In [2]:
import pandas as pd
import requests
import numpy as np

In [3]:
from data_ingestor_github import SkillCornerDataIngestor

In [4]:
di = SkillCornerDataIngestor()

In [4]:
data = di.load_data(match_id=1886347)

/Users/mihirthalanki/Documents/MT/Hackathon/PlayTactix/backend/services/data_ingestor_github.py:142: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  players_df['start_time'] = pd.to_datetime(players_df['start_time'])
/Users/mihirthalanki/Documents/MT/Hackathon/PlayTactix/backend/services/data_ingestor_github.py:143: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  players_df['end_time'] = pd.to_datetime(players_df['end_time'])

In [5]:
import json
with open (f"../../data/gold_tracking_data.json", "r") as f:
    gold_tracking_data = json.load(f)

frames = gold_tracking_data['frames']

In [7]:
start=1000
end=1050
filtered_frames = {frame_num: frames[str(frame_num)] for frame_num in range(start, end + 1) if str(frame_num) in frames}
filtered_frames

{1000: {'period': 1.0,
  'players': {'x': [-24.91,
    8.94,
    7.91,
    31.42,
    29.79,
    29.27,
    34.71,
    31.97,
    38.18,
    32.26,
    38.03,
    49.24,
    38.19,
    38.2,
    36.89,
    38.28,
    34.49,
    35.28,
    30.09,
    35.19,
    30.64,
    9.55],
   'y': [-5.68,
    -26.5,
    -10.16,
    -33.71,
    3.85,
    -27.74,
    -24.35,
    -7.35,
    -25.72,
    -2.36,
    -14.9,
    -0.59,
    -8.16,
    -14.31,
    -2.86,
    -24.17,
    -13.44,
    -23.69,
    -1.72,
    -29.3,
    -27.34,
    -17.6],
   'player_id': [51009,
    176224,
    51649,
    50983,
    735578,
    50978,
    735574,
    795507,
    795505,
    735573,
    966120,
    285188,
    51667,
    33697,
    51713,
    133498,
    14736,
    23418,
    133501,
    965685,
    50951,
    38673],
   'id': [51009,
    176224,
    51649,
    50983,
    735578,
    50978,
    735574,
    795507,
    795505,
    735573,
    966120,
    285188,
    51667,
    33697,
    51713,
    133498,
    14736,
    23418,
    133501,
    965685,
    50951,
    38673],
   'short_name': ['R. Scott',
    'P. Cancar',
    'A. Šušnjar',
    'D. Ingham',
    'M. Natta',
    'C. Timmins',
    'K. Grozos',
    'L. Bayliss',
    'E. Adams',
    'T. Aquilina',
    'B. Gibson',
    'A. Paulsen',
    'D. Hall',
    'N. Pijnaker',
    'C. Elliott',
    'F. De Vries',
    'L. Verstraete',
    'F. Gallegos',
    'L. Rogerson',
    'L. Gillion',
    'J. Brimmer',
    'G. May'],
   'number': [1,
    4,
    15,
    14,
    33,
    19,
    17,
    37,
    7,
    39,
    22,
    12,
    23,
    4,
    17,
    15,
    6,
    28,
    27,
    14,
    22,
    10],
   'team_id': [1805,
    1805,
    1805,
    1805,
    1805,
    1805,
    1805,
    1805,
    1805,
    1805,
    1805,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177],
   'total_time': [5400,
    5400,
    5400,
    5400,
    5400,
    5098,
    5400,
    3615,
    5098,
    5400,
    4063,
    5400,
    5400,
    5400,
    5400,
    5400,
    5400,
    5400,
    4193,
    5400,
    4597,
    5121],
   'player_role.name': ['Goalkeeper',
    'Right Center Back',
    'Left Center Back',
    'Right Back',
    'Left Back',
    'Left Defensive Midfield',
    'Right Defensive Midfield',
    'Attacking Midfield',
    'Right Winger',
    'Left Winger',
    'Center Forward',
    'Goalkeeper',
    'Right Center Back',
    'Left Center Back',
    'Right Back',
    'Left Back',
    'Defensive Midfield',
    'Attacking Midfield',
    'Right Winger',
    'Left Winger',
    'Center Forward',
    'Center Forward'],
   'player_role.acronym': ['GK',
    'RCB',
    'LCB',
    'RB',
    'LB',
    'LDM',
    'RDM',
    'AM',
    'RW',
    'LW',
    'CF',
    'GK',
    'RCB',
    'LCB',
    'RB',
    'LB',
    'DM',
    'AM',
    'RW',
    'LW',
    'CF',
    'CF'],
   'is_gk': [True,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    True,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False],
   'direction_player_1st_half': ['left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left'],
   'direction_player_2nd_half': ['right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right']},
  'ball': {'ball_x': 29.41, 'ball_y': -30.47, 'ball_z': 0.22}},
 1001: {'period': 1.0,
  'players': {'x': [-24.89,
    8.92,
    7.91,
    31.2,
    29.78,
    29.28,
    34.45,
    31.83,
    37.98,
    32.11,
    37.87,
    49.24,
    38.08,
    38.03,
    36.85,
    38.09,
    34.36,
    35.16,
    29.94,
    34.77,
    30.62,
    9.6],
   'y': [-5.69,
    -26.61,
    -10.19,
    -33.69,
    3.8,
    -27.86,
    -24.45,
    -7.4,
    -25.77,
    -2.31,
    -14.92,
    -0.57,
    -8.16,
    -14.37,
    -2.78,
    -24.26,
    -13.46,
    -23.85,
    -1.78,
    -29.54,
    -27.41,
    -17.71],
   'player_id': [51009,
    176224,
    51649,
    50983,
    735578,
    50978,
    735574,
    795507,
    795505,
    735573,
    966120,
    285188,
    51667,
    33697,
    51713,
    133498,
    14736,
    23418,
    133501,
    965685,
    50951,
    38673],
   'id': [51009,
    176224,
    51649,
    50983,
    735578,
    50978,
    735574,
    795507,
    795505,
    735573,
    966120,
    285188,
    51667,
    33697,
    51713,
    133498,
    14736,
    23418,
    133501,
    965685,
    50951,
    38673],
   'short_name': ['R. Scott',
    'P. Cancar',
    'A. Šušnjar',
    'D. Ingham',
    'M. Natta',
    'C. Timmins',
    'K. Grozos',
    'L. Bayliss',
    'E. Adams',
    'T. Aquilina',
    'B. Gibson',
    'A. Paulsen',
    'D. Hall',
    'N. Pijnaker',
    'C. Elliott',
    'F. De Vries',
    'L. Verstraete',
    'F. Gallegos',
    'L. Rogerson',
    'L. Gillion',
    'J. Brimmer',
    'G. May'],
   'number': [1,
    4,
    15,
    14,
    33,
    19,
    17,
    37,
    7,
    39,
    22,
    12,
    23,
    4,
    17,
    15,
    6,
    28,
    27,
    14,
    22,
    10],
   'team_id': [1805,
    1805,
    1805,
    1805,
    1805,
    1805,
    1805,
    1805,
    1805,
    1805,
    1805,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177],
   'total_time': [5400,
    5400,
    5400,
    5400,
    5400,
    5098,
    5400,
    3615,
    5098,
    5400,
    4063,
    5400,
    5400,
    5400,
    5400,
    5400,
    5400,
    5400,
    4193,
    5400,
    4597,
    5121],
   'player_role.name': ['Goalkeeper',
    'Right Center Back',
    'Left Center Back',
    'Right Back',
    'Left Back',
    'Left Defensive Midfield',
    'Right Defensive Midfield',
    'Attacking Midfield',
    'Right Winger',
    'Left Winger',
    'Center Forward',
    'Goalkeeper',
    'Right Center Back',
    'Left Center Back',
    'Right Back',
    'Left Back',
    'Defensive Midfield',
    'Attacking Midfield',
    'Right Winger',
    'Left Winger',
    'Center Forward',
    'Center Forward'],
   'player_role.acronym': ['GK',
    'RCB',
    'LCB',
    'RB',
    'LB',
    'LDM',
    'RDM',
    'AM',
    'RW',
    'LW',
    'CF',
    'GK',
    'RCB',
    'LCB',
    'RB',
    'LB',
    'DM',
    'AM',
    'RW',
    'LW',
    'CF',
    'CF'],
   'is_gk': [True,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    True,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False],
   'direction_player_1st_half': ['left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left'],
   'direction_player_2nd_half': ['right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right']},
  'ball': {'ball_x': 29.48, 'ball_y': -30.99, 'ball_z': 0.22}},
 1002: {'period': 1.0,
  'players': {'x': [-24.89,
    8.89,
    7.91,
    30.98,
    29.76,
    29.29,
    34.19,
    31.7,
    37.79,
    31.96,
    37.72,
    49.23,
    37.98,
    37.86,
    36.81,
    37.91,
    34.23,
    35.04,
    29.8,
    34.34,
    30.59,
    9.63],
   'y': [-5.71,
    -26.71,
    -10.22,
    -33.67,
    3.75,
    -27.97,
    -24.56,
    -7.44,
    -25.82,
    -2.26,
    -14.95,
    -0.56,
    -8.16,
    -14.44,
    -2.69,
    -24.35,
    -13.49,
    -24.02,
    -1.86,
    -29.8,
    -27.47,
    -17.82],
   'player_id': [51009,
    176224,
    51649,
    50983,
    735578,
    50978,
    735574,
    795507,
    795505,
    735573,
    966120,
    285188,
    51667,
    33697,
    51713,
    133498,
    14736,
    23418,
    133501,
    965685,
    50951,
    38673],
   'id': [51009,
    176224,
    51649,
    50983,
    735578,
    50978,
    735574,
    795507,
    795505,
    735573,
    966120,
    285188,
    51667,
    33697,
    51713,
    133498,
    14736,
    23418,
    133501,
    965685,
    50951,
    38673],
   'short_name': ['R. Scott',
    'P. Cancar',
    'A. Šušnjar',
    'D. Ingham',
    'M. Natta',
    'C. Timmins',
    'K. Grozos',
    'L. Bayliss',
    'E. Adams',
    'T. Aquilina',
    'B. Gibson',
    'A. Paulsen',
    'D. Hall',
    'N. Pijnaker',
    'C. Elliott',
    'F. De Vries',
    'L. Verstraete',
    'F. Gallegos',
    'L. Rogerson',
    'L. Gillion',
    'J. Brimmer',
    'G. May'],
   'number': [1,
    4,
    15,
    14,
    33,
    19,
    17,
    37,
    7,
    39,
    22,
    12,
    23,
    4,
    17,
    15,
    6,
    28,
    27,
    14,
    22,
    10],
   'team_id': [1805,
    1805,
    1805,
    1805,
    1805,
    1805,
    1805,
    1805,
    1805,
    1805,
    1805,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177],
   'total_time': [5400,
    5400,
    5400,
    5400,
    5400,
    5098,
    5400,
    3615,
    5098,
    5400,
    4063,
    5400,
    5400,
    5400,
    5400,
    5400,
    5400,
    5400,
    4193,
    5400,
    4597,
    5121],
   'player_role.name': ['Goalkeeper',
    'Right Center Back',
    'Left Center Back',
    'Right Back',
    'Left Back',
    'Left Defensive Midfield',
    'Right Defensive Midfield',
    'Attacking Midfield',
    'Right Winger',
    'Left Winger',
    'Center Forward',
    'Goalkeeper',
    'Right Center Back',
    'Left Center Back',
    'Right Back',
    'Left Back',
    'Defensive Midfield',
    'Attacking Midfield',
    'Right Winger',
    'Left Winger',
    'Center Forward',
    'Center Forward'],
   'player_role.acronym': ['GK',
    'RCB',
    'LCB',
    'RB',
    'LB',
    'LDM',
    'RDM',
    'AM',
    'RW',
    'LW',
    'CF',
    'GK',
    'RCB',
    'LCB',
    'RB',
    'LB',
    'DM',
    'AM',
    'RW',
    'LW',
    'CF',
    'CF'],
   'is_gk': [True,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    True,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False],
   'direction_player_1st_half': ['left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left'],
   'direction_player_2nd_half': ['right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right']},
  'ball': {'ball_x': 29.53, 'ball_y': -31.44, 'ball_z': 0.22}},
 1003: {'period': 1.0,
  'players': {'x': [-24.87,
    8.86,
    7.91,
    30.77,
    29.73,
    29.28,
    33.93,
    31.57,
    37.59,
    31.8,
    37.56,
    49.22,
    37.86,
    37.69,
    36.77,
    37.72,
    34.09,
    34.9,
    29.66,
    33.91,
    30.56,
    9.67],
   'y': [-5.74,
    -26.83,
    -10.25,
    -33.64,
    3.7,
    -28.08,
    -24.67,
    -7.47,
    -25.88,
    -2.2,
    -14.98,
    -0.54,
    -8.15,
    -14.52,
    -2.61,
    -24.44,
    -13.52,
    -24.2,
    -1.93,
    -30.05,
    -27.53,
    -17.93],
   'player_id': [51009,
    176224,
    51649,
    50983,
    735578,
    50978,
    735574,
    795507,
    795505,
    735573,
    966120,
    285188,
    51667,
    33697,
    51713,
    133498,
    14736,
    23418,
    133501,
    965685,
    50951,
    38673],
   'id': [51009,
    176224,
    51649,
    50983,
    735578,
    50978,
    735574,
    795507,
    795505,
    735573,
    966120,
    285188,
    51667,
    33697,
    51713,
    133498,
    14736,
    23418,
    133501,
    965685,
    50951,
    38673],
   'short_name': ['R. Scott',
    'P. Cancar',
    'A. Šušnjar',
    'D. Ingham',
    'M. Natta',
    'C. Timmins',
    'K. Grozos',
    'L. Bayliss',
    'E. Adams',
    'T. Aquilina',
    'B. Gibson',
    'A. Paulsen',
    'D. Hall',
    'N. Pijnaker',
    'C. Elliott',
    'F. De Vries',
    'L. Verstraete',
    'F. Gallegos',
    'L. Rogerson',
    'L. Gillion',
    'J. Brimmer',
    'G. May'],
   'number': [1,
    4,
    15,
    14,
    33,
    19,
    17,
    37,
    7,
    39,
    22,
    12,
    23,
    4,
    17,
    15,
    6,
    28,
    27,
    14,
    22,
    10],
   'team_id': [1805,
    1805,
    1805,
    1805,
    1805,
    1805,
    1805,
    1805,
    1805,
    1805,
    1805,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177],
   'total_time': [5400,
    5400,
    5400,
    5400,
    5400,
    5098,
    5400,
    3615,
    5098,
    5400,
    4063,
    5400,
    5400,
    5400,
    5400,
    5400,
    5400,
    5400,
    4193,
    5400,
    4597,
    5121],
   'player_role.name': ['Goalkeeper',
    'Right Center Back',
    'Left Center Back',
    'Right Back',
    'Left Back',
    'Left Defensive Midfield',
    'Right Defensive Midfield',
    'Attacking Midfield',
    'Right Winger',
    'Left Winger',
    'Center Forward',
    'Goalkeeper',
    'Right Center Back',
    'Left Center Back',
    'Right Back',
    'Left Back',
    'Defensive Midfield',
    'Attacking Midfield',
    'Right Winger',
    'Left Winger',
    'Center Forward',
    'Center Forward'],
   'player_role.acronym': ['GK',
    'RCB',
    'LCB',
    'RB',
    'LB',
    'LDM',
    'RDM',
    'AM',
    'RW',
    'LW',
    'CF',
    'GK',
    'RCB',
    'LCB',
    'RB',
    'LB',
    'DM',
    'AM',
    'RW',
    'LW',
    'CF',
    'CF'],
   'is_gk': [True,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    True,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False],
   'direction_player_1st_half': ['left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left'],
   'direction_player_2nd_half': ['right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right']},
  'ball': {'ball_x': 29.6, 'ball_y': -31.83, 'ball_z': 0.21}},
 1004: {'period': 1.0,
  'players': {'x': [-24.86,
    8.83,
    7.91,
    30.58,
    29.7,
    29.27,
    33.67,
    31.44,
    37.38,
    31.64,
    37.39,
    49.21,
    37.75,
    37.52,
    36.73,
    37.54,
    33.95,
    34.75,
    29.52,
    33.48,
    30.53,
    9.7],
   'y': [-5.77,
    -26.94,
    -10.29,
    -33.63,
    3.65,
    -28.19,
    -24.78,
    -7.51,
    -25.95,
    -2.15,
    -15.02,
    -0.52,
    -8.14,
    -14.61,
    -2.54,
    -24.54,
    -13.54,
    -24.38,
    -2.01,
    -30.32,
    -27.6,
    -18.04],
   'player_id': [51009,
    176224,
    51649,
    50983,
    735578,
    50978,
    735574,
    795507,
    795505,
    735573,
    966120,
    285188,
    51667,
    33697,
    51713,
    133498,
    14736,
    23418,
    133501,
    965685,
    50951,
    38673],
   'id': [51009,
    176224,
    51649,
    50983,
    735578,
    50978,
    735574,
    795507,
    795505,
    735573,
    966120,
    285188,
    51667,
    33697,
    51713,
    133498,
    14736,
    23418,
    133501,
    965685,
    50951,
    38673],
   'short_name': ['R. Scott',
    'P. Cancar',
    'A. Šušnjar',
    'D. Ingham',
    'M. Natta',
    'C. Timmins',
    'K. Grozos',
    'L. Bayliss',
    'E. Adams',
    'T. Aquilina',
    'B. Gibson',
    'A. Paulsen',
    'D. Hall',
    'N. Pijnaker',
    'C. Elliott',
    'F. De Vries',
    'L. Verstraete',
    'F. Gallegos',
    'L. Rogerson',
    'L. Gillion',
    'J. Brimmer',
    'G. May'],
   'number': [1,
    4,
    15,
    14,
    33,
    19,
    17,
    37,
    7,
    39,
    22,
    12,
    23,
    4,
    17,
    15,
    6,
    28,
    27,
    14,
    22,
    10],
   'team_id': [1805,
    1805,
    1805,
    1805,
    1805,
    1805,
    1805,
    1805,
    1805,
    1805,
    1805,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177],
   'total_time': [5400,
    5400,
    5400,
    5400,
    5400,
    5098,
    5400,
    3615,
    5098,
    5400,
    4063,
    5400,
    5400,
    5400,
    5400,
    5400,
    5400,
    5400,
    4193,
    5400,
    4597,
    5121],
   'player_role.name': ['Goalkeeper',
    'Right Center Back',
    'Left Center Back',
    'Right Back',
    'Left Back',
    'Left Defensive Midfield',
    'Right Defensive Midfield',
    'Attacking Midfield',
    'Right Winger',
    'Left Winger',
    'Center Forward',
    'Goalkeeper',
    'Right Center Back',
    'Left Center Back',
    'Right Back',
    'Left Back',
    'Defensive Midfield',
    'Attacking Midfield',
    'Right Winger',
    'Left Winger',
    'Center Forward',
    'Center Forward'],
   'player_role.acronym': ['GK',
    'RCB',
    'LCB',
    'RB',
    'LB',
    'LDM',
    'RDM',
    'AM',
    'RW',
    'LW',
    'CF',
    'GK',
    'RCB',
    'LCB',
    'RB',
    'LB',
    'DM',
    'AM',
    'RW',
    'LW',
    'CF',
    'CF'],
   'is_gk': [True,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    True,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False],
   'direction_player_1st_half': ['left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',

In [6]:
# import pickle

# with open(f"../../data/gold_tracking_data.pkl", "rb") as f:
#     gold_tracking_data = pickle.load(f)
# gold_tracking_data

In [7]:
# gold_tracking_data[10].to_dict(orient="records")

In [7]:
bronze_tracking_data = di._get_bronze_tracking_data(match_id=1886347)
# silver_tracking_data = di._get_silver_tracking_data(bronze_tracking_data)
bronze_meta_data = di._get_bronze_meta_data(match_id=1886347)
# silver_meta_data = di._get_silver_meta_data(bronze_meta_data)
# gold_data = di._get_gold_tracking_data(silver_tracking_data, silver_meta_data)

In [9]:
bronze_meta_data

{'id': 1886347,
 'home_team_score': 2,
 'away_team_score': 0,
 'date_time': '2024-11-30T04:00:00Z',
 'stadium': {'id': 3811,
  'name': 'Mount Smart Stadium',
  'city': 'Auckland',
  'capacity': 25000},
 'home_team': {'id': 4177,
  'name': 'Auckland FC',
  'short_name': 'Auckland FC',
  'acronym': 'AUC'},
 'home_team_kit': {'id': 14025,
  'team_id': 4177,
  'season': {'id': 95,
   'start_year': 2024,
   'end_year': 2025,
   'name': '2024/2025'},
  'name': 'Home',
  'jersey_color': '#2800f0',
  'number_color': '#ffffff'},
 'away_team': {'id': 1805,
  'name': 'Newcastle United Jets FC',
  'short_name': 'Newcastle',
  'acronym': 'NEW'},
 'away_team_kit': {'id': 10376,
  'team_id': 1805,
  'season': {'id': 29, 'start_year': 2024, 'end_year': 2024, 'name': '2024'},
  'name': 'away',
  'jersey_color': '#ffffff',
  'number_color': '#000000'},
 'home_team_coach': None,
 'away_team_coach': None,
 'home_team_playing_time': {'minutes_tip': 31.13, 'minutes_otip': 22.2},
 'away_team_playing_time': {'minutes_tip': 22.2, 'minutes_otip': 31.13},
 'competition_edition': {'id': 870,
  'competition': {'id': 61,
   'area': 'AUS',
   'name': 'A-League',
   'gender': 'male',
   'age_group': 'adult'},
  'season': {'id': 95,
   'start_year': 2024,
   'end_year': 2025,
   'name': '2024/2025'},
  'name': 'AUS - A-League - 2024/2025'},
 'match_periods': [{'period': 1,
   'name': 'period_1',
   'start_frame': 10,
   'end_frame': 27790,
   'duration_frames': 27780,
   'duration_minutes': 46.3},
  {'period': 2,
   'name': 'period_2',
   'start_frame': 27800,
   'end_frame': 59060,
   'duration_frames': 31260,
   'duration_minutes': 52.1}],
 'competition_round': {'id': 611,
  'name': 'Round 6',
  'round_number': 6,
  'potential_overtime': False},
 'referees': [],
 'players': [{'player_role': {'id': 15,
    'position_group': 'Center Forward',
    'name': 'Center Forward',
    'acronym': 'CF'},
   'start_time': '00:00:00',
   'end_time': '01:25:21',
   'number': 10,
   'yellow_card': 0,
   'red_card': 0,
   'injured': False,
   'goal': 0,
   'own_goal': 0,
   'playing_time': {'total': {'minutes_tip': 29.55,
     'minutes_otip': 18.76,
     'start_frame': 10,
     'end_frame': 52009,
     'minutes_played': 86.65,
     'minutes_played_regular_time': 86.65},
    'by_period': [{'name': 'period_1',
      'minutes_tip': 18.21,
      'minutes_otip': 11.03,
      'start_frame': 10,
      'end_frame': 27790,
      'minutes_played': 46.3},
     {'name': 'period_2',
      'minutes_tip': 11.34,
      'minutes_otip': 7.73,
      'start_frame': 27800,
      'end_frame': 52009,
      'minutes_played': 40.35}]},
   'team_player_id': 1507965,
   'team_id': 4177,
   'id': 38673,
   'first_name': 'Guillermo Luis',
   'last_name': 'May Bartesaghi',
   'short_name': 'G. May',
   'birthday': '1998-03-11',
   'trackable_object': 39794,
   'gender': 'male'},
  {'player_role': {'id': 20,
    'position_group': 'Full Back',
    'name': 'Right Back',
    'acronym': 'RB'},
   'start_time': '00:00:00',
   'end_time': None,
   'number': 17,
   'yellow_card': 0,
   'red_card': 0,
   'injured': False,
   'goal': 0,
   'own_goal': 0,
   'playing_time': {'total': {'minutes_tip': 31.13,
     'minutes_otip': 22.2,
     'start_frame': 10,
     'end_frame': 59059,
     'minutes_played': 98.4,
     'minutes_played_regular_time': 98.4},
    'by_period': [{'name': 'period_1',
      'minutes_tip': 18.21,
      'minutes_otip': 11.03,
      'start_frame': 10,
      'end_frame': 27790,
      'minutes_played': 46.3},
     {'name': 'period_2',
      'minutes_tip': 12.92,
      'minutes_otip': 11.18,
      'start_frame': 27800,
      'end_frame': 59059,
      'minutes_played': 52.1}]},
   'team_player_id': 1507968,
   'team_id': 4177,
   'id': 51713,
   'first_name': 'Callan',
   'last_name': 'Elliot',
   'short_name': 'C. Elliott',
   'birthday': '1999-07-07',
   'trackable_object': 52839,
   'gender': 'male'},
  {'player_role': {'id': 15,
    'position_group': 'Center Forward',
    'name': 'Center Forward',
    'acronym': 'CF'},
   'start_time': '00:00:00',
   'end_time': '01:16:37',
   'number': 22,
   'yellow_card': 0,
   'red_card': 0,
   'injured': False,
   'goal': 0,
   'own_goal': 0,
   'playing_time': {'total': {'minutes_tip': 26.28,
     'minutes_otip': 17.94,
     'start_frame': 10,
     'end_frame': 46769,
     'minutes_played': 77.91,
     'minutes_played_regular_time': 77.91},
    'by_period': [{'name': 'period_1',
      'minutes_tip': 18.21,
      'minutes_otip': 11.03,
      'start_frame': 10,
      'end_frame': 27790,
      'minutes_played': 46.3},
     {'name': 'period_2',
      'minutes_tip': 8.07,
      'minutes_otip': 6.91,
      'start_frame': 27800,
      'end_frame': 46769,
      'minutes_played': 31.62}]},
   'team_player_id': 1507963,
   'team_id': 4177,
   'id': 50951,
   'first_name': 'Jake',
   'last_name': 'Brimmer',
   'short_name': 'J. Brimmer',
   'birthday': '1998-04-03',
   'trackable_object': 52077,
   'gender': 'male'},
  {'player_role': {'id': 21,
    'position_group': 'Midfield',
    'name': 'Left Defensive Midfield',
    'acronym': 'LDM'},
   'start_time': '00:00:00',
   'end_time': '01:24:58',
   'number': 19,
   'yellow_card': 1,
   'red_card': 0,
   'injured': False,
   'goal': 0,
   'own_goal': 0,
   'playing_time': {'total': {'minutes_tip': 18.76,
     'minutes_otip': 29.55,
     'start_frame': 10,
     'end_frame': 51779,
     'minutes_played': 86.26,
     'minutes_played_regular_time': 86.26},
    'by_period': [{'name': 'period_1',
      'minutes_tip': 11.03,
      'minutes_otip': 18.21,
      'start_frame': 10,
      'end_frame': 27790,
      'minutes_played': 46.3},
     {'name': 'period_2',
      'minutes_tip': 7.73,
      'minutes_otip': 11.34,
      'start_frame': 27800,
      'end_frame': 51779,
      'minutes_played': 39.97}]},
   'team_player_id': 1087119,
   'team_id': 1805,
   'id': 50978,
   'first_name': 'Callum',
   'last_name': 'Timmins',
   'short_name': 'C. Timmins',
   'birthday': '1999-12-23',
   'trackable_object': 52104,
   'gender': 'male'},
  {'player_role': {'id': 19,
    'position_group': 'Full Back',
    'name': 'Left Back',
    'acronym': 'LB'},
   'start_time': '00:00:00',
   'end_time': None,
   'number': 15,
   'yellow_card': 0,
   'red_card': 0,
   'injured': False,
   'goal': 1,
   'own_goal': 0,
   'playing_time': {'total': {'minutes_tip': 31.13,
     'minutes_otip': 22.2,
     'start_frame': 10,
     'end_frame': 59059,
     'minutes_played': 98.4,
     'minutes_played_regular_time': 98.4},
    'by_period': [{'name': 'period_1',
      'minutes_tip': 18.21,
      'minutes_otip': 11.03,
      'start_frame': 10,
      'end_frame': 27790,
      'minutes_played': 46.3},
     {'name': 'period_2',
      'minutes_tip': 12.92,
      'minutes_otip': 11.18,
      'start_frame': 27800,
      'end_frame': 59059,
      'minutes_played': 52.1}]},
   'team_player_id': 1507956,
   'team_id': 4177,
   'id': 133498,
   'first_name': 'Francis',
   'last_name': 'De Vries',
   'short_name': 'F. De Vries',
   'birthday': '1994-11-28',
   'trackable_object': 135053,
   'gender': 'male'},
  {'player_role': {'id': 3,
    'position_group': 'Central Defender',
    'name': 'Left Center Back',
    'acronym': 'LCB'},
   'start_time': '00:00:00',
   'end_time': None,
   'number': 4,
   'yellow_card': 1,
   'red_card': 0,
   'injured': False,
   'goal': 0,
   'own_goal': 0,
   'playing_time': {'total': {'minutes_tip': 31.13,
     'minutes_otip': 22.2,
     'start_frame': 10,
     'end_frame': 59059,
     'minutes_played': 98.4,
     'minutes_played_regular_time': 98.4},
    'by_period': [{'name': 'period_1',
      'minutes_tip': 18.21,
      'minutes_otip': 11.03,
      'start_frame': 10,
      'end_frame': 27790,
      'minutes_played': 46.3},
     {'name': 'period_2',
      'minutes_tip': 12.92,
      'minutes_otip': 11.18,
      'start_frame': 27800,
      'end_frame': 59059,
      'minutes_played': 52.1}]},
   'team_player_id': 1507971,
   'team_id': 4177,
   'id': 33697,
   'first_name': 'Nando',
   'last_name': 'Pijnaker',
   'short_name': 'N. Pijnaker',
   'birthday': '1999-02-25',
   'trackable_object': 34805,
   'gender': 'male'},
  {'player_role': {'id': 4,
    'position_group': 'Central Defender',
    'name': 'Right Center Back',
    'acronym': 'RCB'},
   'start_time': '00:00:00',
   'end_time': None,
   'number': 23,
   'yellow_card': 0,
   'red_card': 0,
   'injured': False,
   'goal': 0,
   'own_goal': 0,
   'playing_time': {'total': {'minutes_tip': 31.13,
     'minutes_otip': 22.2,
     'start_frame': 10,
     'end_frame': 59059,
     'minutes_played': 98.4,
     'minutes_played_regular_time': 98.4},
    'by_period': [{'name': 'period_1',
      'minutes_tip': 18.21,
      'minutes_otip': 11.03,
      'start_frame': 10,
      'end_frame': 27790,
      'minutes_played': 46.3},
     {'name': 'period_2',
      'minutes_tip': 12.92,
      'minutes_otip': 11.18,
      'start_frame': 27800,
      'end_frame': 59059,
      'minutes_played': 52.1}]},
   'team_player_id': 1507974,
   'team_id': 4177,
   'id': 51667,
   'first_name': 'Daniel',
   'last_name': 'Hall',
   'short_name': 'D. Hall',
   'birthday': '1999-06-14',
   'trackable_object': 52793,
   'gender': 'male'},
  {'player_role': {'id': 7,
    'position_group': 'Midfield',
    'name': 'Defensive Midfield',
    'acronym': 'DM'},
   'start_time': '00:00:00',
   'end_time': None,
   'number': 6,
   'yellow_card': 0,
   'red_card': 0,
   'injured': False,
   'goal': 0,
   'own_goal': 0,
   'playing_time': {'total': {'minutes_tip': 31.13,
     'minutes_otip': 22.2,
     'start_frame': 10,
     'end_frame': 59059,
     'minutes_played': 98.4,
     'minutes_played_regular_time': 98.4},
    'by_period': [{'name': 'period_1',
      'minutes_tip': 18.21,
      'minutes_otip': 11.03,
      'start_frame': 10,
      'end_frame': 27790,
      'minutes_played': 46.3},
     {'name': 'period_2',
      'minutes_tip': 12.92,
      'minutes_otip': 11.18,
      'start_frame': 27800,
      'end_frame': 59059,
      'minutes_played': 52.1}]},
   'team_player_id': 1507966,
   'team_id': 4177,
   'id': 14736,
   'first_name': 'Louis',
   'last_name': 'Verstraete',
   'short_name': 'L. Verstraete',
   'birthday': '1999-05-04',
   'trackable_object': 14933,
   'gender': 'male'},
  {'player_role': {'id': 17,
    'position_group': 'Other',
    'name': 'Substitute',
    'acronym': 'SUB'},
   'start_time': None,
   'end_time': None,
   'number': 28,
   'yellow_card': 0,
   'red_card': 0,
   'injured': False,
   'goal': 0,
   'own_goal': 0,
   'playing_time': {'total': None, 'by_period': []},
   'team_player_id': 1508548,
   'team_id': 1805,
   'id': 966125,
   'first_name': 'Will ',
   'last_name': 'Dobson',
   'short_name': 'W. Will Dobson',
   'birthday': None,
   'trackable_object': 967688,
   'gender': 'male'},
  {'player_role': {'id': 17,
    'position_group': 'Other',
    'name': 'Substitute',
    'acronym': 'SUB'},
   'start_time': None,
   'end_time': None,
   'number': 21,
   'yellow_card': 0,
   'red_card': 0,
   'injured': False,
   'goal': 0,
   'own_goal': 0,
   'playing_time': {'total': None, 'by_period': []},
   'team_player_id': 1508547,
   'team_id': 1805,
   'id': 966124,
   'first_name': 'Noah Paul',
   'last_name': 'James',
   'short_name': 'N. James',
   'birthday': '2001-02-14',
   'trackable_object': 967687,
   'gender': 'male'},
  {'player_role': {'id': 17,
    'position_group': 'Other',
    'name': 'Substitute',
    'acronym': 'SUB'},
   'start_time': None,
   'end_time': None,
   'number': 27,
   'yellow_card': 0,
   'red_card': 0,
   'injured': False,
   'goal': 0,
   'own_goal': 0,
   'playing_time': {'total': None, 'by_period': []},
   'team_player_id': 1229663,
   'team_id': 1805,
   'id': 808965,
   'first_name': 'Nathan',
   'last_name': 'Grimaldi',
   'short_name': 'N. Grimaldi',
   'birthday': '2001-09-15',
   'trackable_object': 810528,
   'gender': 'male'},
  {'player_role': {'id': 12,
    'position_group': 'Wide Attacker',
    'name': 'Left Winger',
    'acronym': 'LW'},
   'start_time': '00:00:00',
   'end_time': None,
   'number': 39,
   'yellow_card': 0,
   'red_card': 0,
   'injured': False,
   'goal': 0,
   'own_goal': 0,
   'playing_time': {'total': {'minutes_tip': 22.2,
     'minutes_otip': 31.13,
     'start_frame': 10,
     'end_frame': 59059,
     'minutes_played': 98.4,
     'minutes_played_regular_time': 98.4},
    'by_period': [{'name': 'period_1',
      'minutes_tip': 11.03,
      'minutes_otip': 18.21,
      'start_frame': 10,
      'end_frame': 27790,
      'minutes_played': 46.3},
     {'name': 'period_2',
      'minutes_tip': 11.18,
      'minutes_otip': 12.92,
      'start_frame': 27800,
      'end_frame': 59059,
      'minutes_played': 52.1}]},
   'team_player_id': 1087109,
   'team_id': 1805,
   'id': 735573,
   'first_name': 'Thomas',
   'last_name': 'Aquilina',
   'short_name': 'T. Aquilina',
   'birthday': '2001-02-02',
   'trackable_object': 737136,
   'gender': 'male'},
  {'player_role': {'id': 0,
    'position_group': 'Other',
    'name': 'Goalkeeper',
    'acronym': 'GK'},
   'start_time': '00:00:00',
   'end_time': None,
   'number': 1,
   'yellow_card': 0,
   'red_card': 0,
   'injured': False,
   'goal': 0,
   'own_goal': 0,
   'playing_time': {'total': {'minutes_tip': 22.2,
     'minutes_otip': 31.13,
     'start_frame': 10,
     'end_frame': 59059,
     'minutes_played': 98.4,
     'minutes_played_regular_time': 98.4},
    'by_period': [{'name': 'period_1',
      'minutes_tip': 11.03,
      'minutes_otip': 18.21,
      'start_frame': 10,
      'end_frame': 27790,
      'minutes_played': 46.3},
     {'name': 'period_2',
      'minutes_tip': 11.18,
      'minutes_otip': 12.92,
      'start_frame': 27800,
      'end_frame': 59059,
      'minutes_played': 52.1}]},
   'team_player_id': 1204873,
   'team_id': 1805,
   'id': 51009,
   'first_name': 'Ryan',
   'last_name': 'Scott',
   'short_name': 'R. Scott',
   'birthday': '1995-12-18',
   'trackable_object': 52135,
   'gender': 'male'},
  {'player_role': {'id': 4,
    'position_group': 'Central Defender',
    'name': 'Right Center Back',
    'acronym': 'RCB'},
   'start_time': '00:00:00',
   'end_time': None,
   'number': 4,
   'yellow_card': 0,
   'red_card': 0,
   'injured': False,
   'goal': 0,
   'own_goal': 0,
   'playing_time': {'total': {'minutes_tip': 22.2,
     'minutes_otip': 31.13,
     'start_frame': 10,
     'end_frame': 59059,
     'minutes_played': 98.4,
     'minutes_played_regular_time': 98.4},
    'by_period': [{'name': 'period_1',
      'minutes_tip': 11.03,
      'minutes_otip': 18.21,
      'start_frame': 10,
      'end_frame': 27790,
      'minutes_played': 46.3},
     {'name': 'period_2',
      'minutes_tip': 11.18,
      'minutes_otip': 12.92,
      'start_frame': 27800,
      'end_frame': 59059,
      'minutes_played': 52.1}]},
   'team_player_id': 1204875,
   'team_id': 1805,
   'id': 176224,
   'first_name': 'Phillip',
   'last_name': 'Cancar',
   'short_name': 'P. Cancar',
   'birthday': '2001-05-11',
   'trackable_object': 177779,
   'gender': 'male'},
  {'player_role': {'id': 19,
    'position_group': 'Full Back',
    'name': 'Left Back',
    'acronym': 'LB'},
   'start_time': '00:00:00',
   'end_time': None,
   'number': 33,
   'yellow_card': 0,
   'red_card': 0,
   'injured': False,
   'goal': 0,
   'own_goal': 0,
   'playing_time': {'total': {'minutes_tip': 22.2,
     'minutes_otip': 31.13,
     'start_frame': 10,
     'end_frame': 59059,
     'minutes_played': 98.4,
     'minutes_played_regular_time': 98.4},
    'by_period': [{'name': 'period_1',
      'minutes_tip': 11.03,
      'minutes_otip': 18.21,
      'start_frame': 10,
      'end_frame': 27790,
      'minutes_played': 46.3},
     {'name': 'period_2',
      'minutes_tip': 11.18,
      'minutes_otip': 12.92,
      'start_frame': 27800,
      'end_frame': 59059,
      'minutes_played': 52.1}]},
   'team_player_id': 1087123,
   'team_id': 1805,
   'id': 735578,
   'first_name': 'Mark',
   'last_name': 'Natta',
   'short_name': 'M. Natta',
   'birthday': '2002-11-28',
   'trackable_object': 737141,
   'gender': 'male'},
  {'player_role': {'id': 22,
    'position_group': 'Midfield',
    'name': 'Right Defensive Midfield',
    'acronym': 'RDM'},
   'start_time': '00:00:00',
   'end_time': None,
   'number': 17,
   'yellow_card': 0,
   'red_card': 0,
   'injured': False,
   'goal': 0,
   'own_goal': 0,
   'playing_time': {'total': {'minutes_tip': 22.2,
     'minutes_otip': 31.13,
     'start_frame': 10,
     'end_frame': 59059,
     'minutes_played': 98.4,
     'minutes_played_regular_time': 98.4},
    'by_period': [{'name': 'period_1',
      'minutes_tip': 11.03,
      'minutes_otip': 18.21,
      'start_frame': 10,
      'end_frame': 27790,
      'minutes_played': 46.3},
     {'name': 'period_2',
      'minutes_tip': 11.18,
      'minutes_otip': 12.92,
      'start_frame': 27800,
      'end_frame': 59059,
      'minutes_played': 52.1}]},
   'team_player_id': 1087114,
   'team_id': 1805,
   'id': 735574,
   'first_name': 'Kosta',
   'last_name': 'Grozos',
   'short_name': 'K. Grozos',
   'birthday': '2000-08-10',
   'trackable_object': 737137,
   'gender': 'male'},
  {'player_role': {'id': 20,
    'position_group': 'Full Back',
    'name': 'Right Back',
    'acronym': 'RB'},
   'start_time': '00:00:00',
   'end_time': None,
   'number': 14,
   'yellow_card': 1,
   'red_card': 0,
   'injured': False,
   'goal': 0,
   'own_goal': 0,
   'playing_time': {'total': {'minutes_tip': 22.2,
     'minutes_otip': 31.13,
     'start_frame': 10,
     'end_frame': 59059,
     'minutes_played': 98.4,
     'minutes_played_regular_time': 98.4},
    'by_period': [{'name': 'period_1',
      'minutes_tip': 11.03,
      'minutes_otip': 18.21,
      'start_frame': 10,
      'end_frame': 27790,
      'minutes_played': 46.3},
     {'name': 'period_2',
      'minutes_tip': 11.18,
      'minutes_otip': 12.92,
      'start_frame': 27800,
      'end_frame': 59059,
      'minutes_played': 52.1}]},
   'team_player_id': 1087111,
   'team_id': 1805,
   'id': 50983,
   'first_name': 'Dane',
   'last_name': 'Ingham',
   'short_name': 'D. Ingham',
   'birthday': '1999-06-08',
   'trackable_object': 52109,
   'gender': 'male'},
  {'player_role': {'id': 3,
    'position_group': 'Central Defender',
    'name': 'Left Center Back',
    'acronym': 'LCB'},
   'start_time': '00:00:00',
   'end_time': None,
   'number': 15,
   'yellow_card': 1,
   'red_card': 0,
   'injured': False,
   'goal': 0,
   'own_goal': 0,
   'playing_time': {'total': {'minutes_tip': 22.2,
     'minutes_otip': 31.13,
     'start_frame': 10,
     'end_frame': 59059,
     'minutes_played': 98.4,
     'minutes_played_regular_time': 98.4},
    'by_period': [{'name': 'period_1',
      'minutes_tip': 11.03,
      'minutes_otip': 18.21,
      'start_frame': 10,
      'end_frame': 27790,
      'minutes_played': 46.3},
     {'name': 'period_2',
      'minutes_tip': 11.18,
      'minutes_otip': 12.92,
      'start_frame': 27800,
      'end_frame': 59059,
      'minutes_played': 52.1}]},
   'team_player_id': 1508538,
   'team_id': 1805,
   'id': 51649,
   'first_name': 'Aleksandar',
   'last_name': 'Šušnjar',
   'short_name': 'A. Šušnjar',
   'birthday': '1995-08-19',
   'trackable_object': 52775,
   'gender': 'male'},
  {'player_role': {'id': 12,
    'position_group': 'Wide Attacker',
    'name': 'Left Winger',
    'acronym': 'LW'},
   'start_time': '00:00:00',
   'end_time': None,
   'number': 14,
   'yellow_card': 0,
   'red_card': 0,
   'injured': False,
   'goal': 0,
   'own_goal': 0,
   'playing_time': {'total': {'minutes_tip': 31.13,
     'minutes_otip': 22.2,
     'start_frame': 10,
     'end_frame': 59059,
     'minutes_played': 98.4,
     'minutes_played_regular_time': 98.4},
    'by_period': [{'name': 'period_1',
      'minutes_tip': 18.21,
      'minutes_otip': 11.03,
      'start_frame': 10,
      'end_frame': 27790,
      'minutes_played': 46.3},
     {'name': 'period_2',

In [ ]:
# final_df = silver_tracking_data.merge(silver_meta_data, left_on=["player_id"], right_on=["id"])

In [32]:
import pandas as pd
pd.set_option('display.max_columns', None)
final_df[final_df["frame"] == 10]

,x,y,player_id,is_detected,frame,timestamp,period,possession_player_id,possession_group,ball_x,ball_y,ball_z,is_detected_ball,start_time,end_time,match_name,date_time,home_team.name,away_team.name,id,short_name,number,team_id,team_name,player_role.position_group,total_time,player_role.name,player_role.acronym,is_gk,direction_player_1st_half,direction_player_2nd_half
0,-39.63,-0.08,51009,False,10,2026-04-20,1.0,NaN,None,0.32,0.38,0.13,True,2026-04-20,NaT,Auckland FC vs Newcastle United Jets FC,2024-11-30T04:00:00Z,Auckland FC,Newcastle United Jets FC,51009,R. Scott,1,1805,Newcastle United Jets FC,Other,5400,Goalkeeper,GK,True,left_to_right,right_to_left
1,-19.21,-9.18,176224,True,10,2026-04-20,1.0,NaN,None,0.32,0.38,0.13,True,2026-04-20,NaT,Auckland FC vs Newcastle United Jets FC,2024-11-30T04:00:00Z,Auckland FC,Newcastle United Jets FC,176224,P. Cancar,4,1805,Newcastle United Jets FC,Central Defender,5400,Right Center Back,RCB,False,left_to_right,right_to_left
2,-21.83,0.47,51649,True,10,2026-04-20,1.0,NaN,None,0.32,0.38,0.13,True,2026-04-20,NaT,Auckland FC vs Newcastle United Jets FC,2024-11-30T04:00:00Z,Auckland FC,Newcastle United Jets FC,51649,A. Šušnjar,15,1805,Newcastle United Jets FC,Central Defender,5400,Left Center Back,LCB,False,left_to_right,right_to_left
3,-1.16,-32.47,50983,True,10,2026-04-20,1.0,NaN,None,0.32,0.38,0.13,True,2026-04-20,NaT,Auckland FC vs Newcastle United Jets FC,2024-11-30T04:00:00Z,Auckland FC,Newcastle United Jets FC,50983,D. Ingham,14,1805,Newcastle United Jets FC,Full Back,5400,Right Back,RB,False,left_to_right,right_to_left
4,-18.88,15.73,735578,True,10,2026-04-20,1.0,NaN,None,0.32,0.38,0.13,True,2026-04-20,NaT,Auckland FC vs Newcastle United Jets FC,2024-11-30T04:00:00Z,Auckland FC,Newcastle United Jets FC,735578,M. Natta,33,1805,Newcastle United Jets FC,Full Back,5400,Left Back,LB,False,left_to_right,right_to_left
5,-7.41,7.13,50978,True,10,2026-04-20,1.0,NaN,None,0.32,0.38,0.13,True,2026-04-20,2026-04-20 01:24:58,Auckland FC vs Newcastle United Jets FC,2024-11-30T04:00:00Z,Auckland FC,Newcastle United Jets FC,50978,C. Timmins,19,1805,Newcastle United Jets FC,Midfield,5098,Left Defensive Midfield,LDM,False,left_to_right,right_to_left
6,-9.51,-5.01,735574,True,10,2026-04-20,1.0,NaN,None,0.32,0.38,0.13,True,2026-04-20,NaT,Auckland FC vs Newcastle United Jets FC,2024-11-30T04:00:00Z,Auckland FC,Newcastle United Jets FC,735574,K. Grozos,17,1805,Newcastle United Jets FC,Midfield,5400,Right Defensive Midfield,RDM,False,left_to_right,right_to_left
7,-2.50,7.27,795507,False,10,2026-04-20,1.0,NaN,None,0.32,0.38,0.13,True,2026-04-20,2026-04-20 01:00:15,Auckland FC vs Newcastle United Jets FC,2024-11-30T04:00:00Z,Auckland FC,Newcastle United Jets FC,795507,L. Bayliss,37,1805,Newcastle United Jets FC,Midfield,3615,Attacking Midfield,AM,False,left_to_right,right_to_left
8,-0.78,-20.69,795505,True,10,2026-04-20,1.0,NaN,None,0.32,0.38,0.13,True,2026-04-20,2026-04-20 01:24:58,Auckland FC vs Newcastle United Jets FC,2024-11-30T04:00:00Z,Auckland FC,Newcastle United Jets FC,795505,E. Adams,7,1805,Newcastle United Jets FC,Wide Attacker,5098,Right Winger,RW,False,left_to_right,right_to_left
9,-1.85,18.80,735573,True,10,2026-04-20,1.0,NaN,None,0.32,0.38,0.13,True,2026-04-20,NaT,Auckland FC vs Newcastle United Jets FC,2024-11-30T04:00:00Z,Auckland FC,Newcastle United Jets FC,735573,T. Aquilina,39,1805,Newcastle United Jets FC,Wide Attacker,5400,Left Winger,LW,False,left_to_right,right_to_left
10,1.27,0.88,966120,True,10,2026-04-20,1.0,NaN,None,0.32,0.38,0.13,True,2026-04-20,2026-04-20 01:07:43,Auckland FC vs Newcastle United Jets FC,2024-11-30T04:00:00Z,Auckland FC,Newcastle United Jets FC,966120,B. Gibson,22,1805,Newcastle United Jets FC,Center Forward,4063,Center Forward,CF,False,left_to_right,right_to_left
11,40.47,0.24,285188,False,10,2026-04-20,1.0,NaN,None,0.32,0.38,0.13,True,2026-04-20,NaT,Auckland FC vs Newcastle United Jets FC,2024-11-30T04:00:00Z,Auckland FC,Newcastle United Jets FC,285188,A. Paulsen,12,4177,Auckland FC,Other,5400,Goalkeeper,GK,True,right_to_left,left_to_right
12,17.85,5.52,51667,True,10,2026-04-20,1.0,NaN,None,0.32,0.38,0.13,True,2026-04-20,NaT,Auckland FC vs Newcastle United Jets FC,2024-11-30T04:00:00Z,Auckland FC,Newcastle United Jets FC,51667,D. Hall,23,4177,Auckland FC,Central Defender,5400,Right Center Back,RCB,False,right_to_left,left_to_right
13,16.78,-3.67,33697,True,10,2026-04-20,1.0,NaN,None,0.32,0.38,0.13,True,2026-04-20,NaT,Auckland FC vs Newcastle United Jets FC,2024-11-30T04:00:00Z,Auckland FC,Newcastle United Jets FC,33697,N. Pijnaker,4,4177,Auckland FC,Central Defender,5400,Left Center Back,LCB,False,right_to_left,left_to_right
14,17.03,14.69,51713,True,10,2026-04-20,1.0,NaN,None,0.32,0.38,0.13,True,2026-04-20,NaT,Auckland FC vs Newcastle United Jets FC,2024-11-30T04:00:00Z,Auckland FC,Newcastle United Jets FC,51713,C. Elliott,17,4177,Auckland FC,Full Back,5400,Right Back,RB,False,right_to_left,left_to_right
15,17.55,-13.60,133498,True,10,2026-04-20,1.0,NaN,None,0.32,0.38,0.13,True,2026-04-20,NaT,Auckland FC vs Newcastle United Jets FC,2024-11-30T04:00:00Z,Auckland FC,Newcastle United Jets FC,133498,F. De Vries,15,4177,Auckland FC,Full Back,5400,Left Back,LB,False,right_to_left,left_to_right
16,11.70,6.73,14736,True,10,2026-04-20,1.0,NaN,None,0.32,0.38,0.13,True,2026-04-20,NaT,Auckland FC vs Newcastle United Jets FC,2024-11-30T04:00:00Z,Auckland FC,Newcastle United Jets FC,14736,L. Verstraete,6,4177,Auckland FC,Midfield,5400,Defensive Midfield,DM,False,right_to_left,left_to_right
17,10.16,-2.12,23418,True,10,2026-04-20,1.0,NaN,None,0.32,0.38,0.13,True,2026-04-20,NaT,Auckland FC vs Newcastle United Jets FC,2024-11-30T04:00:00Z,Auckland FC,Newcastle United Jets FC,23418,F. Gallegos,28,4177,Auckland FC,Midfield,5400,Attacking Midfield,AM,False,right_to_left,left_to_right
18,0.91,18.96,133501,False,10,2026-04-20,1.0,NaN,None,0.32,0.38,0.13,True,2026-04-20,2026-04-20 01:09:53,Auckland FC vs Newcastle United Jets FC,2024-11-30T04:00:00Z,Auckland FC,Newcastle United Jets FC,133501,L. Rogerson,27,4177,Auckland FC,Wide Attacker,4193,Right Winger,RW,False,right_to_left,left_to_right
19,7.74,-16.27,965685,True,10,2026-04-20,1.0,NaN,None,0.32,0.38,0.13,True,2026-04-20,NaT,Auckland FC vs Newcastle United Jets FC,2024-11-30T04:00:00Z,Auckland FC,Newcastle United Jets FC,965685,L. Gillion,14,4177,Auckland FC,Wide Attacker,5400,Left Winger,LW,False,right_to_left,left_to_right
20,0.40,-8.28,50951,True,10,2026-04-20,1.0,NaN,None,0.32,0.38,0.13,True,2026-04-20,2026-04-20 01:16:37,Auckland FC vs Newcastle United Jets FC,2024-11-30T04:00:00Z,Auckland FC,Newcastle United Jets FC,50951,J. Brimmer,22,4177,Auckland FC,Center Forward,4597,Center Forward,CF,False,right_to_left,left_to_right
21,2.67,9.94,38673,True,10,2026-04-20,1.0,NaN,None,0.32,0.38,0.13,True,2026-04-20,2026-04-20 01:25:21,Auckland FC vs Newcastle United Jets FC,2024-11-30T04:00:00Z,Auckland FC,Newcastle United Jets FC,38673,G. May,10,4177,Auckland FC,Center Forward,5121,Center Forward,CF,False,right_to_left,left_to_right

IRRELEVANT

In [ ]:
match_id = 1886347
tracking_data_github_url = f"https://media.githubusercontent.com/media/SkillCorner/opendata/741bdb798b0c1835057e3fa77244c1571a00e4aa/data/matches/{match_id}/{match_id}_tracking_extrapolated.jsonl"
raw_data = pd.read_json(tracking_data_github_url, lines=True)

In [ ]:
raw_data

,frame,timestamp,period,ball_data,possession,image_corners_projection,player_data
0,0,NaT,NaN,"{'x': None, 'y': None, 'z': None, 'is_detected...","{'player_id': None, 'group': None}","{'x_top_left': None, 'y_top_left': None, 'x_bo...",[]
1,1,NaT,NaN,"{'x': None, 'y': None, 'z': None, 'is_detected...","{'player_id': None, 'group': None}","{'x_top_left': None, 'y_top_left': None, 'x_bo...",[]
2,2,NaT,NaN,"{'x': None, 'y': None, 'z': None, 'is_detected...","{'player_id': None, 'group': None}","{'x_top_left': None, 'y_top_left': None, 'x_bo...",[]
3,3,NaT,NaN,"{'x': None, 'y': None, 'z': None, 'is_detected...","{'player_id': None, 'group': None}","{'x_top_left': None, 'y_top_left': None, 'x_bo...",[]
4,4,NaT,NaN,"{'x': None, 'y': None, 'z': None, 'is_detected...","{'player_id': None, 'group': None}","{'x_top_left': None, 'y_top_left': None, 'x_bo...",[]
...,...,...,...,...,...,...,...
59056,59056,2026-04-19 01:37:05.600,2.0,"{'x': None, 'y': None, 'z': None, 'is_detected...","{'player_id': None, 'group': None}","{'x_top_left': None, 'y_top_left': None, 'x_bo...",[]
59057,59057,2026-04-19 01:37:05.700,2.0,"{'x': None, 'y': None, 'z': None, 'is_detected...","{'player_id': None, 'group': None}","{'x_top_left': None, 'y_top_left': None, 'x_bo...",[]
59058,59058,2026-04-19 01:37:05.800,2.0,"{'x': None, 'y': None, 'z': None, 'is_detected...","{'player_id': None, 'group': None}","{'x_top_left': None, 'y_top_left': None, 'x_bo...",[]
59059,59059,2026-04-19 01:37:05.900,2.0,"{'x': None, 'y': None, 'z': None, 'is_detected...","{'player_id': None, 'group': None}","{'x_top_left': None, 'y_top_left': None, 'x_bo...",[]
59060,59060,2026-04-19 01:37:06.000,2.0,"{'x': None, 'y': None, 'z': None, 'is_detected...","{'player_id': None, 'group': None}","{'x_top_left': None, 'y_top_left': None, 'x_bo...",[]

In [ ]:
raw_df = pd.json_normalize(
            raw_data.to_dict("records"),
            "player_data",
            ["frame", "timestamp", "period", "possession", "ball_data"],
        )

In [ ]:
raw_df.dtypes

x                     float64
y                     float64
player_id               int64
is_detected              bool
frame                  object
timestamp      datetime64[ns]
period                 object
possession             object
ball_data              object
dtype: object

In [ ]:
# Extract 'player_id' and 'group from the 'possession' dictionary
raw_df["possession_player_id"] = raw_df["possession"].apply(
            lambda x: x.get("player_id")
        )
raw_df["possession_group"] = raw_df["possession"].apply(
            lambda x: x.get("group")
        )

        # (Optional) Expand the ball_data with json_normalize
raw_df[["ball_x", "ball_y", "ball_z", "is_detected_ball"]] = pd.json_normalize(
            raw_df.ball_data
        )

        # (Optional) Drop the original 'possession' column if you no longer need it
raw_df = raw_df.drop(columns=["possession", "ball_data"])

        # Add the match_id identifier to your dataframe
raw_df["match_id"] = match_id
tracking_df = raw_df.copy()

In [ ]:
tracking_df.dtypes

x                              float64
y                              float64
player_id                        int64
is_detected                       bool
frame                           object
timestamp               datetime64[ns]
period                          object
possession_player_id           float64
possession_group                object
ball_x                         float64
ball_y                         float64
ball_z                         float64
is_detected_ball                  bool
match_id                         int64
dtype: object

In [ ]:
meta_data_github_url = f"https://raw.githubusercontent.com/SkillCorner/opendata/741bdb798b0c1835057e3fa77244c1571a00e4aa/data/matches/{match_id}/{match_id}_match.json"
response = requests.get(meta_data_github_url)
raw_match_data = response.json()

In [ ]:
        # The output has nested json elements. We process them
raw_match_df = pd.json_normalize(raw_match_data, max_level=2)
raw_match_df["home_team_side"] = raw_match_df["home_team_side"].astype(str)

In [ ]:
players_df = pd.json_normalize(
            raw_match_df.to_dict("records"),
            record_path="players",
            meta=[
                "home_team_score",
                "away_team_score",
                "date_time",
                "home_team_side",
                "home_team.name",
                "home_team.id",
                "away_team.name",
                "away_team.id",
            ],  # data we keep
        )

        # Take only players who played and create their total time
players_df = players_df[
            ~((players_df.start_time.isna()) & (players_df.end_time.isna()))
        ]
players_df["total_time"] = None

        # Create a flag for GK
players_df["is_gk"] = players_df["player_role.acronym"] == "GK"

        # Add a flag if the given player is home or away
players_df["match_name"] = (
            players_df["home_team.name"] + " vs " + players_df["away_team.name"]
        )

        # Add a flag if the given player is home or away
players_df["home_away_player"] = np.where(
            players_df.team_id == players_df["home_team.id"], "Home", "Away"
        )

        # Create flag from player
players_df["team_name"] = np.where(
            players_df.team_id == players_df["home_team.id"],
            players_df["home_team.name"],
            players_df["away_team.name"],
        )

        # Figure out sides
players_df[["home_team_side_1st_half", "home_team_side_2nd_half"]] = (
            players_df["home_team_side"]
            .astype(str)
            .str.strip("[]")
            .str.replace("'", "")
            .str.split(", ", expand=True)
        )
        # Clean up sides
players_df["direction_player_1st_half"] = np.where(
            players_df.home_away_player == "Home",
            players_df.home_team_side_1st_half,
            players_df.home_team_side_2nd_half,
        )
players_df["direction_player_2nd_half"] = np.where(
            players_df.home_away_player == "Home",
            players_df.home_team_side_2nd_half,
            players_df.home_team_side_1st_half,
        )

In [ ]:
players_df['start_time'] = pd.to_datetime(players_df['start_time'])
players_df['end_time'] = pd.to_datetime(players_df['end_time'])

/var/folders/5y/nm55z3vs3q72_gcmp1j45hmr0000gn/T/ipykernel_79228/3820804381.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  players_df['start_time'] = pd.to_datetime(players_df['start_time'])
/var/folders/5y/nm55z3vs3q72_gcmp1j45hmr0000gn/T/ipykernel_79228/3820804381.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  players_df['end_time'] = pd.to_datetime(players_df['end_time'])

In [ ]:
players_df.dtypes

start_time                                        datetime64[ns]
end_time                                          datetime64[ns]
number                                                     int64
yellow_card                                                int64
red_card                                                   int64
injured                                                     bool
goal                                                       int64
own_goal                                                   int64
team_player_id                                             int64
team_id                                                    int64
id                                                         int64
first_name                                                object
last_name                                                 object
short_name                                                object
birthday                                                  object
trackable_object                                           int64
gender                                                    object
player_role.id                                             int64
player_role.position_group                                object
player_role.name                                          object
player_role.acronym                                       object
playing_time.total.minutes_tip                           float64
playing_time.total.minutes_otip                          float64
playing_time.total.start_frame                           float64
playing_time.total.end_frame                             float64
playing_time.total.minutes_played                        float64
playing_time.total.minutes_played_regular_time           float64
playing_time.by_period                                    object
playing_time.total                                       float64
home_team_score                                           object
away_team_score                                           object
date_time                                                 object
home_team_side                                            object
home_team.name                                            object
home_team.id                                              object
away_team.name                                            object
away_team.id                                              object
total_time                                                object
is_gk                                                       bool
match_name                                                object
home_away_player                                          object
team_name                                                 object
home_team_side_1st_half                                   object
home_team_side_2nd_half                                   object
direction_player_1st_half                                 object
direction_player_2nd_half                                 object
dtype: object