In [1]:
# imports
import pandas as pd
import requests
import numpy as np
import json

from data_ingestor_github import SkillCornerDataIngestor
di = SkillCornerDataIngestor()

In [2]:
# # To load all the data
# data = di.load_data(match_id=1886347)

In [3]:
# # To view the loaded data
# with open (f"../../data/gold_tracking_data.json", "r") as f:
#     gold_tracking_data = json.load(f)

# frames = gold_tracking_data['frames']

In [4]:
# start=1000
# end=1050
# filtered_frames = {frame_num: frames[str(frame_num)] for frame_num in range(start, end + 1) if str(frame_num) in frames}
# filtered_frames

In [5]:
# To view tracking data at different stages of the pipeline
bronze_tracking_data = di._get_bronze_tracking_data(match_id=1899585)
silver_tracking_data = di._get_silver_tracking_data(bronze_tracking_data)
bronze_meta_data = di._get_bronze_meta_data(match_id=1899585)
silver_meta_data = di._get_silver_meta_data(bronze_meta_data)
bronze_event_data = di._get_bronze_event_data(match_id=1899585)
silver_event_data = di._get_silver_event_data(bronze_event_data)
# gold_data = di._get_gold_tracking_data(silver_tracking_data, silver_meta_data, silver_event_data)

/Users/mihirthalanki/Documents/MT/Hackathon/PlayTactix/backend/services/data_ingestor_github.py:221: DtypeWarning: Columns (276) have mixed types. Specify dtype option on import or set low_memory=False.
  raw_data = pd.read_csv(event_data_github_url)

In [17]:
bronze_tracking_data[bronze_tracking_data['frame'] == 100]

,frame,timestamp,period,ball_data,possession,image_corners_projection,player_data
100,100,2026-05-14 00:00:09,1.0,"{'x': -7.36, 'y': 15.36, 'z': 0.13, 'is_detect...","{'player_id': None, 'group': 'away team'}","{'x_top_left': -37.05, 'y_top_left': 39.0, 'x_...","[{'x': -40.96, 'y': 2.85, 'player_id': 34718, ..."

In [ ]:
bronze_tracking_data[bronze_tracking_data["player_data"].apply(len) == 0]

TypeError: Index(...) must be called with a collection of some kind, False was passed

In [20]:
bronze_tracking_data[bronze_tracking_data['frame'] == 44558]

,frame,timestamp,period,ball_data,possession,image_corners_projection,player_data
44558,44558,2026-05-14 01:09:38.800,2.0,"{'x': None, 'y': None, 'z': None, 'is_detected...","{'player_id': None, 'group': None}","{'x_top_left': None, 'y_top_left': None, 'x_bo...",[]

In [15]:
silver_tracking_data[silver_tracking_data['frame'] == 44558]

Empty DataFrame
Columns: [x, y, player_id, is_detected, frame, timestamp, period, possession_player_id, possession_group, ball_x, ball_y, ball_z, is_detected_ball]
Index: []

In [12]:
import pandas as pd
pd.set_option('display.max_columns', None)  # Show all columns
bronze_event_data[bronze_event_data['first_line_break'] == True].head()

,event_id,index,match_id,frame_start,frame_end,frame_physical_start,time_start,time_end,minute_start,second_start,duration,period,attacking_side_id,attacking_side,event_type_id,event_type,event_subtype_id,event_subtype,player_id,player_name,player_position_id,player_position,player_in_possession_id,player_in_possession_name,player_in_possession_position_id,player_in_possession_position,team_id,team_shortname,x_start,y_start,channel_id_start,channel_start,third_id_start,third_start,penalty_area_start,x_end,y_end,channel_id_end,channel_end,third_id_end,third_end,penalty_area_end,associated_player_possession_event_id,associated_player_possession_frame_start,associated_player_possession_frame_end,associated_player_possession_end_type_id,associated_player_possession_end_type,associated_off_ball_run_event_id,associated_off_ball_run_subtype_id,associated_off_ball_run_subtype,game_state_id,game_state,team_score,opponent_team_score,phase_index,player_possession_phase_index,first_player_possession_in_team_possession,last_player_possession_in_team_possession,lead_to_different_phase,issued_from_different_phase,n_player_possessions_in_phase,team_possession_loss_in_phase,team_in_possession_phase_type_id,team_in_possession_phase_type,team_out_of_possession_phase_type_id,team_out_of_possession_phase_type,current_team_in_possession_next_phase_type_id,current_team_in_possession_next_phase_type,current_team_out_of_possession_next_phase_type_id,current_team_out_of_possession_next_phase_type,current_team_in_possession_previous_phase_type_id,current_team_in_possession_previous_phase_type,current_team_out_of_possession_previous_phase_type_id,current_team_out_of_possession_previous_phase_type,game_interruption_before_id,game_interruption_before,game_interruption_after_id,game_interruption_after,lead_to_shot,lead_to_goal,distance_covered,trajectory_angle,trajectory_direction_id,trajectory_direction,in_to_out,out_to_in,speed_avg,speed_avg_band_id,speed_avg_band,separation_start,separation_end,separation_gain,last_defensive_line_x_start,last_defensive_line_x_end,delta_to_last_defensive_line_start,delta_to_last_defensive_line_end,delta_to_last_defensive_line_gain,last_defensive_line_height_start,last_defensive_line_height_end,last_defensive_line_height_gain,inside_defensive_shape_start,inside_defensive_shape_end,start_type_id,start_type,end_type_id,end_type,consecutive_on_ball_engagements,one_touch,quick_pass,carry,forward_momentum,is_header,hand_pass,initiate_give_and_go,pass_angle_received,pass_direction_received_id,pass_direction_received,pass_distance_received,pass_range_received_id,pass_range_received,pass_outcome_id,pass_outcome,targeted_passing_option_event_id,high_pass,player_targeted_id,player_targeted_name,player_targeted_position_id,player_targeted_position,player_targeted_x_pass,player_targeted_y_pass,player_targeted_channel_pass_id,player_targeted_channel_pass,player_targeted_third_pass_id,player_targeted_third_pass,player_targeted_penalty_area_pass,player_targeted_x_reception,player_targeted_y_reception,player_targeted_channel_reception_id,player_targeted_channel_reception,player_targeted_third_reception_id,player_targeted_third_reception,player_targeted_penalty_area_reception,player_targeted_distance_to_goal_start,player_targeted_distance_to_goal_end,player_targeted_angle_to_goal_start,player_targeted_angle_to_goal_end,player_targeted_average_speed,player_targeted_speed_avg_band_id,player_targeted_speed_avg_band,speed_difference,player_targeted_xpass_completion,player_targeted_difficult_pass_target,player_targeted_xthreat,player_targeted_dangerous,n_passing_options,n_off_ball_runs,n_passing_options_line_break,n_passing_options_first_line_break,n_passing_options_second_last_line_break,n_passing_options_last_line_break,n_passing_options_ahead,n_passing_options_dangerous_difficult,n_passing_options_dangerous_not_difficult,n_passing_options_not_dangerous_not_difficult,n_passing_options_not_dangerous_difficult,n_passing_options_at_start,n_passing_options_at_end,n_passing_options_ahead_at_start,n_passing_options_ahead_at_end,n_teammates_ahead_end,n_teammates_ahead_start,n_player_targeted_opponents_ahead_start,n_player_targeted_opponents_ahead_end,n_player_targeted_teammates_ahead_start,n_player_targeted_teammates_ahead_end,n_player_targeted_teammates_within_5m_start,n_player_targeted_teammates_within_5m_end,n_player_targeted_opponents_within_5m_start,n_player_targeted_opponents_within_5m_end,organised_defense,defensive_structure,n_defensive_lines,first_line_break,first_line_break_type_id,first_line_break_type,second_last_line_break,second_last_line_break_type_id,second_last_line_break_type,last_line_break,last_line_break_type_id,last_line_break_type,furthest_line_break_id,furthest_line_break,furthest_line_break_type_id,furthest_line_break_type,interplayer_distance,interplayer_distance_range_id,interplayer_distance_range,interplayer_distance_start,interplayer_distance_end,interplayer_distance_min,interplayer_distance_start_physical,close_at_player_possession_start,interplayer_angle,interplayer_direction_id,interplayer_direction,angle_of_engagement,goal_side_start,goal_side_end,pass_distance,pass_range_id,pass_range,pass_angle,pass_direction_id,pass_direction,pass_ahead,n_opponents_ahead_player_in_possession_pass_moment,n_opponents_ahead_pass_reception,n_opponents_bypassed,location_to_player_in_possession_id_start,location_to_player_in_possession_start,location_to_player_in_possession_id_end,location_to_player_in_possession_end,distance_to_player_in_possession_start,distance_to_player_in_possession_end,player_in_possession_x_start,player_in_possession_y_start,player_in_possession_channel_id_start,player_in_possession_channel_start,player_in_possession_third_id_start,player_in_possession_third_start,player_in_possession_penalty_area_start,player_in_possession_x_end,player_in_possession_y_end,player_in_possession_channel_id_end,player_in_possession_channel_end,player_in_possession_third_id_end,player_in_possession_third_end,player_in_possession_penalty_area_end,targeted,received,received_in_space,dangerous,difficult_pass_target,xthreat,xpass_completion,passing_option_score,predicted_passing_option,peak_passing_option_frame,passing_option_at_player_possession_start,n_simultaneous_runs,give_and_go,intended_run_behind,push_defensive_line,break_defensive_line,passing_option_at_start,n_simultaneous_passing_options,passing_option_at_pass_moment,n_opponents_ahead_end,n_opponents_ahead_start,n_opponents_overtaken,pressing_chain,pressing_chain_length,pressing_chain_end_type_id,pressing_chain_end_type,pressing_chain_index,index_in_pressing_chain,simultaneous_defensive_engagement_same_target,simultaneous_defensive_engagement_same_target_rank,affected_line_breaking_passing_option_id,affected_line_break_id,affected_line_break,affected_line_breaking_passing_option_attempted,affected_line_breaking_passing_option_xthreat,affected_line_breaking_passing_option_dangerous,affected_line_breaking_passing_option_run_subtype_id,affected_line_breaking_passing_option_run_subtype,possession_danger,beaten_by_possession,beaten_by_movement,stop_possession_danger,reduce_possession_danger,force_backward,xloss_player_possession_start,xloss_player_possession_end,xloss_player_possession_max,xshot_player_possession_start,xshot_player_possession_end,xshot_player_possession_max,is_player_possession_start_matched,is_player_possession_end_matched,is_previous_pass_matched,is_pass_reception_matched,fully_extrapolated
153,7_73,153,1899585,1615,1616,NaN,02:40.5,02:40.6,2,40,0.1,1,2,right_to_left,7,passing_option,NaN,NaN,23418,F. Gallegos,12,LM,51667.0,D. Hall,6.0,RCB,4177,Auckland FC,14.49,26.41,1,wide_left,2,middle_third,False,14.12,26.32,1,wide_left,2,middle_third,False,8_33,1615.0,NaN,NaN,NaN,NaN,NaN,NaN,3,drawing,0,0,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,create,9,medium_block,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,1.57,-167.54,2.0,backward,False,False,14.02,1.0,jogging,7.46,7.66,0.20,34.08,33.72,19.59,19.60,0.01,17.92,18.28,0.36,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,424.0,3.0,True,1.0,through,False,NaN,NaN,False,NaN,NaN,1.0,first,1.0,through,14.81,1.0,short,NaN,NaN,NaN,NaN,NaN,32.01,1.0,forward,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,10.0,7.0,3.0,3.0,ahead,3.0,ahead,18.74,18.53,-2.80,19.17,2.0,half_space_left,2.0,middle_third,False,-2.90,19.00,2.0,half_space_left,2.0,middle_third,False,False,False,NaN,False,False,0.0018,0.9554,0.7655,True,1647.0,True,NaN,NaN,NaN,NaN,NaN,NaN,2.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,False
156,7_76,156,1899585,1642,1653,NaN,02:43.2,02:44.3,2,43,1.1,1,2,right_to_left,7,passing_option,NaN,NaN,23418,F. Gallegos,12,LM,51667.0,D. Hall,6.0,RCB,4177,Auckland FC,7.34,21.99,1,wide_left,2,middle_third,False,6.71,19.79,2,half_space_left,2,middle_third,False,8_33,1615.0,NaN,NaN,NaN,NaN,NaN,NaN,3,drawing,0,0,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,create,9,medium_block,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,2.11,-105.98,4.0,sideway_right,False,True,7.58,1.0,jogging,4.28,2.93,-1.36,26.94,25.75,19.60,19.04,-0.56,25.06,26.25,1.19,False,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,424.0,3.0,True,1.0,through,False,NaN,NaN,False,NaN,NaN,1.0,first,1.0,through,14.81,1.0,short,NaN,NaN,NaN,NaN,NaN,32.01,1.0,forward,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,10.0,7.0,3.0,3.0,ahead,3.0,ahead,15.63,14.01,-5.67,13.32,2.0,half_space_left,2.0,middle_third,False,-5.55,13.02,2.0,half_space_left,2.0,middle_third,False,False,False,NaN,False,False,0.0018,0.9554,0.7655,True,1647.0,False,NaN,NaN,NaN,NaN,NaN,NaN,3.0,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,False
158,8_34,158,1899585,1672,1684,NaN,02:46.2,02:47.4,2,46,1.2,1,2,right_to_left,8,player_possession,NaN,NaN,133498,F. De Vries,2,LB,NaN,NaN,NaN,NaN,4177,Auckland FC,5.70,32.56,1,wide_left,2,middle_third,False,8.17,32.58,1,wide_left,2,middle_third,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,drawing,0,0,18,1.0,False,False,False,True,2.0,False,2,finish,8,low_block,5.0,chaotic,5.0,chaotic,1.0,create,9.0,medium_block,NaN,NaN,NaN,NaN,False,False,2.47,0.46,1.0,forward,False,False,7.22,1.0,jogging,8.40,5.05,-3.35,26.46,27.59,20.76,19.42,-1.34,25.54,24.41,-1.13,False,False,1.0,pass_reception,1.0,pass,NaN,False,False,True,False,False,False,False,62.47,3.0,sideway_left,26.98,2.0,medium,1.0,successful,7_80,False,50951.0,J. Brimmer,19.0,CF,15.72,29.53,1.0,wide_left,2.0,middle_third,False,15.0,29.98,1.0,wide_left,2.0,middle_third,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.9567,False,0.0015,False,4.0,0.0,3.0,2.0,1.0,0.0,2.0,0.0,0.0,4.0,0.0,4.0,3.0,2.0,2.0,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,424.0,3.0,True,NaN,NaN,False,NaN,NaN,False,NaN,NaN,1.0,first,2.0,around,8.14,1.0,short,NaN,NaN,NaN,NaN,NaN,-22.00,1.0,forward,NaN,NaN,NaN,7.92,1.0,short,-24.69,1.0,forward,True,7.0,6.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,8.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,True,True,False
160,7_79,160,1899585,1672,1684,NaN,02:46.2,02:47.4,2,46,1.2,1,2,right_to_left,7,passing_option,NaN,NaN,23418,F. Gallegos,12,LM,133498.0,F. De Vries,2.0,LB,4177,Auckland FC,8.17,19.50,2,half_space_left,2,middle_third,False,10.09,22.13,1,wide_left,2,middle_third,False,8_34,1672.0,NaN,NaN,NaN,NaN,NaN,NaN,3,drawing,0,0,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,finish,8,low_block,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,3.27,53.87,3.0,sideway_left,True,False,9.76,1.0,jogging,4.91,6.08,1.17,26.46,27.59,18.29,17.50,-0.79,25.54,24.41,-1.13,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,424.0,3.0,True,1.0,through,False,NaN,NaN,False,NaN,NaN,1.0,first,1.0,through,10.62,1.0,short,NaN,NaN,NaN,NaN,NaN,-79.59,4.0,sideway_right,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,7.0,7.0,0.0,2.0,same_line,2.0,same_line,13.29,10.62,5.70,32.56,1.0,wide_left,2.0,middle_third,False,8.17,32.58,1.0,wide_left,2.0,middle_third,False,False,False,NaN,False,False,0.0028,0.9221,0.8711,True,1684.0,True,NaN,NaN,NaN,NaN,NaN,NaN,3.0,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,False
161,7_80,161,1899585,1672,1684,NaN,02:46.2,02:47.4,2,46,1.2,1,2,right_to_left,7,passing_option,NaN,NaN,50951,J. Brimmer,19,CF,133498.0,F. De Vries,2.0,LB,4177,Auckland FC,17.58,27.83,1,wide_left,3,attacking_third,False,15.72,29.53,1,wide_left,2,middle_third,False,8_34,1672.0,NaN,NaN,NaN,NaN,NaN,NaN,3,drawing,0,0,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,finish,8,low_block,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,2.53,137.57,2.0,backward,False,False,NaN,NaN,NaN,4.49,1.46,-3.03,26.46,27.59,8.88,11.87,2.99,25.54,24.41,-1.13,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,424.0,3.0,True,2.0,around,False,NaN,NaN,False,NaN,NaN,1.0,first,2.0,around,8.14,1.0,short,NaN,NaN,NaN,NaN,NaN,-22.00,1.0,forward,NaN,NaN,NaN,7.92,1.0,short,-24.69,1.0,forward,True,7.0,6.0,1.0,3.0,ahead,3.0,ahead,12.79,8.14,5.70,32.56,1.0,wide_left,2.0,middle_third,False,8.17,32.58,1.0,wide_left,2.0,middle_third,False,True,True,False,False,False,0.0015,0.9567,0.9751,True,1684.0,True,NaN,NaN,NaN,NaN,NaN,NaN,3.0,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,True,False

In [10]:
silver_event_data[silver_event_data['event_type'] == 'off_ball_run'].head()

,event_id,index,frame_start,frame_end,attacking_side,event_type_id,event_type,player_id,player_name,team_id,x_start,y_start,x_end,y_end
8,1_0,8,57,66,left_to_right,1,off_ball_run,51015,A. Rufer,867,-9.98,0.48,-10.80,4.37
18,1_1,18,88,105,left_to_right,1,off_ball_run,26969,H. Ishige,867,13.18,19.94,20.60,23.58
21,1_2,21,117,125,left_to_right,1,off_ball_run,26969,H. Ishige,867,21.70,27.53,19.77,30.39
24,1_3,24,126,163,left_to_right,1,off_ball_run,27003,K. Nagasawa,867,6.12,15.14,23.88,28.47
38,1_4,38,195,227,left_to_right,1,off_ball_run,42510,S. Wootton,867,-17.83,7.35,-35.41,0.91

In [ ]:
event_idx = 0
n_events = len(silver_event_data)
events = 
while event_idx < n_events and silver_event_data.iloc[event_idx]['frame_start'] <= frame_number:
    event = silver_event_data.iloc[event_idx]
    if event['frame_start'] <= frame_number <= event['frame_end']:
        frames[frame_number]['events'].append(event.to_dict())
                if event['frame_end'] < frame_number:
                    event_idx += 1
                else:
                    break

adding event player_possession for frame 12
adding event player_possession for frame 31
adding event passing_option for frame 31
adding event passing_option for frame 31
adding event on_ball_engagement for frame 37

In [21]:
event_set = set()
for event in events:
    event_set.add(event['event_type'])
print(event_set)

{'on_ball_engagement', 'passing_option', 'player_possession'}

In [7]:
silver_data = silver_tracking_data.merge(
            silver_meta_data, left_on=["player_id"], right_on=["id"]
        )

In [8]:
pd.set_option('display.max_columns', None)  # Show all columns

In [9]:
def build_frame_dict(tracking_data, event_data):
    frames = {}
    event_idx = 0
    n_events = len(event_data)
    for frame_number, group in tracking_data.groupby("frame"):
        # Add tracking data
        frames[frame_number] = {
                #'is_detected': group['is_detected'].iloc[0],
                #'timestamp': group['timestamp'].iloc[0],
                'period': group['period'].iloc[0],
                'players': {
                    'x': group['x'].tolist(),
                    'y': group['y'].tolist(),
                    'player_id': group['player_id'].tolist(),
                    'id': group['id'].tolist(),
                    'short_name': group['short_name'].tolist(),
                    'number': group['number'].tolist(),
                    'team_id': group['team_id'].tolist(),
                    'total_time': group['total_time'].tolist(),
                    'player_role.name': group['player_role.name'].tolist(),
                    'player_role.acronym': group['player_role.acronym'].tolist(),
                    'is_gk': group['is_gk'].tolist(),
                    'direction_player_1st_half': group['direction_player_1st_half'].tolist(),
                    'direction_player_2nd_half': group['direction_player_2nd_half'].tolist(),
                },
                'ball': {
                    'ball_x': group['ball_x'].iloc[0],
                    'ball_y': group['ball_y'].iloc[0],
                    'ball_z': group['ball_z'].iloc[0],
                    #'is_detected_ball': group['is_detected_ball'].iloc[0],
                },
                'events': []
            }
        # Add event data
        while event_idx < n_events and event_data.iloc[event_idx]['frame_start'] <= frame_number:
            event = event_data.iloc[event_idx]
            if event['frame_start'] <= frame_number <= event['frame_end']:
                frames[frame_number]['events'].append(event.to_dict())
            if event['frame_end'] < frame_number:
                event_idx += 1
            else:
                break
    
    return frames

In [10]:
gold_frames = build_frame_dict(silver_data, silver_event_data)

KeyboardInterrupt:

In [ ]:
gold_frames[58]['events']

[{'event_id': '8_1',
  'index': 1,
  'frame_start': 48,
  'frame_end': 58,
  'attacking_side': 'left_to_right',
  'event_type_id': 8,
  'event_type': 'player_possession',
  'event_subtype_id': nan,
  'event_subtype': nan,
  'player_id': 51649,
  'player_name': 'A. Šušnjar',
  'team_id': 1805,
  'x_start': -22.31,
  'y_start': 1.22,
  'x_end': -22.21,
  'y_end': 2.7}]

In [ ]:
silver_event_data.head()

,event_id,index,frame_start,frame_end,attacking_side,event_type_id,event_type,event_subtype_id,event_subtype,player_id,player_name,team_id,x_start,y_start,x_end,y_end
0,8_0,0,28,28,left_to_right,8,player_possession,NaN,NaN,966120,B. Gibson,1805,0.73,0.49,0.73,0.49
1,8_1,1,48,58,left_to_right,8,player_possession,NaN,NaN,51649,A. Šušnjar,1805,-22.31,1.22,-22.21,2.70
2,7_0,2,48,53,left_to_right,7,passing_option,NaN,NaN,735574,K. Grozos,1805,-10.47,-2.78,-11.36,-1.38
3,7_1,3,48,58,left_to_right,7,passing_option,NaN,NaN,735578,M. Natta,1805,-20.69,16.66,-20.36,17.69
4,9_0,4,56,58,right_to_left,9,on_ball_engagement,11.0,pressing,50951,J. Brimmer,4177,13.03,0.06,13.98,-0.68