In [9]:
# imports
import pandas as pd
import requests
import numpy as np
import json

from data_ingestor_github import DataIngestor
di = DataIngestor()

In [10]:
match_id = 1886347
event_data = di.skillcorner_ingestor._get_bronze_event_data(match_id)
silver_event_data = di.skillcorner_ingestor._get_silver_event_data(event_data)

2026-07-07 15:00:44 | INFO     | playtactix.data_ingestor_github | Fetching event data from GitHub match_id=1886347
2026-07-07 15:00:46 | INFO     | playtactix.data_ingestor_github | Event data fetched successfully match_id=1886347 rows=5079
2026-07-07 15:00:46 | INFO     | playtactix.data_ingestor_github | Silver event data transformed rows=5079

In [11]:
pd.set_option('display.max_columns', None)
silver_event_data['xthreat'].describe()

count    3143.000000
mean        0.010888
std         0.028126
min         0.000000
25%         0.000600
50%         0.002500
75%         0.008500
max         0.415500
Name: xthreat, dtype: float64

In [12]:
pd.set_option('display.max_columns', None)
silver_event_data[silver_event_data['xshot_player_possession_start'].notnull()][['xshot_player_possession_start', 'xshot_player_possession_end', 'xshot_player_possession_max']].describe()

,xshot_player_possession_start,xshot_player_possession_end,xshot_player_possession_max
count,936.000000,936.000000,936.000000
mean,0.026270,0.032569,0.045833
std,0.112666,0.136124,0.149487
min,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000
50%,0.001000,0.000000,0.002000
75%,0.005000,0.003000,0.008000
max,0.946000,0.946000,0.946000

In [13]:
# print the number of distinc phase index
print("Number of distinct phase index: ", silver_event_data['phase_index'].nunique())
print(silver_event_data['phase_index'].min(), silver_event_data['phase_index'].max())

Number of distinct phase index:  400
0 453

In [14]:
count = 0
for i in range(0,silver_event_data['phase_index'].max()):
    if i not in silver_event_data['phase_index'].unique():
        count += 1
        # print("Missing phase index: ", i)

print("Number of missing phase index: ", count)

Number of missing phase index:  54

In [17]:
from key_moments_service import KeyMomentsService
kms = KeyMomentsService()
kms._get_all_events(silver_event_data)

[{'event_id': '8_0',
  'index': 0,
  'phase_index': 0,
  'frame_start': 28,
  'frame_end': 28,
  'time_end': '00:01.8',
  'team_id': 1805,
  'attacking_side': 'left_to_right',
  'team_in_possession_phase_type': 'create',
  'team_out_of_possession_phase_type': 'medium_block',
  'event_type_id': 8,
  'event_type': 'player_possession',
  'event_subtype_id': nan,
  'event_subtype': nan,
  'end_type': 'pass',
  'player_id': 966120,
  'player_name': 'B. Gibson',
  'player_position': 'CF',
  'player_in_possession_id': nan,
  'x_start': 0.73,
  'y_start': 0.49,
  'x_end': 0.73,
  'y_end': 0.49,
  'lead_to_shot': False,
  'lead_to_goal': False,
  'distance_covered': 0.0,
  'speed_avg': 2.24,
  'separation_gain': 0.0,
  'pass_distance_received': nan,
  'player_targeted_xpass_completion': nan,
  'player_targeted_xthreat': nan,
  'xthreat': nan,
  'xpass_completion': nan,
  'n_opponents_overtaken': 0.0,
  'xloss_player_possession_start': nan,
  'xloss_player_possession_end': nan,
  'xloss_player_possession_max': nan,
  'xshot_player_possession_start': nan,
  'xshot_player_possession_end': nan,
  'xshot_player_possession_max': nan},
 {'event_id': '8_1',
  'index': 1,
  'phase_index': 0,
  'frame_start': 48,
  'frame_end': 58,
  'time_end': '00:04.8',
  'team_id': 1805,
  'attacking_side': 'left_to_right',
  'team_in_possession_phase_type': 'create',
  'team_out_of_possession_phase_type': 'medium_block',
  'event_type_id': 8,
  'event_type': 'player_possession',
  'event_subtype_id': nan,
  'event_subtype': nan,
  'end_type': 'pass',
  'player_id': 51649,
  'player_name': 'A. Šušnjar',
  'player_position': 'LCB',
  'player_in_possession_id': nan,
  'x_start': -22.31,
  'y_start': 1.22,
  'x_end': -22.21,
  'y_end': 2.7,
  'lead_to_shot': False,
  'lead_to_goal': False,
  'distance_covered': 1.49,
  'speed_avg': 5.34,
  'separation_gain': -5.74,
  'pass_distance_received': 26.02,
  'player_targeted_xpass_completion': 0.9865,
  'player_targeted_xthreat': 0.0001,
  'xthreat': nan,
  'xpass_completion': nan,
  'n_opponents_overtaken': 0.0,
  'xloss_player_possession_start': nan,
  'xloss_player_possession_end': nan,
  'xloss_player_possession_max': nan,
  'xshot_player_possession_start': nan,
  'xshot_player_possession_end': nan,
  'xshot_player_possession_max': nan},
 {'event_id': '7_0',
  'index': 2,
  'phase_index': 0,
  'frame_start': 48,
  'frame_end': 53,
  'time_end': '00:04.3',
  'team_id': 1805,
  'attacking_side': 'left_to_right',
  'team_in_possession_phase_type': 'create',
  'team_out_of_possession_phase_type': 'medium_block',
  'event_type_id': 7,
  'event_type': 'passing_option',
  'event_subtype_id': nan,
  'event_subtype': nan,
  'end_type': nan,
  'player_id': 735574,
  'player_name': 'K. Grozos',
  'player_position': 'RDM',
  'player_in_possession_id': 51649.0,
  'x_start': -10.47,
  'y_start': -2.78,
  'x_end': -11.36,
  'y_end': -1.38,
  'lead_to_shot': False,
  'lead_to_goal': False,
  'distance_covered': 1.31,
  'speed_avg': 11.89,
  'separation_gain': -1.52,
  'pass_distance_received': nan,
  'player_targeted_xpass_completion': nan,
  'player_targeted_xthreat': nan,
  'xthreat': 0.0006,
  'xpass_completion': 0.9629,
  'n_opponents_overtaken': nan,
  'xloss_player_possession_start': nan,
  'xloss_player_possession_end': nan,
  'xloss_player_possession_max': nan,
  'xshot_player_possession_start': nan,
  'xshot_player_possession_end': nan,
  'xshot_player_possession_max': nan},
 {'event_id': '7_1',
  'index': 3,
  'phase_index': 0,
  'frame_start': 48,
  'frame_end': 58,
  'time_end': '00:04.8',
  'team_id': 1805,
  'attacking_side': 'left_to_right',
  'team_in_possession_phase_type': 'create',
  'team_out_of_possession_phase_type': 'medium_block',
  'event_type_id': 7,
  'event_type': 'passing_option',
  'event_subtype_id': nan,
  'event_subtype': nan,
  'end_type': nan,
  'player_id': 735578,
  'player_name': 'M. Natta',
  'player_position': 'LB',
  'player_in_possession_id': 51649.0,
  'x_start': -20.69,
  'y_start': 16.66,
  'x_end': -20.36,
  'y_end': 17.69,
  'lead_to_shot': False,
  'lead_to_goal': False,
  'distance_covered': 1.09,
  'speed_avg': 3.96,
  'separation_gain': -9.44,
  'pass_distance_received': nan,
  'player_targeted_xpass_completion': nan,
  'player_targeted_xthreat': nan,
  'xthreat': 0.0001,
  'xpass_completion': 0.9865,
  'n_opponents_overtaken': nan,
  'xloss_player_possession_start': nan,
  'xloss_player_possession_end': nan,
  'xloss_player_possession_max': nan,
  'xshot_player_possession_start': nan,
  'xshot_player_possession_end': nan,
  'xshot_player_possession_max': nan},
 {'event_id': '9_0',
  'index': 4,
  'phase_index': 0,
  'frame_start': 56,
  'frame_end': 58,
  'time_end': '00:04.8',
  'team_id': 4177,
  'attacking_side': 'right_to_left',
  'team_in_possession_phase_type': 'create',
  'team_out_of_possession_phase_type': 'medium_block',
  'event_type_id': 9,
  'event_type': 'on_ball_engagement',
  'event_subtype_id': 11.0,
  'event_subtype': 'pressing',
  'end_type': nan,
  'player_id': 50951,
  'player_name': 'J. Brimmer',
  'player_position': 'CF',
  'player_in_possession_id': 51649.0,
  'x_start': 13.03,
  'y_start': 0.06,
  'x_end': 13.98,
  'y_end': -0.68,
  'lead_to_shot': False,
  'lead_to_goal': False,
  'distance_covered': 14.45,
  'speed_avg': 21.52,
  'separation_gain': nan,
  'pass_distance_received': nan,
  'player_targeted_xpass_completion': nan,
  'player_targeted_xthreat': nan,
  'xthreat': nan,
  'xpass_completion': nan,
  'n_opponents_overtaken': nan,
  'xloss_player_possession_start': nan,
  'xloss_player_possession_end': nan,
  'xloss_player_possession_max': nan,
  'xshot_player_possession_start': nan,
  'xshot_player_possession_end': nan,
  'xshot_player_possession_max': nan},
 {'event_id': '8_2',
  'index': 5,
  'phase_index': 1,
  'frame_start': 72,
  'frame_end': 89,
  'time_end': '00:07.9',
  'team_id': 1805,
  'attacking_side': 'left_to_right',
  'team_in_possession_phase_type': 'direct',
  'team_out_of_possession_phase_type': 'defending_direct',
  'event_type_id': 8,
  'event_type': 'player_possession',
  'event_subtype_id': nan,
  'event_subtype': nan,
  'end_type': 'pass',
  'player_id': 735578,
  'player_name': 'M. Natta',
  'player_position': 'LB',
  'player_in_possession_id': nan,
  'x_start': -17.6,
  'y_start': 20.17,
  'x_end': -10.75,
  'y_end': 24.18,
  'lead_to_shot': False,
  'lead_to_goal': False,
  'distance_covered': 7.54,
  'speed_avg': 16.65,
  'separation_gain': -5.59,
  'pass_distance_received': 12.3,
  'player_targeted_xpass_completion': 0.4683,
  'player_targeted_xthreat': 0.0124,
  'xthreat': nan,
  'xpass_completion': nan,
  'n_opponents_overtaken': 2.0,
  'xloss_player_possession_start': nan,
  'xloss_player_possession_end': nan,
  'xloss_player_possession_max': nan,
  'xshot_player_possession_start': nan,
  'xshot_player_possession_end': nan,
  'xshot_player_possession_max': nan},
 {'event_id': '7_2',
  'index': 6,
  'phase_index': 1,
  'frame_start': 72,
  'frame_end': 82,
  'time_end': '00:07.2',
  'team_id': 1805,
  'attacking_side': 'left_to_right',
  'team_in_possession_phase_type': 'direct',
  'team_out_of_possession_phase_type': 'defending_direct',
  'event_type_id': 7,
  'event_type': 'passing_option',
  'event_subtype_id': nan,
  'event_subtype': nan,
  'end_type': nan,
  'player_id': 50978,
  'player_name': 'C. Timmins',
  'player_position': 'LDM',
  'player_in_possession_id': 735578.0,
  'x_start': -4.66,
  'y_start': 11.04,
  'x_end': -6.39,
  'y_end': 14.27,
  'lead_to_shot': False,
  'lead_to_goal': False,
  'distance_covered': 3.68,
  'speed_avg': 13.16,
  'separation_gain': -1.03,
  'pass_distance_received': nan,
  'player_targeted_xpass_completion': nan,
  'player_targeted_xthreat': nan,
  'xthreat': 0.0011,
  'xpass_completion': 0.9797,
  'n_opponents_overtaken': nan,
  'xloss_player_possession_start': nan,
  'xloss_player_possession_end': nan,
  'xloss_player_possession_max': nan,
  'xshot_player_possession_start': nan,
  'xshot_player_possession_end': nan,
  'xshot_player_possession_max': nan},
 {'event_id': '7_3',
  'index': 7,
  'phase_index': 1,
  'frame_start': 72,
  'frame_end': 89,
  'time_end': '00:07.9',
  'team_id': 1805,
  'attacking_side': 'left_to_right',
  'team_in_possession_phase_type': 'direct',
  'team_out_of_possession_phase_type': 'defending_direct',
  'event_type_id': 7,
  'event_type': 'passing_option',
  'event_subtype_id': nan,
  'event_subtype': nan,
  'end_type': nan,
  'player_id': 795507,
  'player_name': 'L. Bayliss',
  'player_position': 'AM',
  'player_in_possession_id': 735578.0,
  'x_start': 14.93,
  'y_start': 10.13,
  'x_end': 11.67,
  'y_end': 16.14,
  'lead_to_shot': False,
  'lead_to_goal': False,
  'distance_covered': 6.57,
  'speed_avg': 15.15,
  'separation_gain': 1.16,
  'pass_distance_received': nan,
  'player_targeted_xpass_completion': nan,
  'player_targeted_xthreat': nan,
  'xthreat': 0.0103,
  'xpass_completion': 0.5251,
  'n_opponents_overtaken': nan,
  'xloss_player_possession_start': nan,
  'xloss_player_possession_end': nan,
  'xloss_player_possession_max': nan,
  'xshot_player_possession_start': nan,
  'xshot_player_possession_end': nan,
  'xshot_player_possession_max': nan},
 {'event_id': '7_4',
  'index': 8,
  'phase_index': 1,
  'frame_start': 72,
  'frame_end': 89,
  'time_end': '00:07.9',
  'team_id': 1805,
  'attacking_side': 'left_to_right',
  'team_in_possession_phase_type': 'direct',
  'team_out_of_possession_phase_type': 'defending_direct',
  'event_type_id': 7,
  'event_type': 'passing_option',
  'event_subtype_id': nan,
  'event_subtype': nan,
  'end_type': nan,
  'player_id': 966120,
  'player_name': 'B. Gibson',
  'player_position': 'CF',
  'player_in_possession_id': 735578.0,
  'x_start': 12.73,
  'y_start': 3.61,
  'x_end': 16.91,
  'y_end': 9.27,
  'lead_to_shot': False,
  'lead_to_goal': False,
  'distance_covered': 6.67,
  'speed_avg': 15.21,
  'separation_gain': -1.1,
  'pass_distance_received': nan,
  'player_targeted_xpass_completion': nan,
  'player_targeted_xthreat': nan,
  'xthreat': 0.0124,
  'xpass_completion': 0.4683,
  'n_opponents_overtaken': nan,
  'xloss_player_possession_start': nan,
  'xloss_player_possession_end': nan,
  'xloss_player_possession_max': nan,
  'xshot_player_possession_start': nan,
  'xshot_player_possession_end': nan,
  'xshot_player_possession_max': nan},
 {'event_id': '7_5',
  'index': 9,
  'phase_index': 1,
  'frame_start': 73,
  'frame_end': 89,
  'time_end': '00:07.9',
  'team_id': 1805,
  'attacking_side': 'left_to_right',
  'team_in_possession_phase_type': 'direct',
  'team_out_of_possession_phase_type': 'defending_direct',
  'event_type_id': 7,
  'event_type': 'passing_option',
  'event_subtype_id': nan,
  'event_subtype': nan,
  'end_type': nan,
  'player_id': 735573,
  'player_name': 'T. Aquilina',
  'player_position': 'LW',
  'player_in_possession_id': 735578.0,
  'x_start': 7.31,
  'y_start': 19.98,
  'x_end': 6.87,
  'y_end': 27.64,
  'lead_to_shot': False,
  'lead_to_goal': False,
  'distance_covered': 7.69,
  'speed_avg': 17.16,
  'separation_gain': 0.34,
  'pass_distance_received': nan,
  'player_targeted_xpass_completion': nan,
  'player_targeted_xthreat': nan,
  'xthreat': 0.0038,
  'xpass_completion': 0.7189,
  'n_opponents_overtaken': nan,
  'xloss_player_possession_start': nan,
  'xloss_player_possession_end': nan,
  'xloss_player_possession_max': nan,
  'xshot_player_possession_start': nan,
  'xshot_player_possession_end': nan,
  'xshot_player_possession_max': nan},
 {'event_id': '1_0',
  'index': 10,
  'phase_index': 1,
  'frame_start': 74,
  'frame_end': 90,
  'time_end': '00:08.0',
  'team_id': 1805,
  'attacking_side': 'left_to_right',
  'team_in_possession_phase_type': 'direct',
  'team_out_of_possession_phase_type': 'defending_direct',
  'event_type_id': 1,
  'event_type': 'off_ball_run',
  'event_subtype_id': 7.0,
  'event_subtype': 'pulling_wide',
  'end_type': nan,
  'player_id': 735573,
  'player_name': 'T. Aquilina',
  'player_position': 'LW',
  'player_in_possession_id': 735578.0,
  'x_start': 7.31,
  'y_start': 20.4,
  'x_end': 6.94,
  'y_end': 28.05,
  'lead_to_shot': False,
  'lead_to_goal': False,
  'distance_covered': 7.69,
  'speed_avg': 17.13,
  'separation_gain': -0.01,
  'pass_distance_received': nan,
  'player_targeted_xpass_completion': nan,
  'player_targeted_xthreat': nan,
  'xthreat': 0.0038,
  'xpass_completion': 0.7189,
  'n_opponents_overtaken': 0.0,
  'xloss_player_possession_start': nan,
  'xloss_player_possession_end': nan,
  'xloss_player_possession_max': nan,
  'xshot_player_possession_start': nan,
  'xshot_player_possession_end': nan,
  'xshot_player_possession_max': nan},
 {'event_id': '9_1',
  'index': 11,
  'phase_index': 1,
  'frame_start': 74,
  'frame_end': 89,
  'time_end': '00:07.9',
  'team_id': 4177,
  'attacking_side': 'right_to_left',
  'team_in_possession_phase_type': 'direct',
  'team_out_of_possession_phase_type': 'defending_direct',
  'event_type_id': 9,
  'event_type': 'on_ball_engagement',
  'event_subtype_id': 14.0,
  'event_subtype': 'recovery_press',
  'end_type': 'indirect_disruption',
  'player_id': 38673,
  'player_name': 'G. May',
  'player_position': 'CF',
  'player_in_possession_id': 735578.0,
  'x_start': 16.03,
  'y_start': -13.76,
  'x_end': 10.97,
  'y_end': -22.06,
  'lead_to_shot': False,
  'lead_to_goal': False,
  'distance_covered': 16.64,
  'speed_avg': 21.52,
  'separation_gain': nan,
  'pass_distance_received': nan,
  'player_targeted_xpass_completion': nan,
  'player_targeted_xthreat': nan,
  'xthreat': nan,
  'xpass_completion': nan,
  'n_opponents_overtaken': nan,
  'xloss_player_possession_start': 0.288,
  'xloss_player_possession_end': 0.392,
  'xloss_player_possession_max': 0.392,
  'xshot_player_possession_start': 0.003,
  'xshot_player_possession_end': 0.0,
  'xshot_player_possession_max': 0.004},
 {'event_id': '1_1',
  'index': 12,
  'phase_index': 1,
  'frame_start': 81,
  'frame_end': 96,
  'time_end': '00:08.6',
  'team_id': 1805,
  'attacking_side': 'left_to_right',
  'team_in_possession_phase_type': 'direct',
  'team_out_of_possession_phase_type': 'defending_direct',
  'event_type_id': 1,
  'event_type': 'off_ball_run',
  'event_subtype_id': 2.0,
  'event_subtype': 'coming_short',
  'end_type': nan,
  'player_id': 795507,
  'player_name': 'L. Bayliss',
  'player_position': 'AM',
  'player_in_possession_id': 735578.0,
  'x_start': 14.25,
  'y_start': 12.68,
  'x_end': 10.46,
  'y_end': 19.53,
  'lead_to_shot': False,
  'lead_to_goal': False,
  'distance_covered': 7.52,
  'speed_avg': 18.79,
  'separation_gain': -0.08,
  'pass_distance_received': nan,
  'player_targeted_xpass_completion': nan,
  'player_targeted_xthreat': nan,
  'xthreat': 0.0051,
  'xpass_completion': 0.7879,
  'n_opponents_overtaken': 0.0,
  'xloss_player_possession_start': nan,
  'xloss_player_possession_end': nan,
  'xloss_player_possession_max': nan,
  'xshot_player_possession_start': nan,
  'xshot_player_possession_end': nan,
  'xshot_player_possession_max': nan},
 {'event_id': '1_2',
  'index': 13,
  'phase_index': 1,
  'frame_start': 82,
  'frame_end': 99,
  'time_end': '00:08.9',
  'team_id': 1805,
  'attacking_side': 'left_to_right',
  'team_in_possession_phase_type': 'direct',
  'team_out_of_possession_phase_type': 'defending_direct',
  'event_type_id': 1,
  'event_type': 'off_ball_run',
  'event_subtype_id': 1.0,
  'event_subtype': 'behind',
  'end_type': nan,
  'player_id': 966120,
  'player_name': 'B. Gibson',
  'player_position': 'CF',
  'player_in_possession_id': 735578.0,
  'x_start': 15.51,
  'y_start': 6.38,
  'x_end': 19.96,
  'y_end': 13.36,
  'lead_to_shot': False,
  'lead_to_goal': False,
  'distance_covered': 7.84,
  'speed_avg': 17.57,
  'separation_gain': -3.29,
  'pass_distance_received': nan,
  'player_targeted_xpass_completion': nan,
  'player_targeted_xthreat': nan,
  'xthreat': 0.0124,
  'xpass_completion': 0.4683,
  'n_opponents_overtaken': 2.0,
  'xloss_player_possession_start': nan,
  'xloss_player_possession_end': nan,
  'xloss_player_possession_max': nan,
  'xshot_player_possession_start': nan,
  'xshot_player_possession_end': nan,
  'xshot_player_possession_max': nan},
 {'event_id': '8_3',
  'index': 14,
  'phase_index': 2,
  'frame_start': 202,
  'frame_end': 229,
  'time_end': '00:21.9',
  'team_id': 4177,
  'attacking_side': 'right_to_left',
  'team_in_possession_phase_type': 'build_up',
  'team_out_of_possession_phase_type': 'high_block',
  'event_type_id': 8,
  'event_type': 'player_possession',
  'event_subtype_id': nan,
  'event_subtype': nan,
  'end_type': 'pass',
  'player_id': 33697,
  'player_name': 'N. Pijnaker',
  'player_position': 'LCB',
  'player_in_possession_id': nan,
  'x_start': -27.84,
  'y_start': 6.4,
  'x_end': -23.05,
  'y_end': 13.87,
  'lead_to_shot': False,
  'lead_to_goal': False,
  'distance_covered': 8.63,
  'speed_avg': 11.83,
  'separation_gain': -4.3,
  'pass_distance_received': nan,
  'player_targeted_xpass_completion': 0.9947,
  'player_targeted_xthreat': 0.0003,
  'xthreat': nan,
  'xpass_completion': nan,
  'n_opponents_overtaken': 0.0,
  'xloss_player_possession_start': nan,
  'xloss_player_possession_end': nan,
  'xloss_player_possession_max': nan,
  'xshot_player_possession_start': nan,
  'xshot_player_possession_end': nan,
  'xshot_player_possession_max': nan},
 {'event_id': '7_6',
  'index': 15,
  'phase_index': 2,
  'frame_start': 202,
  'frame_end': 229,
  'time_end': '00:21.9',
  'team_id': 4177,
  'attacking_side': 'right_to_left',
  'team_in_possession_phase_type': 'build_up',
  'team_out_of_possession_phase_type': 'high_block',
  'event_type_id': 7,
  'event_type': 'passing_option',
  'event_subtype_id': nan,
  'event_subtype': nan,
  'end_type': nan,
  'player_id': 133498,
  'player_name': 'F. De Vries',
  'player_position': 'LB',
  'player_in_possession_id': 33697.0,
  'x_start': -15.93,
  'y_start': 21.92,
  'x_end': -10.82,
  'y_end': 30.43,
  'lead_to_shot': False,
  'lead_to_goal': False,
  'distance_covered': 9.78,
  'speed_avg': 13.2,
  'separation_gain': -5.62,
  'pass_distance_received': nan,
  'player_targeted_xpass_completion': nan,
  'player_targeted_xthreat': nan,
  'xthreat': 0.0003,
  'xpass_completion': 0.9947,
  'n_opponents_overtaken': nan,
  'xloss_player_possession_start': nan,
  'xloss_player_possession_end': nan,
  'xloss_player_possession_max': nan,
  'xshot_player_possession_start': nan,
  'xshot_player_possession_end': nan,
  'xshot_player_possession_max': nan},
 {'event_id': '1_3',
  'index': 16,
  'phase_index': 2,
  'frame_start': 207,
  'frame_end': 217,
  'time_end': '00:20.7',
  'team_id': 4177,
  'attacking_side': 'right_to_left',
  'team_in_possession_phase_type': 'build_up',
  'team_out_of_possession_phase_type': 'high_block',
  'event_type_id': 1,
  'event_type': 'off_ball_run',
  'event_subtype_id': 7.0,
  'event_subtype': 'pulling_wide',
  'end_type': nan,
  'player_id': 133498,
  'player_name': 'F. De Vries',
  'player_position': 'LB',
  'player_in_possession_id': 33697.0,
  'x_start': -15.24,
  'y_start': 23.74,
  'x_end': -12.76,
  'y_end': 27.44,
  'lead_to_shot': False,
  'lead_to_goal': False,
  'distance_covered': 4.46,
  'speed_avg': 15.93,
  'separation_gain': -5.43,
  'pass_distance_received': nan,
  'player_targeted_xpass_completion': nan,
  'player_targeted_xthreat': nan,
  'xthreat': 0.0003,
  'xpass_completion': 0.9947,
  'n_opponents_overtaken': 1.0,
  'xloss_player_possession_start': nan,
  'xloss_player_possession_end': nan,
  'xloss_player_possession_max': nan,
  'xshot_player_possession_start': nan,
  'xshot_player_possession_end': nan,
  'xshot_player_possession_max': nan},
 {'event_id': '7_7',
  'index': 17,
  'phase_index': 2,
  'frame_start': 228,
  'frame_end': 229,
  'time_end': '00:21.9',
  'team_id': 4177,
  'attacking_side': 'right_to_left',
  'team_in_possession_phase_type': 'build_up',
  'team_out_of_possession_phase_type': 'high_block',
  'event_type_id': 7,

In [2]:
meta_data = di._get_bronze_meta_data(1886347)
tracking_df = di._get_silver_tracking_data_from_kloppy(1886347, meta_data)

Index(['period_id', 'timestamp', 'frame_id', 'ball_state',
       'ball_owning_team_id', 'ball_x', 'ball_y', 'ball_z', 'ball_speed',
       '51009_x',
       ...
       '31147_d', '31147_s', '800320_x', '800320_y', '800320_d', '800320_s',
       '797297_x', '797297_y', '797297_d', '797297_s'],
      dtype='object', length=125)
Keep columns: ['51009_x', '51009_y', '176224_x', '176224_y', '51649_x', '51649_y', '50983_x', '50983_y', '735578_x', '735578_y', '50978_x', '50978_y', '735574_x', '735574_y', '795507_x', '795507_y', '795505_x', '795505_y', '735573_x', '735573_y', '966120_x', '966120_y', '285188_x', '285188_y', '51667_x', '51667_y', '33697_x', '33697_y', '51713_x', '51713_y', '133498_x', '133498_y', '14736_x', '14736_y', '23418_x', '23418_y', '133501_x', '133501_y', '965685_x', '965685_y', '50951_x', '50951_y', '38673_x', '38673_y', '560992_x', '560992_y', '795506_x', '795506_y', '43829_x', '43829_y', '163972_x', '163972_y', '31147_x', '31147_y', '800320_x', '800320_y', '797297_x', '797297_y']
Rename map: {'51009_x': 'away_51009_x', '51009_y': 'away_51009_y', '176224_x': 'away_176224_x', '176224_y': 'away_176224_y', '51649_x': 'away_51649_x', '51649_y': 'away_51649_y', '50983_x': 'away_50983_x', '50983_y': 'away_50983_y', '735578_x': 'away_735578_x', '735578_y': 'away_735578_y', '50978_x': 'away_50978_x', '50978_y': 'away_50978_y', '735574_x': 'away_735574_x', '735574_y': 'away_735574_y', '795507_x': 'away_795507_x', '795507_y': 'away_795507_y', '795505_x': 'away_795505_x', '795505_y': 'away_795505_y', '735573_x': 'away_735573_x', '735573_y': 'away_735573_y', '966120_x': 'away_966120_x', '966120_y': 'away_966120_y', '285188_x': 'home_285188_x', '285188_y': 'home_285188_y', '51667_x': 'home_51667_x', '51667_y': 'home_51667_y', '33697_x': 'home_33697_x', '33697_y': 'home_33697_y', '51713_x': 'home_51713_x', '51713_y': 'home_51713_y', '133498_x': 'home_133498_x', '133498_y': 'home_133498_y', '14736_x': 'home_14736_x', '14736_y': 'home_14736_y', '23418_x': 'home_23418_x', '23418_y': 'home_23418_y', '133501_x': 'home_133501_x', '133501_y': 'home_133501_y', '965685_x': 'home_965685_x', '965685_y': 'home_965685_y', '50951_x': 'home_50951_x', '50951_y': 'home_50951_y', '38673_x': 'home_38673_x', '38673_y': 'home_38673_y', '560992_x': 'away_560992_x', '560992_y': 'away_560992_y', '795506_x': 'away_795506_x', '795506_y': 'away_795506_y', '43829_x': 'home_43829_x', '43829_y': 'home_43829_y', '163972_x': 'home_163972_x', '163972_y': 'home_163972_y', '31147_x': 'home_31147_x', '31147_y': 'home_31147_y', '800320_x': 'away_800320_x', '800320_y': 'away_800320_y', '797297_x': 'away_797297_x', '797297_y': 'away_797297_y'}

In [4]:
tracking_df.describe()

,frame_id,period_id,timestamp,ball_owning_team_id,ball_x,ball_y,ball_z,ball_vx,ball_vy,ball_speed,home_38673_x,home_38673_y,home_38673_vx,home_38673_vy,home_38673_speed,home_51713_x,home_51713_y,home_51713_vx,home_51713_vy,home_51713_speed,home_50951_x,home_50951_y,home_50951_vx,home_50951_vy,home_50951_speed,away_50978_x,away_50978_y,away_50978_vx,away_50978_vy,away_50978_speed,home_133498_x,home_133498_y,home_133498_vx,home_133498_vy,home_133498_speed,home_33697_x,home_33697_y,home_33697_vx,home_33697_vy,home_33697_speed,home_51667_x,home_51667_y,home_51667_vx,home_51667_vy,home_51667_speed,home_14736_x,home_14736_y,home_14736_vx,home_14736_vy,home_14736_speed,away_735573_x,away_735573_y,away_735573_vx,away_735573_vy,away_735573_speed,away_51009_x,away_51009_y,away_51009_vx,away_51009_vy,away_51009_speed,away_176224_x,away_176224_y,away_176224_vx,away_176224_vy,away_176224_speed,away_735578_x,away_735578_y,away_735578_vx,away_735578_vy,away_735578_speed,away_735574_x,away_735574_y,away_735574_vx,away_735574_vy,away_735574_speed,away_50983_x,away_50983_y,away_50983_vx,away_50983_vy,away_50983_speed,away_51649_x,away_51649_y,away_51649_vx,away_51649_vy,away_51649_speed,home_965685_x,home_965685_y,home_965685_vx,home_965685_vy,home_965685_speed,away_795506_x,away_795506_y,away_795506_vx,away_795506_vy,away_795506_speed,away_797297_x,away_797297_y,away_797297_vx,away_797297_vy,away_797297_speed,away_560992_x,away_560992_y,away_560992_vx,away_560992_vy,away_560992_speed,away_800320_x,away_800320_y,away_800320_vx,away_800320_vy,away_800320_speed,home_43829_x,home_43829_y,home_43829_vx,home_43829_vy,home_43829_speed,home_31147_x,home_31147_y,home_31147_vx,home_31147_vy,home_31147_speed,home_163972_x,home_163972_y,home_163972_vx,home_163972_vy,home_163972_speed,home_133501_x,home_133501_y,home_133501_vx,home_133501_vy,home_133501_speed,home_23418_x,home_23418_y,home_23418_vx,home_23418_vy,home_23418_speed,away_795507_x,away_795507_y,away_795507_vx,away_795507_vy,away_795507_speed,away_795505_x,away_795505_y,away_795505_vx,away_795505_vy,away_795505_speed,away_966120_x,away_966120_y,away_966120_vx,away_966120_vy,away_966120_speed,home_285188_x,home_285188_y,home_285188_vx,home_285188_vy,home_285188_speed
count,3157.000000,3157.000000,3157,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.00000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.00000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000,3157.000000
mean,26413.417168,1.447260,0 days 00:23:17.406018371,3158.925879,1.508663,-1.438369,0.566845,-0.112449,-0.061071,68.454103,-2.656842,-0.188426,0.158347,-0.041970,24.640345,1.043380,2.095112,-0.105638,-0.112575,29.332036,-3.068068,-1.967035,0.089674,-0.04083,25.591136,-0.033852,-2.780538,0.142635,-0.027621,30.757065,0.535724,-3.093453,-0.079538,0.071714,30.220590,2.074150,-1.759990,-0.119259,0.007190,25.892986,2.453047,-0.345195,-0.134748,-0.056921,26.618696,0.945971,-0.659471,-0.051093,-0.077795,33.960268,-0.913687,8.972502,-0.031992,-0.040988,32.777100,-4.089997,-0.210583,0.249066,-0.010231,10.354194,-1.741220,-1.369009,0.088343,0.008014,26.017046,-1.962347,0.738232,0.086316,-0.127178,27.697335,-0.914286,2.944102,0.026417,-0.030409,31.136162,-1.077263,-2.245046,0.009693,0.107064,29.164585,-2.026132,-0.648226,0.091036,-0.05445,26.259302,-1.240481,-1.930215,-0.006398,0.068071,31.870215,-1.154539,-1.411517,-0.074976,0.009059,8.430550,0.602914,-0.281536,-0.036902,-0.038201,3.354457,1.763621,-5.227567,-0.065664,0.014317,9.820379,-0.963985,-0.223982,-0.045423,-0.006113,3.321844,2.501527,-2.918400,-0.039753,-0.070922,7.810343,-1.213288,0.001878,0.026037,-0.027114,3.025239,2.721004,-0.565946,0.057016,-0.076053,5.476488,-3.662186,4.731530,-0.022078,-0.038518,24.694912,0.442281,-2.427862,-0.028571,0.013462,35.607234,1.368090,0.922056,0.079062,-0.032246,23.266962,-0.400985,-6.999544,0.040101,0.065790,27.872172,2.827941,-1.031726,-0.041083,-0.019512,23.117092,4.399943,-0.163513,-0.249541,-0.049382,11.582694
std,16876.506539,0.497289,0 days 00:14:42.725716687,1174.237478,25.398793,19.743180,1.269099,60.063006,61.649985,52.161794,23.617471,11.966844,26.320128,29.936657,31.331142,19.418831,20.014716,38.344162,28.398396,37.631457,20.319239,14.542511,29.826663,34.28174,37.546817,21.481037,12.979193,30.271465,32.181580,31.713404,20.825085,21.329617,41.631563,31.042191,42.228458,19.475517,11.702259,37.405083,25.542885,37.160925,19.171996,11.914917,40.866770,26.373969,40.705295,18.875563,13.334481,38.595089,31.821021,36.721952,21.064544,16.445981,41.444332,31.787339,40.661918,42.021507,2.960527,17.503057,9.023719,16.751220,27.152793,11.714973,31.952346,26.183622,32.084906,26.155654,16.587533,33.049597,27.468976,32.855117,21.891102,13.502992,31.746232,31.063689,31.670332,25.009346,20.119010,40.888543,30.293662,41.698296,27.494166,9.780319,31.752985,26.20212,31.702444,22.192108,16.734941,38.871109,29.310759,36.797499,9.446505,7.972628,23.864094,16.000505,27.466710,6.005551,4.004728,13.566993,10.791076,17.007572,12.218969,9.997406,25.756364,16.326267,28.869905,6.601343,3.737916,17.946155,10.510953,20.530674,9.893474,7.606917,23.229917,14.082454,26.017886,6.573411,2.657466,19.441306,8.173660,20.871500,9.677050,5.959112,16.807961,13.301239,20.722888,20.885614,15.511546,29.427815,27.784545,32.061617,20.135375,15.773083,37.057673,37.086473,38.475990,16.626551,10.733535,27.441061,28.071468,31.614924,18.890611,16.317548,34.575073,30.524494,36.743465,16.939332,12.054791,32.780312,28.201636,36.541947,35.634876,3.612129,20.863695,10.266534,20.163306
min,30.000000,1.000000,0 days 00:00:02,1805.000000,-52.980000,-35.310000,-0.360000,-479.700000,-389.400000,0.000000,-52.460000,-34.460000,-261.100000,-401.100000,0.000000,-52.080000,-34.270000,-426.700000,-322.000000,0.000000,-57.050000,-33.110000,-377.900000,-587.00000,0.000000,-50.010000,-30.690000,-243.900000,-406.800000,0.000000,-52.440000,-34.610000,-526.700000,-340.500000,0.000000,-49.520000,-30.390000,-452.900000,-333.800000,0.000000,-47.860000,-34.290000,-585.100000,-283.900000,0.000000,-47.700000,-32.570000,-576.000000,-333.800000,0.000000,-48.460000,-33.910000,-451.500000,-469.500000,0.000000,-51.930000,-17.940000,-133.800000,-91.800000,0.000000,-51.560000,-32.900000,-477.400000,-390.000000,0.000000,-49.080000,-34.960000,-418.300000,-382.600000,0.000000,-50.910000,-33.380000,-347.200000,-370.600000,0.000000,-49.680000,-34.480000,-465.100000,-337.800000,0.000000,-50.410000,-32.040000,-440.800000,-279.20000,0.000000,-51.310000,-36.280000,-537.700000,-317.600000,0.000000,-43.690000,-33.650000,-429.500000,-297.000000,0.000000,-25.990000,-29.340000,-331.200000,-275.100000,0.000000,-45.050000,-36.440000,-435.900000,-274.100000,0.000000,-46.160000,-29.900000,-435.000000,-306.900000,0.000000,-36.040000,-34.480000,-454.000000,-242.300000,0.000000,-43.760000,-19.550000,-635.200000,-226.000000,0.000000,-37.470000,-30.140000,-415.600000,-261.500000,0.000000,-50.000000,-36.830000,-262.000000,-465.800000,0.000000,-54.590000,-34.550000,-326.700000,-587.100000,0.000000,-49.720000,-27.500000,-341.500000,-439.400000,0.000000,-52.090000,-33.650000,-313.300000,-348.000000,0.000000,-49.190000,-31.410000,-467.800000,-345.100000,0.000000,-51.470000,-18.110000,-856.600000,-116.100000,0.000000
25%,11770.000000,1.000000,0 days 00:10:24,1805.000000,-18.480000,-18.900000,0.100000,-31.600000,-31.100000,34.159186,-22.250000,-6.990000,-9.900000,-8.700000,9.019978,-13.510000,-15.030000,-14.900000,-10.900000,12.822246,-19.200000,-12.920000,-9.700000,-8.50000,8.549269,-15.840000,-11.870000,-15.100000,-14.300000,15.102980,-14.500000,-23.570000,-14.900000,-10.700000,13.823531,-10.010000,-10.270000,-12.800000,-9.800000,12.140016,-8.490000,-8.110000,-12.100000,-10.000000,11.667476,-11.760000,-10.300000,-15.900000,-16.400000,18.083418,-16.920000,-1.840000,-16.900000,-12.000000,15.318290,-43.350000,-1.920000,-5.100000,-3.900000,4.601087,-25.280000,-9.300000,-13.300000,-9.000000,12.228655,-24.230000,-13.390000,-14.500000,-10.200000,13.039172,-18.060000,-6.330000,-14.600000,-14.900000,16.200309,-21.080000,-20.020000,-15.200000,-10.000000,13.074020,-25.830000,-6.010000,-13.400000,-9.60000,12.794139,-18.840000,-16.270000,-16.900000,-12.600000,15.316005,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-4.840000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-18.460000,-0.490000,-12.100000,-8.100000,4.801042,-13.720000,-14.780000,-17.800000,-15.500000,19.780040,-5.910000,-4.550000,-10.400000,-9.500000,0.000000,-13.200000,-20.020000,-13.700000,-9.400000,12.657409,-2.950000,-8.230000,-9.200000,-8.300000,2.886174,-32.030000,-2.480000,-5.100000,-4.300000,5.108816
50%,24990.000000,1.000000,0 days 00:23:15.900000,4177.000000,2.740000,-1.790000,0.160000,-1.100000,1.200000,56.201957,-2.120000,0.000000,0.000000,0.000000,18.085353,0.450000,3.650000,-1.200000,0.300000,22.264770,0.000000,0.000000,0.000000,0.00000,18.880943,0.000000,-1.450000,0.000000,0.000000,28.401584,1.560000,-4.460000,-0.700000,-0.300000,22.141590,1.630000,-1.720000,-0.800000,0.200000,19.260582,1.940000,-0.580000,-1.100000,0.000000,19.577794,0.990000,-0.060000,-1.400000,0.100000,29.531170,-0.980000,11.800000,-0.800000,-1.300000,25.419677,-31.860000,-0.190000,-0.200000,0.000000,7.960528,-4.600000,-1.620000,-0.400000,0.700000,20.319449,-4.390000,2.480000,-1.100000,0.600000,22.095475,-0.720000,3.450000,-0.700000,-0.700000,27.508726,-3.850000,-3.870000,-1.200000,0.200000,21.582400,-4.990000,-0.640000,-0.900000,0.00000,20.400000,-3.210000,-2.010000,0.000000,-0.100000,25.249158,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.840000,0.000000,0.000000,20.814658,0.330000,-3.240000,-1.300000,0.900000,30.383713,0.000000,0.000000,0.000000,0.000000,20.506097,0.000000,-9.470000,0.000000,0.000000,20.909567,0.000000,0.000000,0.000000,0.000000,17.545370,26.720000,-0.170000,-0.200000,0.100000,8.475848
75%,40859.000000,2.000000,0 days 00:35:02.900000,4177.000000,21.460000,15.150000,0.290000,30.400000,31.400000,90.827749,15.120000,6.670000,9.600000,9.600000,32.031547,14.630000,20.390000,12.500000,11.300000,34.702305,8.760000,5.560000,10.300000,10.50000,33.392364,15.270000,4.900000,13.600000,16.000000,38.615152,15.110000,16.220000,14.300000,11.200000,33.201506,15.160000,6.300000,11.000000,10.700000,28.968949,13.660000,7.730000,10.400000,11.200000,30.149793,13.860000,8.340000,15.000000,17.200000,38.930836,13.870000,22.060000,16.200000,12.700000,38.626416,42.060000,1.500000,4.300000,4.000000,12.033287,22.470000,5.910000,12.000000,10.400000,30.372685,19.680000,14.230000,12.900000,10.900000,32.262207,15.040000,12.720000,13.700000,15.400000,37.215588,20.040000,14.860000,13.100000,10.800000,32.768583,22.160000,4.950000,12.300000,10.60000,31.646959,16.660000,11.470000,14.500000,13.100000,37.432205,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.263776,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.100000,16.240000,11.200000,8.800000,34.302332,13.710000,9.310000,16.500000,19.100000,41.732601,10.890000,6.110000,7.600000,9.300000,32.951479,11.090000,1.260000,12.400000,11.300000,33.905309,12.200000,4.380000,7.000000,8.700000,31.586864,35.710000,2.130000,4.600000,4.600000,12.844454
max,58929.000000,2.000000,0 days 00:51:52.900000,4177.000000,53.400000,35.850000,13.460000,747.300000,472.300000,756.465498,47.690000,32.190000,265.000000,370.800000,428.718136,52.460000,34.300000,405.900000,305.200000,467.449955,50.660000,34.290000,347.400000,418.50000,605.077879,52.370000,33.730000,296.200000,353.700000,466.141609,50.650000,35.250000,397.000000,444.600000,540.577266,50.600000,33.050000,466.700000,359.500000,501.127389,49.910000,34.400000,478.300000,347.400000,605.849693,49.220000,34.010000,409.900000,394.500000,576.319911,49.640000,34.310000,423.200000,306.100000,519.126670,53.110000,13.050000,722.800000,81.600000,724.224413,50.710000,34.310000,451.700000,278.600000,542.428797,50.580000,35.130000,374.400000,380.500000,421.385453,51.530000,33.180000,360.200000,358.600000,502.308720,50.350000,35.070000,486.300000,294.400000,592.111924,50.030000,32.200000,479.700000,409.40000,487.472030,52.560000,33.970000,490.600000,369.700000,584.429739,49.470000,33.200000,495.900000,194.300000,501.750705,48.440000,30.180000,330.200000,220.300000,421.313209,50.550000,23.720000,417.200000,313.000000,451.904249,45.270000,29.530000,477.300000,220.700000,518.061946,52.150000,32.460000,454.700000,229.900000,515.229444,49.470000,21.820000,505.000000,157.500000,639.659441,51.040000,28.580000,317.000000,261.500000,445.437549,50.270000,34.800000,301.600000,303.000000,474.740487,55.020000,34.900000,393.100000,366.500000,593.958256,49.950000,32.320000,357.000000,394.700000,486.898449,50.090000,35.030000,392.400000,421.000000,480.885392,51.700000,35.300000,517.600000,495.200000,552.581288,51.090000,16.460000,148.000000,98.100000,856.742038

In [2]:
# # To load all the data
# data = di.load_data(match_id=1886347)

In [16]:
# # To view the loaded data
# with open (f"../../data/gold_tracking_data.json", "r") as f:
#     gold_tracking_data = json.load(f)

# frames = gold_tracking_data['frames']

In [3]:
# To view tracking data at different stages of the pipeline
bronze_tracking_data = di._get_bronze_tracking_data(match_id=1899585)
silver_tracking_data = di._get_silver_tracking_data(bronze_tracking_data)
bronze_meta_data = di._get_bronze_meta_data(match_id=1899585)
silver_meta_data = di._get_silver_meta_data(bronze_meta_data)
bronze_event_data = di._get_bronze_event_data(match_id=1899585)
silver_event_data = di._get_silver_event_data(bronze_event_data)
# gold_data = di._get_gold_tracking_data(silver_tracking_data, silver_meta_data, silver_event_data)

/Users/mihirthalanki/Documents/MT/Hackathon/PlayTactix/backend/services/data_ingestor_github.py:261: DtypeWarning: Columns (276) have mixed types. Specify dtype option on import or set low_memory=False.
  raw_data = pd.read_csv(event_data_github_url)
/Users/mihirthalanki/Documents/MT/Hackathon/PlayTactix/backend/services/data_ingestor_github.py:276: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  silver_event_data['event_subtype_id'] = silver_event_data['event_subtype_id'].fillna(0).astype(int)
/Users/mihirthalanki/Documents/MT/Hackathon/PlayTactix/backend/services/data_ingestor_github.py:277: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  silver_event_data['event_subtype'] = silver_event_data['event_subtype'].fillna('Unknown')
/Users/mihirthalanki/Documents/MT/Hackathon/PlayTactix/backend/services/data_ingestor_github.py:278: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  silver_event_data['player_position'] = silver_event_data['player_position'].fillna('Unknown')
/Users/mihirthalanki/Documents/MT/Hackathon/PlayTactix/backend/services/data_ingestor_github.py:279: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  silver_event_data['player_in_possession_id'] = silver_event_data['player_in_possession_id'].fillna(-1).astype(int)
/Users/mihirthalanki/Documents/MT/Hackathon/PlayTactix/backend/services/data_ingestor_github.py:280: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  silver_event_data['player_targeted_xthreat'] = silver_event_data['player_targeted_xthreat'].fillna(-1).astype(float)
/Users/mihirthalanki/Documents/MT/Hackathon/PlayTactix/backend/services/data_ingestor_github.py:281: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  silver_event_data['lead_to_shot'] = silver_event_data['lead_to_shot'].fillna(False).astype(bool)
/Users/mihirthalanki/Documents/MT/Hackathon/PlayTactix/backend/services/data_ingestor_github.py:282: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  silver_event_data['lead_to_goal'] = silver_event_data['lead_to_goal'].fillna(False).astype(bool)
/Users/mihirthalanki/Documents/MT/Hackathon/PlayTactix/backend/services/data_ingestor_github.py:283: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  silver_event_data['distance_covered'] = silver_event_data['distance_covered'].fillna(0).astype(float)
/Users/mihirthalanki/Documents/MT/Hackathon/PlayTactix/backend/services/data_ingestor_github.py:284: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  silver_event_data['speed_avg'] = silver_event_data['speed_avg'].fillna(0).astype(float)
/Users/mihirthalanki/Documents/MT/Hackathon/PlayTactix/backend/services/data_ingestor_github.py:285: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  silver_event_data['separation_gain'] = silver_event_data['separation_gain'].fillna(0).astype(float)
/Users/mihirthalanki/Documents/MT/Hackathon/PlayTactix/backend/services/data_ingestor_github.py:286: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  silver_event_data['pass_distance_received'] = silver_event_data['pass_distance_received'].fillna(0).astype(float)
/Users/mihirthalanki/Documents/MT/Hackathon/PlayTactix/backend/services/data_ingestor_github.py:287: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  silver_event_data['player_targeted_xpass_completion'] = silver_event_data['player_targeted_xpass_completion'].fillna(-1).astype(float)
/Users/mihirthalanki/Documents/MT/Hackathon/PlayTactix/backend/services/data_ingestor_github.py:288: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  silver_event_data['xthreat'] = silver_event_data['xthreat'].fillna(-1).astype(float)
/Users/mihirthalanki/Documents/MT/Hackathon/PlayTactix/backend/services/data_ingestor_github.py:289: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  silver_event_data['xpass_completion'] = silver_event_data['xpass_completion'].fillna(-1).astype(float)
/Users/mihirthalanki/Documents/MT/Hackathon/PlayTactix/backend/services/data_ingestor_github.py:290: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  silver_event_data['n_opponents_overtaken'] = silver_event_data['n_opponents_overtaken'].fillna(0).astype(int)
/Users/mihirthalanki/Documents/MT/Hackathon/PlayTactix/backend/services/data_ingestor_github.py:291: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  silver_event_data['xloss_player_possession_max'] = silver_event_data['xloss_player_possession_max'].fillna(-1).astype(float)
/Users/mihirthalanki/Documents/MT/Hackathon/PlayTactix/backend/services/data_ingestor_github.py:292: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  silver_event_data['xshot_player_possession_max'] = silver_event_data['xshot_player_possession_max'].fillna(-1).astype(float)

In [5]:
pd.set_option('display.max_columns', None)
silver_event_data.head(20)

,event_id,index,frame_start,frame_end,attacking_side,event_type_id,event_type,event_subtype_id,event_subtype,player_id,player_name,player_position,player_in_possession_id,team_id,x_start,y_start,x_end,y_end,lead_to_shot,lead_to_goal,distance_covered,speed_avg,separation_gain,pass_distance_received,player_targeted_xpass_completion,player_targeted_xthreat,xthreat,xpass_completion,n_opponents_overtaken,xloss_player_possession_max,xshot_player_possession_max
0,8_0,0,12,12,left_to_right,8,player_possession,0,Unknown,23909,K. Barbarouses,RF,-1,867,0.53,-0.28,0.53,-0.28,False,False,0.00,0.00,0.00,0.00,-1.0000,-1.0000,-1.0000,-1.0000,0,-1.000,-1.000
1,8_1,1,31,44,left_to_right,8,player_possession,0,Unknown,42510,S. Wootton,LCB,-1,867,-20.68,0.53,-20.75,-0.04,False,False,0.51,1.63,-8.11,23.99,0.9821,0.0002,-1.0000,-1.0000,0,-1.000,-1.000
2,7_0,2,31,32,left_to_right,7,passing_option,0,Unknown,51015,A. Rufer,LM,42510,867,-9.38,-3.50,-9.36,-3.52,False,False,0.10,0.86,-0.18,0.00,-1.0000,-1.0000,0.0008,0.9565,0,-1.000,-1.000
3,7_1,3,31,44,left_to_right,7,passing_option,0,Unknown,799092,M. Sheridan,RCB,42510,867,-17.97,-13.76,-18.41,-14.35,False,False,1.07,3.39,-0.93,0.00,-1.0000,-1.0000,0.0003,0.9981,0,-1.000,-1.000
4,9_0,4,37,44,right_to_left,9,on_ball_engagement,11,pressing,38673,G. May,CF,42510,4177,11.77,-3.34,15.46,-1.41,False,False,16.11,21.82,0.00,0.00,-1.0000,-1.0000,-1.0000,-1.0000,0,-1.000,-1.000
5,7_2,5,42,44,left_to_right,7,passing_option,0,Unknown,698137,I. Hughes,CB,42510,867,-18.71,10.11,-18.58,10.14,False,False,0.26,2.35,-5.56,0.00,-1.0000,-1.0000,0.0002,0.9821,0,-1.000,-1.000
6,7_3,6,43,44,left_to_right,7,passing_option,0,Unknown,51015,A. Rufer,LM,42510,867,-9.13,-3.10,-9.16,-2.99,False,False,0.33,3.23,-0.01,0.00,-1.0000,-1.0000,0.0008,0.9565,0,-1.000,-1.000
7,9_1,7,53,62,right_to_left,9,on_ball_engagement,11,pressing,38673,G. May,CF,698137,4177,17.87,-3.01,18.23,-7.49,False,False,4.01,17.83,0.00,0.00,-1.0000,-1.0000,-1.0000,-1.0000,0,0.197,0.000
8,1_0,8,57,66,left_to_right,1,off_ball_run,2,coming_short,51015,A. Rufer,LM,698137,867,-9.98,0.48,-10.80,4.37,False,False,3.58,15.88,-1.59,0.00,-1.0000,-1.0000,0.0005,0.9931,0,-1.000,-1.000
9,8_2,9,62,62,left_to_right,8,player_possession,0,Unknown,698137,I. Hughes,CB,-1,867,-17.98,11.27,-17.98,11.27,False,False,0.00,3.44,0.00,11.19,0.9931,0.0005,-1.0000,-1.0000,0,-1.000,-1.000
10,7_4,10,62,62,left_to_right,7,passing_option,0,Unknown,27003,K. Nagasawa,CF,698137,867,0.95,8.98,0.95,8.98,False,False,0.00,9.59,0.00,0.00,-1.0000,-1.0000,0.0016,0.9782,0,-1.000,-1.000
11,7_5,11,62,62,left_to_right,7,passing_option,0,Unknown,51015,A. Rufer,LM,698137,867,-10.27,2.73,-10.27,2.73,False,False,0.00,16.21,-0.90,0.00,-1.0000,-1.0000,0.0005,0.9931,0,-1.000,-1.000
12,8_3,12,73,106,left_to_right,8,player_possession,0,Unknown,51015,A. Rufer,LM,-1,867,-12.32,6.44,-6.80,17.45,False,False,12.93,14.22,0.06,13.34,0.9648,0.0010,-1.0000,-1.0000,0,-1.000,-1.000
13,7_6,13,73,74,left_to_right,7,passing_option,0,Unknown,42510,S. Wootton,LCB,51015,867,-23.93,0.49,-24.05,0.51,False,False,0.56,4.85,0.03,0.00,-1.0000,-1.0000,0.0001,0.9953,0,-1.000,-1.000
14,7_7,14,73,93,left_to_right,7,passing_option,0,Unknown,27003,K. Nagasawa,CF,51015,867,-1.68,11.48,-5.61,10.15,False,False,4.60,8.22,-3.05,0.00,-1.0000,-1.0000,0.0015,0.9707,0,-1.000,-1.000
15,7_8,15,82,85,left_to_right,7,passing_option,0,Unknown,698137,I. Hughes,CB,51015,867,-19.53,15.31,-19.46,16.28,False,False,1.22,11.28,0.37,0.00,-1.0000,-1.0000,0.0002,0.9630,0,-1.000,-1.000
16,7_9,16,82,106,left_to_right,7,passing_option,0,Unknown,51028,S. Sutton,LWB,51015,867,7.12,29.22,3.03,31.88,False,False,4.89,7.33,-9.32,0.00,-1.0000,-1.0000,0.0010,0.9648,0,-1.000,-1.000
17,9_2,17,87,106,right_to_left,9,on_ball_engagement,11,pressing,50951,J. Brimmer,CF,51015,4177,11.64,-7.83,5.40,-15.02,False,False,10.09,17.89,0.00,0.00,-1.0000,-1.0000,-1.0000,-1.0000,0,0.214,0.006
18,1_1,18,88,105,left_to_right,1,off_ball_run,1,behind,26969,H. Ishige,LF,51015,867,13.18,19.94,20.60,23.58,False,False,7.86,17.37,2.05,0.00,-1.0000,-1.0000,0.0188,0.4008,3,-1.000,-1.000
19,7_10,19,90,106,left_to_right,7,passing_option,0,Unknown,26969,H. Ishige,LF,51015,867,13.90,20.42,20.91,23.82,False,False,7.81,17.41,2.85,0.00,-1.0000,-1.0000,0.0188,0.4008,0,-1.000,-1.000

In [34]:
# schema = {

#     key: type(value).__name__

#     for key, value in bronze_meta_data.items()

# }

# print(schema.keys())

In [35]:
# for c in silver_event_data.columns:
#     print(c)

Store tracking data in parquet

In [5]:
# silver_tracking_data.to_parquet(
#     "../../data/silver_tracking_data.parquet",
#     engine="pyarrow",
#     index=False,
# )

Store meta data in parquet

In [ ]:
# silver_meta_data.to_parquet(
#     "../../data/silver_meta_data.parquet",
#     engine="pyarrow",
#     index=False,
# )