In [1]:
# imports
import pandas as pd
import requests
import numpy as np
import json

from data_ingestor_github import SkillCornerDataIngestor
di = SkillCornerDataIngestor()

In [2]:
# # To load all the data
# data = di.load_data(match_id=1886347)

In [3]:
# # To view the loaded data
# with open (f"../../data/gold_tracking_data.json", "r") as f:
#     gold_tracking_data = json.load(f)

# frames = gold_tracking_data['frames']

In [4]:
# start=1000
# end=1050
# filtered_frames = {frame_num: frames[str(frame_num)] for frame_num in range(start, end + 1) if str(frame_num) in frames}
# filtered_frames

In [5]:
# To view tracking data at different stages of the pipeline
bronze_tracking_data = di._get_bronze_tracking_data(match_id=1899585)
silver_tracking_data = di._get_silver_tracking_data(bronze_tracking_data)
bronze_meta_data = di._get_bronze_meta_data(match_id=1899585)
silver_meta_data = di._get_silver_meta_data(bronze_meta_data)
bronze_event_data = di._get_bronze_event_data(match_id=1899585)
silver_event_data = di._get_silver_event_data(bronze_event_data)
gold_data = di._get_gold_tracking_data(silver_tracking_data, silver_meta_data, silver_event_data)

/Users/mihirthalanki/Documents/MT/Hackathon/PlayTactix/backend/services/data_ingestor_github.py:254: DtypeWarning: Columns (276) have mixed types. Specify dtype option on import or set low_memory=False.
  raw_data = pd.read_csv(event_data_github_url)

In [6]:
silver_groups = {
            int(frame_number): group
            for frame_number, group in silver_tracking_data.groupby("frame")
        }
min_frame = int(silver_tracking_data["frame"].min())
max_frame = int(silver_tracking_data["frame"].max())
for frame_number in range(min_frame, max_frame + 1):
    group = silver_groups.get(frame_number)
    if group is None or group.empty:
        print(f"No data for frame {frame_number}")

No data for frame 364
No data for frame 365
No data for frame 366
No data for frame 367
No data for frame 368
No data for frame 369
No data for frame 370
No data for frame 371
No data for frame 372
No data for frame 373
No data for frame 374
No data for frame 375
No data for frame 376
No data for frame 377
No data for frame 378
No data for frame 379
No data for frame 380
No data for frame 381
No data for frame 382
No data for frame 383
No data for frame 384
No data for frame 385
No data for frame 386
No data for frame 387
No data for frame 388
No data for frame 389
No data for frame 390
No data for frame 391
No data for frame 392
No data for frame 393
No data for frame 394
No data for frame 395
No data for frame 396
No data for frame 397
No data for frame 398
No data for frame 399
No data for frame 400
No data for frame 401
No data for frame 402
No data for frame 403
No data for frame 404
No data for frame 405
No data for frame 406
No data for frame 407
No data for frame 408
No data for frame 409
No data for frame 410
No data for frame 411
No data for frame 412
No data for frame 413
No data for frame 414
No data for frame 415
No data for frame 416
No data for frame 417
No data for frame 418
No data for frame 419
No data for frame 420
No data for frame 421
No data for frame 422
No data for frame 423
No data for frame 424
No data for frame 425
No data for frame 426
No data for frame 427
No data for frame 428
No data for frame 429
No data for frame 430
No data for frame 431
No data for frame 432
No data for frame 433
No data for frame 434
No data for frame 435
No data for frame 436
No data for frame 437
No data for frame 438
No data for frame 439
No data for frame 440
No data for frame 441
No data for frame 442
No data for frame 443
No data for frame 444
No data for frame 445
No data for frame 446
No data for frame 447
No data for frame 448
No data for frame 449
No data for frame 450
No data for frame 451
No data for frame 452
No data for frame 453
No data for frame 454
No data for frame 455
No data for frame 456
No data for frame 457
No data for frame 458
No data for frame 459
No data for frame 460
No data for frame 461
No data for frame 462
No data for frame 463
No data for frame 464
No data for frame 465
No data for frame 466
No data for frame 467
No data for frame 468
No data for frame 469
No data for frame 470
No data for frame 471
No data for frame 472
No data for frame 473
No data for frame 474
No data for frame 475
No data for frame 476
No data for frame 477
No data for frame 478
No data for frame 479
No data for frame 480
No data for frame 481
No data for frame 482
No data for frame 483
No data for frame 484
No data for frame 485
No data for frame 486
No data for frame 487
No data for frame 488
No data for frame 489
No data for frame 490
No data for frame 491
No data for frame 492
No data for frame 493
No data for frame 494
No data for frame 495
No data for frame 496
No data for frame 497
No data for frame 498
No data for frame 499
No data for frame 500
No data for frame 501
No data for frame 502
No data for frame 503
No data for frame 504
No data for frame 505
No data for frame 506
No data for frame 507
No data for frame 508
No data for frame 509
No data for frame 510
No data for frame 511
No data for frame 512
No data for frame 513
No data for frame 514
No data for frame 515
No data for frame 516
No data for frame 517
No data for frame 518
No data for frame 519
No data for frame 520
No data for frame 521
No data for frame 522
No data for frame 523
No data for frame 524
No data for frame 525
No data for frame 526
No data for frame 527
No data for frame 528
No data for frame 529
No data for frame 530
No data for frame 531
No data for frame 532
No data for frame 533
No data for frame 534
No data for frame 535
No data for frame 536
No data for frame 537
No data for frame 538
No data for frame 539
No data for frame 540
No data for frame 541
No data for frame 542
No data for frame 543
No data for frame 544
No data for frame 545
No data for frame 546
No data for frame 547
No data for frame 548
No data for frame 549
No data for frame 550
No data for frame 551
No data for frame 552
No data for frame 553
No data for frame 554
No data for frame 555
No data for frame 556
No data for frame 557
No data for frame 558
No data for frame 559
No data for frame 560
No data for frame 561
No data for frame 562
No data for frame 563
No data for frame 564
No data for frame 565
No data for frame 566
No data for frame 567
No data for frame 568
No data for frame 569
No data for frame 570
No data for frame 571
No data for frame 572
No data for frame 573
No data for frame 574
No data for frame 575
No data for frame 576
No data for frame 577
No data for frame 578
No data for frame 579
No data for frame 580
No data for frame 581
No data for frame 582
No data for frame 583
No data for frame 584
No data for frame 585
No data for frame 586
No data for frame 587
No data for frame 588
No data for frame 589
No data for frame 590
No data for frame 591
No data for frame 592
No data for frame 593
No data for frame 594
No data for frame 595
No data for frame 596
No data for frame 597
No data for frame 598
No data for frame 599
No data for frame 600
No data for frame 601
No data for frame 602
No data for frame 603
No data for frame 604
No data for frame 605
No data for frame 606
No data for frame 607
No data for frame 608
No data for frame 609
No data for frame 610
No data for frame 611
No data for frame 612
No data for frame 613
No data for frame 614
No data for frame 615
No data for frame 616
No data for frame 617
No data for frame 618
No data for frame 619
No data for frame 620
No data for frame 621
No data for frame 622
No data for frame 623
No data for frame 624
No data for frame 625
No data for frame 626
No data for frame 627
No data for frame 628
No data for frame 629
No data for frame 630
No data for frame 631
No data for frame 632
No data for frame 633
No data for frame 634
No data for frame 635
No data for frame 636
No data for frame 637
No data for frame 638
No data for frame 639
No data for frame 640
No data for frame 641
No data for frame 642
No data for frame 643
No data for frame 644
No data for frame 645
No data for frame 646
No data for frame 647
No data for frame 648
No data for frame 649
No data for frame 650
No data for frame 651
No data for frame 652
No data for frame 653
No data for frame 654
No data for frame 655
No data for frame 656
No data for frame 657
No data for frame 658
No data for frame 659
No data for frame 660
No data for frame 661
No data for frame 662
No data for frame 663
No data for frame 664
No data for frame 665
No data for frame 666
No data for frame 667
No data for frame 668
No data for frame 669
No data for frame 670
No data for frame 671
No data for frame 672
No data for frame 673
No data for frame 674
No data for frame 675
No data for frame 676
No data for frame 677
No data for frame 678
No data for frame 679
No data for frame 680
No data for frame 681
No data for frame 682
No data for frame 683
No data for frame 684
No data for frame 685
No data for frame 686
No data for frame 687
No data for frame 688
No data for frame 689
No data for frame 690
No data for frame 691
No data for frame 692
No data for frame 693
No data for frame 694
No data for frame 695
No data for frame 696
No data for frame 1879
No data for frame 1880
No data for frame 1881
No data for frame 1882
No data for frame 1883
No data for frame 1884
No data for frame 1885
No data for frame 1886
No data for frame 1887
No data for frame 1888
No data for frame 1889
No data for frame 1890
No data for frame 1891
No data for frame 1892
No data for frame 1893
No data for frame 1894
No data for frame 1895
No data for frame 1896
No data for frame 1897
No data for frame 1898
No data for frame 1899
No data for frame 1900
No data for frame 1901
No data for frame 1902
No data for frame 1903
No data for frame 1904
No data for frame 1905
No data for frame 1906
No data for frame 1907
No data for frame 1908
No data for frame 1909
No data for frame 1910
No data for frame 1911
No data for frame 1912
No data for frame 1913
No data for frame 1914
No data for frame 1915
No data for frame 1916
No data for frame 1917
No data for frame 1918
No data for frame 1919
No data for frame 1920
No data for frame 1921
No data for frame 1922
No data for frame 1923
No data for frame 1924
No data for frame 1925
No data for frame 1926
No data for frame 1927
No data for frame 1928
No data for frame 1929
No data for frame 1930
No data for frame 1931
No data for frame 1932
No data for frame 1933
No data for frame 1934
No data for frame 1935
No data for frame 1936
No data for frame 1937
No data for frame 1938
No data for frame 1939
No data for frame 1940
No data for frame 1941
No data for frame 1942
No data for frame 1943
No data for frame 1944
No data for frame 1945
No data for frame 1946
No data for frame 1947
No data for frame 1948
No data for frame 1949
No data for frame 1950
No data for frame 1951
No data for frame 1952
No data for frame 1953
No data for frame 1954
No data for frame 1955
No data for frame 1956
No data for frame 1957
No data for frame 1958
No data for frame 1959
No data for frame 1960
No data for frame 1961
No data for frame 1962
No data for frame 1963
No data for frame 1964
No data for frame 1965
No data for frame 1966
No data for frame 1967
No data for frame 1968
No data for frame 1969
No data for frame 1970
No data for frame 1971
No data for frame 1972
No data for frame 1973
No data for frame 1974
No data for frame 1975
No data for frame 1976
No data for frame 1977
No data for frame 1978
No data for frame 1979
No data for frame 1980
No data for frame 1981
No data for frame 1982
No data for frame 1983
No data for frame 1984
No data for frame 1985
No data for frame 1986
No data for frame 1987
No data for frame 1988
No data for frame 1989
No data for frame 1990
No data for frame 1991
No data for frame 1992
No data for frame 1993
No data for frame 1994
No data for frame 1995
No data for frame 1996
No data for frame 1997
No data for frame 1998
No data for frame 1999
No data for frame 2000
No data for frame 2001
No data for frame 2002
No data for frame 2003
No data for frame 2004
No data for frame 2005
No data for frame 2006
No data for frame 2007
No data for frame 2008
No data for frame 2009
No data for frame 2010
No data for frame 2011
No data for frame 2012
No data for frame 2013
No data for frame 2014
No data for frame 2015
No data for frame 2016
No data for frame 2017
No data for frame 2018
No data for frame 2019
No data for frame 2020
No data for frame 2021
No data for frame 2022
No data for frame 2023
No data for frame 2024
No data for frame 2025
No data for frame 2026
No data for frame 2027
No data for frame 2028
No data for frame 2029
No data for frame 2030
No data for frame 2031
No data for frame 2032
No data for frame 2033
No data for frame 2034
No data for frame 2035
No data for frame 2036
No data for frame 2037
No data for frame 2038
No data for frame 2039
No data for frame 2040
No data for frame 2041
No data for frame 2042
No data for frame 2043
No data for frame 2044
No data for frame 2045
No data for frame 2546
No data for frame 2547
No data for frame 2548
No data for frame 2549
No data for frame 2550
No data for frame 2551
No data for frame 2552
No data for frame 2553
No data for frame 2554
No data for frame 2555
No data for frame 2556
No data for frame 2557
No data for frame 2558
No data for frame 2559
No data for frame 2560
No data for frame 2561
No data for frame 2562
No data for frame 2563
No data for frame 2564
No data for frame 2565
No data for frame 2566
No data for frame 2567
No data for frame 2568
No data for frame 2569
No data for frame 2570
No data for frame 2571
No data for frame 2572
No data for frame 2573
No data for frame 2574
No data for frame 2575
No data for frame 2576
No data for frame 2577
No data for frame 2578
No data for frame 2579
No data for frame 2580
No data for frame 2581
No data for frame 2582
No data for frame 2583
No data for frame 2584
No data for frame 2585
No data for frame 2586
No data for frame 2587
No data for frame 2588
No data for frame 2589
No data for frame 2590
No data for frame 2591
No data for frame 2592
No data for frame 2593
No data for frame 2594
No data for frame 2595
No data for frame 2596
No data for frame 2597
No data for frame 2598
No data for frame 2599
No data for frame 2600
No data for frame 2601
No data for frame 2602
No data for frame 2603
No data for frame 2604
No data for frame 2605
No data for frame 2606
No data for frame 2607
No data for frame 2608
No data for frame 2609
No data for frame 2610
No data for frame 2611
No data for frame 2612
No data for frame 2613
No data for frame 2614
No data for frame 2615
No data for frame 2616
No data for frame 2617
No data for frame 2618
No data for frame 2619
No data for frame 2620
No data for frame 2621
No data for frame 2622
No data for frame 2623
No data for frame 2624
No data for frame 2625
No data for frame 2626
No data for frame 2627
No data for frame 2628
No data for frame 2629
No data for frame 2630
No data for frame 2631
No data for frame 2632
No data for frame 2633
No data for frame 2634
No data for frame 2635
No data for frame 2636
No data for frame 2637
No data for frame 2638
No data for frame 2639
No data for frame 2640
No data for frame 2641
No data for frame 2642
No data for frame 2643
No data for frame 2644
No data for frame 2645
No data for frame 2646
No data for frame 2647
No data for frame 2648
No data for frame 2649
No data for frame 2650
No data for frame 2651
No data for frame 2652
No data for frame 2653
No data for frame 2654
No data for frame 2655
No data for frame 2656
No data for frame 2657
No data for frame 2658
No data for frame 2659
No data for frame 2660
No data for frame 2661
No data for frame 2662
No data for frame 2663
No data for frame 2664
No data for frame 2665
No data for frame 2666
No data for frame 2667
No data for frame 2668
No data for frame 2669
No data for frame 2670
No data for frame 2671
No data for frame 2672
No data for frame 2673
No data for frame 2674
No data for frame 2675
No data for frame 2676
No data for frame 2677
No data for frame 2678
No data for frame 2679
No data for frame 2680
No data for frame 2681
No data for frame 2682
No data for frame 2683
No data for frame 2684
No data for frame 2685
No data for frame 2686
No data for frame 2687
No data for frame 2688
No data for frame 2689
No data for frame 2690
No data for frame 2691
No data for frame 2692
No data for frame 2693
No data for frame 2694
No data for frame 2695
No data for frame 2696
No data for frame 2697
No data for frame 2698
No data for frame 4306
No data for frame 4307
No data for frame 4308
No data for frame 4309
No data for frame 4310
No data for frame 4311
No data for frame 4312
No data for frame 4313
No data for frame 4314
No data for frame 4315
No data for frame 4316
No data for frame 4317
No data for frame 4318
No data for frame 4319
No data for frame 4320
No data for frame 4321
No data for frame 4322
No data for frame 4323
No data for frame 4324
No data for frame 4325
No data for frame 4326
No data for frame 4327
No data for frame 4328
No data for frame 4329
No data for frame 4330
No data for frame 4331
No data for frame 4332
No data for frame 4333
No data for frame 4334
No data for frame 4335
No data for frame 4336
No data for frame 4337
No data for frame 4338
No data for frame 4339
No data for frame 4340
No data for frame 4341
No data for frame 4342
No data for frame 4343
No data for frame 4344
No data for frame 4345
No data for frame 4346
No data for frame 4347
No data for frame 4348
No data for frame 4349
No data for frame 4350
No data for frame 4351
No data for frame 4352
No data for frame 4353
No data for frame 4354
No data for frame 4355
No data for frame 4356
No data for frame 4357
No data for frame 4358
No data for frame 4359
No data for frame 4360
No data for frame 4361
No data for frame 4362
No data for frame 4363
No data for frame 4364
No data for frame 4365
No data for frame 4366
No data for frame 4367
No data for frame 4368
No data for frame 4369
No data for frame 4370
No data for frame 4371
No data for frame 4372
No data for frame 4373
No data for frame 4374
No data for frame 4375
No data for frame 4376
No data for frame 4377
No data for frame 4378
No data for frame 4379
No data for frame 4380
No data for frame 4381
No data for frame 4382
No data for frame 4383
No data for frame 4384
No data for frame 4385
No data for frame 4386
No data for frame 4387
No data for frame 4388
No data for frame 4389
No data for frame 4390
No data for frame 4391
No data for frame 4392
No data for frame 4393
No data for frame 4394
No data for frame 4395
No data for frame 4396
No data for frame 4397
No data for frame 4398
No data for frame 4399
No data for frame 4400
No data for frame 4401
No data for frame 4402
No data for frame 4403
No data for frame 4404
No data for frame 4405
No data for frame 4406
No data for frame 4407
No data for frame 4408
No data for frame 4409
No data for frame 4410
No data for frame 4411
No data for frame 4412
No data for frame 4413
No data for frame 4414
No data for frame 4415
No data for frame 4416
No data for frame 4417
No data for frame 4418
No data for frame 4419
No data for frame 4420
No data for frame 4421
No data for frame 4422
No data for frame 4423
No data for frame 4424
No data for frame 4425
No data for frame 4426
No data for frame 4427
No data for frame 4428
No data for frame 4429
No data for frame 4430
No data for frame 4431
No data for frame 4432
No data for frame 4433
No data for frame 4434
No data for frame 4435
No data for frame 4436
No data for frame 4437
No data for frame 4438
No data for frame 4439
No data for frame 4440
No data for frame 4441
No data for frame 4442
No data for frame 4443
No data for frame 4444
No data for frame 4445
No data for frame 4446
No data for frame 4447
No data for frame 4448
No data for frame 4449
No data for frame 4450
No data for frame 4451
No data for frame 4452
No data for frame 4453
No data for frame 4454
No data for frame 4455
No data for frame 4456
No data for frame 4457
No data for frame 4458
No data for frame 4459
No data for frame 4460
No data for frame 4461
No data for frame 4462
No data for frame 4463
No data for frame 4464
No data for frame 6569
No data for frame 6570
No data for frame 6571
No data for frame 6572
No data for frame 6573
No data for frame 6574
No data for frame 6575
No data for frame 6576
No data for frame 6577
No data for frame 6578
No data for frame 6579
No data for frame 6580
No data for frame 6581
No data for frame 6582
No data for frame 6583
No data for frame 6584
No data for frame 6585
No data for frame 6586
No data for frame 6587
No data for frame 6588
No data for frame 6589
No data for frame 6590
No data for frame 6591
No data for frame 6592
No data for frame 6593
No data for frame 6594
No data for frame 6595
No data for frame 6596
No data for frame 6597
No data for frame 6598
No data for frame 6599
No data for frame 6600
No data for frame 6601
No data for frame 6602
No data for frame 6603
No data for frame 6604
No data for frame 6605
No data for frame 6606
No data for frame 6607
No data for frame 6608
No data for frame 6609
No data for frame 6610
No data for frame 6611
No data for frame 6612
No data for frame 6613
No data for frame 6614
No data for frame 6615
No data for frame 6616
No data for frame 6617
No data for frame 6618
No data for frame 6619
No data for frame 6620
No data for frame 6621
No data for frame 6622
No data for frame 6623
No data for frame 6624
No data for frame 6625
No data for frame 6626
No data for frame 6627
No data for frame 6628
No data for frame 6629
No data for frame 6630
No data for frame 6631
No data for frame 6632
No data for frame 6633
No data for frame 6634
No data for frame 6635
No data for frame 6636
No data for frame 6637
No data for frame 6638
No data for frame 6639
No data for frame 6640

In [9]:
gold_data[51710]

{'period': None,
 'players': {'x': [],
  'y': [],
  'player_id': [],
  'id': [],
  'short_name': [],
  'number': [],
  'team_id': [],
  'total_time': [],
  'player_role.name': [],
  'player_role.acronym': [],
  'is_gk': [],
  'direction_player_1st_half': [],
  'direction_player_2nd_half': []},
 'ball': {'ball_x': None, 'ball_y': None, 'ball_z': None},
 'events': []}

In [15]:
group = silver_groups.get(51866)
group

,x,y,player_id,is_detected,frame,timestamp,period,possession_player_id,possession_group,ball_x,ball_y,ball_z,is_detected_ball
767052,-39.88,-4.04,285188,False,51866,2026-05-15 01:21:49.600,2.0,NaN,home team,-6.92,-18.63,0.0,True
767053,-17.30,-12.78,31147,True,51866,2026-05-15 01:21:49.600,2.0,NaN,home team,-6.92,-18.63,0.0,True
767054,-7.93,-22.07,51667,True,51866,2026-05-15 01:21:49.600,2.0,NaN,home team,-6.92,-18.63,0.0,True
767055,-12.55,-1.85,33697,True,51866,2026-05-15 01:21:49.600,2.0,NaN,home team,-6.92,-18.63,0.0,True
767056,11.74,-31.65,4322,False,51866,2026-05-15 01:21:49.600,2.0,NaN,home team,-6.92,-18.63,0.0,True
767057,-3.24,12.40,133498,True,51866,2026-05-15 01:21:49.600,2.0,NaN,home team,-6.92,-18.63,0.0,True
767058,2.74,-20.78,23418,True,51866,2026-05-15 01:21:49.600,2.0,NaN,home team,-6.92,-18.63,0.0,True
767059,1.35,-20.60,133495,True,51866,2026-05-15 01:21:49.600,2.0,NaN,home team,-6.92,-18.63,0.0,True
767060,16.04,-27.03,965684,False,51866,2026-05-15 01:21:49.600,2.0,NaN,home team,-6.92,-18.63,0.0,True
767061,17.73,-5.24,43829,False,51866,2026-05-15 01:21:49.600,2.0,NaN,home team,-6.92,-18.63,0.0,True
767062,21.00,-15.48,38673,False,51866,2026-05-15 01:21:49.600,2.0,NaN,home team,-6.92,-18.63,0.0,True
767063,41.41,-0.64,34718,False,51866,2026-05-15 01:21:49.600,2.0,NaN,home team,-6.92,-18.63,0.0,True
767064,19.12,-5.42,698137,False,51866,2026-05-15 01:21:49.600,2.0,NaN,home team,-6.92,-18.63,0.0,True
767065,18.38,7.86,799092,False,51866,2026-05-15 01:21:49.600,2.0,NaN,home team,-6.92,-18.63,0.0,True
767066,18.88,-15.69,42510,False,51866,2026-05-15 01:21:49.600,2.0,NaN,home team,-6.92,-18.63,0.0,True
767067,-0.82,-5.51,26969,True,51866,2026-05-15 01:21:49.600,2.0,NaN,home team,-6.92,-18.63,0.0,True
767068,14.98,-27.96,51028,False,51866,2026-05-15 01:21:49.600,2.0,NaN,home team,-6.92,-18.63,0.0,True
767069,-6.29,-18.75,51015,True,51866,2026-05-15 01:21:49.600,2.0,NaN,home team,-6.92,-18.63,0.0,True
767070,-5.04,5.94,799091,True,51866,2026-05-15 01:21:49.600,2.0,NaN,home team,-6.92,-18.63,0.0,True
767071,-13.52,-10.11,23909,True,51866,2026-05-15 01:21:49.600,2.0,NaN,home team,-6.92,-18.63,0.0,True
767072,5.20,-27.99,159938,False,51866,2026-05-15 01:21:49.600,2.0,NaN,home team,-6.92,-18.63,0.0,True
767073,-3.32,-23.77,6799,True,51866,2026-05-15 01:21:49.600,2.0,NaN,home team,-6.92,-18.63,0.0,True

In [11]:
silver_tracking_data[silver_tracking_data['frame'] == 51710]

Empty DataFrame
Columns: [x, y, player_id, is_detected, frame, timestamp, period, possession_player_id, possession_group, ball_x, ball_y, ball_z, is_detected_ball]
Index: []

In [12]:
bronze_tracking_data[bronze_tracking_data['frame'] == 51710]

,frame,timestamp,period,ball_data,possession,image_corners_projection,player_data
51710,51710,2026-05-15 01:21:34,2.0,"{'x': None, 'y': None, 'z': None, 'is_detected...","{'player_id': None, 'group': None}","{'x_top_left': None, 'y_top_left': None, 'x_bo...",[]

In [17]:
bronze_tracking_data[bronze_tracking_data['frame'] == 100]

,frame,timestamp,period,ball_data,possession,image_corners_projection,player_data
100,100,2026-05-14 00:00:09,1.0,"{'x': -7.36, 'y': 15.36, 'z': 0.13, 'is_detect...","{'player_id': None, 'group': 'away team'}","{'x_top_left': -37.05, 'y_top_left': 39.0, 'x_...","[{'x': -40.96, 'y': 2.85, 'player_id': 34718, ..."

In [22]:
bronze_tracking_data[bronze_tracking_data["player_data"].apply(len) == 0]

,frame,timestamp,period,ball_data,possession,image_corners_projection,player_data
0,0,NaT,NaN,"{'x': None, 'y': None, 'z': None, 'is_detected...","{'player_id': None, 'group': None}","{'x_top_left': None, 'y_top_left': None, 'x_bo...",[]
1,1,NaT,NaN,"{'x': None, 'y': None, 'z': None, 'is_detected...","{'player_id': None, 'group': None}","{'x_top_left': None, 'y_top_left': None, 'x_bo...",[]
2,2,NaT,NaN,"{'x': None, 'y': None, 'z': None, 'is_detected...","{'player_id': None, 'group': None}","{'x_top_left': None, 'y_top_left': None, 'x_bo...",[]
3,3,NaT,NaN,"{'x': None, 'y': None, 'z': None, 'is_detected...","{'player_id': None, 'group': None}","{'x_top_left': None, 'y_top_left': None, 'x_bo...",[]
4,4,NaT,NaN,"{'x': None, 'y': None, 'z': None, 'is_detected...","{'player_id': None, 'group': None}","{'x_top_left': None, 'y_top_left': None, 'x_bo...",[]
...,...,...,...,...,...,...,...
60525,60525,2026-05-14 01:36:15.500,2.0,"{'x': None, 'y': None, 'z': None, 'is_detected...","{'player_id': None, 'group': None}","{'x_top_left': None, 'y_top_left': None, 'x_bo...",[]
60526,60526,2026-05-14 01:36:15.600,2.0,"{'x': None, 'y': None, 'z': None, 'is_detected...","{'player_id': None, 'group': None}","{'x_top_left': None, 'y_top_left': None, 'x_bo...",[]
60527,60527,2026-05-14 01:36:15.700,2.0,"{'x': None, 'y': None, 'z': None, 'is_detected...","{'player_id': None, 'group': None}","{'x_top_left': None, 'y_top_left': None, 'x_bo...",[]
60528,60528,2026-05-14 01:36:15.800,2.0,"{'x': None, 'y': None, 'z': None, 'is_detected...","{'player_id': None, 'group': None}","{'x_top_left': None, 'y_top_left': None, 'x_bo...",[]
60529,60529,2026-05-14 01:36:15.900,2.0,"{'x': None, 'y': None, 'z': None, 'is_detected...","{'player_id': None, 'group': None}","{'x_top_left': None, 'y_top_left': None, 'x_bo...",[]

In [13]:
bronze_tracking_data[bronze_tracking_data['frame'] == 51859]

,frame,timestamp,period,ball_data,possession,image_corners_projection,player_data
51859,51859,2026-05-15 01:21:48.900,2.0,"{'x': -2.25, 'y': -20.77, 'z': 0.04, 'is_detec...","{'player_id': None, 'group': 'home team'}","{'x_top_left': -24.87, 'y_top_left': 34.79, 'x...","[{'x': -37.79, 'y': -4.67, 'player_id': 285188..."

In [15]:
silver_tracking_data[silver_tracking_data['frame'] == 44558]

Empty DataFrame
Columns: [x, y, player_id, is_detected, frame, timestamp, period, possession_player_id, possession_group, ball_x, ball_y, ball_z, is_detected_ball]
Index: []

In [12]:
import pandas as pd
pd.set_option('display.max_columns', None)  # Show all columns
bronze_event_data[bronze_event_data['first_line_break'] == True].head()

,event_id,index,match_id,frame_start,frame_end,frame_physical_start,time_start,time_end,minute_start,second_start,duration,period,attacking_side_id,attacking_side,event_type_id,event_type,event_subtype_id,event_subtype,player_id,player_name,player_position_id,player_position,player_in_possession_id,player_in_possession_name,player_in_possession_position_id,player_in_possession_position,team_id,team_shortname,x_start,y_start,channel_id_start,channel_start,third_id_start,third_start,penalty_area_start,x_end,y_end,channel_id_end,channel_end,third_id_end,third_end,penalty_area_end,associated_player_possession_event_id,associated_player_possession_frame_start,associated_player_possession_frame_end,associated_player_possession_end_type_id,associated_player_possession_end_type,associated_off_ball_run_event_id,associated_off_ball_run_subtype_id,associated_off_ball_run_subtype,game_state_id,game_state,team_score,opponent_team_score,phase_index,player_possession_phase_index,first_player_possession_in_team_possession,last_player_possession_in_team_possession,lead_to_different_phase,issued_from_different_phase,n_player_possessions_in_phase,team_possession_loss_in_phase,team_in_possession_phase_type_id,team_in_possession_phase_type,team_out_of_possession_phase_type_id,team_out_of_possession_phase_type,current_team_in_possession_next_phase_type_id,current_team_in_possession_next_phase_type,current_team_out_of_possession_next_phase_type_id,current_team_out_of_possession_next_phase_type,current_team_in_possession_previous_phase_type_id,current_team_in_possession_previous_phase_type,current_team_out_of_possession_previous_phase_type_id,current_team_out_of_possession_previous_phase_type,game_interruption_before_id,game_interruption_before,game_interruption_after_id,game_interruption_after,lead_to_shot,lead_to_goal,distance_covered,trajectory_angle,trajectory_direction_id,trajectory_direction,in_to_out,out_to_in,speed_avg,speed_avg_band_id,speed_avg_band,separation_start,separation_end,separation_gain,last_defensive_line_x_start,last_defensive_line_x_end,delta_to_last_defensive_line_start,delta_to_last_defensive_line_end,delta_to_last_defensive_line_gain,last_defensive_line_height_start,last_defensive_line_height_end,last_defensive_line_height_gain,inside_defensive_shape_start,inside_defensive_shape_end,start_type_id,start_type,end_type_id,end_type,consecutive_on_ball_engagements,one_touch,quick_pass,carry,forward_momentum,is_header,hand_pass,initiate_give_and_go,pass_angle_received,pass_direction_received_id,pass_direction_received,pass_distance_received,pass_range_received_id,pass_range_received,pass_outcome_id,pass_outcome,targeted_passing_option_event_id,high_pass,player_targeted_id,player_targeted_name,player_targeted_position_id,player_targeted_position,player_targeted_x_pass,player_targeted_y_pass,player_targeted_channel_pass_id,player_targeted_channel_pass,player_targeted_third_pass_id,player_targeted_third_pass,player_targeted_penalty_area_pass,player_targeted_x_reception,player_targeted_y_reception,player_targeted_channel_reception_id,player_targeted_channel_reception,player_targeted_third_reception_id,player_targeted_third_reception,player_targeted_penalty_area_reception,player_targeted_distance_to_goal_start,player_targeted_distance_to_goal_end,player_targeted_angle_to_goal_start,player_targeted_angle_to_goal_end,player_targeted_average_speed,player_targeted_speed_avg_band_id,player_targeted_speed_avg_band,speed_difference,player_targeted_xpass_completion,player_targeted_difficult_pass_target,player_targeted_xthreat,player_targeted_dangerous,n_passing_options,n_off_ball_runs,n_passing_options_line_break,n_passing_options_first_line_break,n_passing_options_second_last_line_break,n_passing_options_last_line_break,n_passing_options_ahead,n_passing_options_dangerous_difficult,n_passing_options_dangerous_not_difficult,n_passing_options_not_dangerous_not_difficult,n_passing_options_not_dangerous_difficult,n_passing_options_at_start,n_passing_options_at_end,n_passing_options_ahead_at_start,n_passing_options_ahead_at_end,n_teammates_ahead_end,n_teammates_ahead_start,n_player_targeted_opponents_ahead_start,n_player_targeted_opponents_ahead_end,n_player_targeted_teammates_ahead_start,n_player_targeted_teammates_ahead_end,n_player_targeted_teammates_within_5m_start,n_player_targeted_teammates_within_5m_end,n_player_targeted_opponents_within_5m_start,n_player_targeted_opponents_within_5m_end,organised_defense,defensive_structure,n_defensive_lines,first_line_break,first_line_break_type_id,first_line_break_type,second_last_line_break,second_last_line_break_type_id,second_last_line_break_type,last_line_break,last_line_break_type_id,last_line_break_type,furthest_line_break_id,furthest_line_break,furthest_line_break_type_id,furthest_line_break_type,interplayer_distance,interplayer_distance_range_id,interplayer_distance_range,interplayer_distance_start,interplayer_distance_end,interplayer_distance_min,interplayer_distance_start_physical,close_at_player_possession_start,interplayer_angle,interplayer_direction_id,interplayer_direction,angle_of_engagement,goal_side_start,goal_side_end,pass_distance,pass_range_id,pass_range,pass_angle,pass_direction_id,pass_direction,pass_ahead,n_opponents_ahead_player_in_possession_pass_moment,n_opponents_ahead_pass_reception,n_opponents_bypassed,location_to_player_in_possession_id_start,location_to_player_in_possession_start,location_to_player_in_possession_id_end,location_to_player_in_possession_end,distance_to_player_in_possession_start,distance_to_player_in_possession_end,player_in_possession_x_start,player_in_possession_y_start,player_in_possession_channel_id_start,player_in_possession_channel_start,player_in_possession_third_id_start,player_in_possession_third_start,player_in_possession_penalty_area_start,player_in_possession_x_end,player_in_possession_y_end,player_in_possession_channel_id_end,player_in_possession_channel_end,player_in_possession_third_id_end,player_in_possession_third_end,player_in_possession_penalty_area_end,targeted,received,received_in_space,dangerous,difficult_pass_target,xthreat,xpass_completion,passing_option_score,predicted_passing_option,peak_passing_option_frame,passing_option_at_player_possession_start,n_simultaneous_runs,give_and_go,intended_run_behind,push_defensive_line,break_defensive_line,passing_option_at_start,n_simultaneous_passing_options,passing_option_at_pass_moment,n_opponents_ahead_end,n_opponents_ahead_start,n_opponents_overtaken,pressing_chain,pressing_chain_length,pressing_chain_end_type_id,pressing_chain_end_type,pressing_chain_index,index_in_pressing_chain,simultaneous_defensive_engagement_same_target,simultaneous_defensive_engagement_same_target_rank,affected_line_breaking_passing_option_id,affected_line_break_id,affected_line_break,affected_line_breaking_passing_option_attempted,affected_line_breaking_passing_option_xthreat,affected_line_breaking_passing_option_dangerous,affected_line_breaking_passing_option_run_subtype_id,affected_line_breaking_passing_option_run_subtype,possession_danger,beaten_by_possession,beaten_by_movement,stop_possession_danger,reduce_possession_danger,force_backward,xloss_player_possession_start,xloss_player_possession_end,xloss_player_possession_max,xshot_player_possession_start,xshot_player_possession_end,xshot_player_possession_max,is_player_possession_start_matched,is_player_possession_end_matched,is_previous_pass_matched,is_pass_reception_matched,fully_extrapolated
153,7_73,153,1899585,1615,1616,NaN,02:40.5,02:40.6,2,40,0.1,1,2,right_to_left,7,passing_option,NaN,NaN,23418,F. Gallegos,12,LM,51667.0,D. Hall,6.0,RCB,4177,Auckland FC,14.49,26.41,1,wide_left,2,middle_third,False,14.12,26.32,1,wide_left,2,middle_third,False,8_33,1615.0,NaN,NaN,NaN,NaN,NaN,NaN,3,drawing,0,0,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,create,9,medium_block,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,1.57,-167.54,2.0,backward,False,False,14.02,1.0,jogging,7.46,7.66,0.20,34.08,33.72,19.59,19.60,0.01,17.92,18.28,0.36,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,424.0,3.0,True,1.0,through,False,NaN,NaN,False,NaN,NaN,1.0,first,1.0,through,14.81,1.0,short,NaN,NaN,NaN,NaN,NaN,32.01,1.0,forward,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,10.0,7.0,3.0,3.0,ahead,3.0,ahead,18.74,18.53,-2.80,19.17,2.0,half_space_left,2.0,middle_third,False,-2.90,19.00,2.0,half_space_left,2.0,middle_third,False,False,False,NaN,False,False,0.0018,0.9554,0.7655,True,1647.0,True,NaN,NaN,NaN,NaN,NaN,NaN,2.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,False
156,7_76,156,1899585,1642,1653,NaN,02:43.2,02:44.3,2,43,1.1,1,2,right_to_left,7,passing_option,NaN,NaN,23418,F. Gallegos,12,LM,51667.0,D. Hall,6.0,RCB,4177,Auckland FC,7.34,21.99,1,wide_left,2,middle_third,False,6.71,19.79,2,half_space_left,2,middle_third,False,8_33,1615.0,NaN,NaN,NaN,NaN,NaN,NaN,3,drawing,0,0,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,create,9,medium_block,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,2.11,-105.98,4.0,sideway_right,False,True,7.58,1.0,jogging,4.28,2.93,-1.36,26.94,25.75,19.60,19.04,-0.56,25.06,26.25,1.19,False,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,424.0,3.0,True,1.0,through,False,NaN,NaN,False,NaN,NaN,1.0,first,1.0,through,14.81,1.0,short,NaN,NaN,NaN,NaN,NaN,32.01,1.0,forward,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,10.0,7.0,3.0,3.0,ahead,3.0,ahead,15.63,14.01,-5.67,13.32,2.0,half_space_left,2.0,middle_third,False,-5.55,13.02,2.0,half_space_left,2.0,middle_third,False,False,False,NaN,False,False,0.0018,0.9554,0.7655,True,1647.0,False,NaN,NaN,NaN,NaN,NaN,NaN,3.0,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,False
158,8_34,158,1899585,1672,1684,NaN,02:46.2,02:47.4,2,46,1.2,1,2,right_to_left,8,player_possession,NaN,NaN,133498,F. De Vries,2,LB,NaN,NaN,NaN,NaN,4177,Auckland FC,5.70,32.56,1,wide_left,2,middle_third,False,8.17,32.58,1,wide_left,2,middle_third,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,drawing,0,0,18,1.0,False,False,False,True,2.0,False,2,finish,8,low_block,5.0,chaotic,5.0,chaotic,1.0,create,9.0,medium_block,NaN,NaN,NaN,NaN,False,False,2.47,0.46,1.0,forward,False,False,7.22,1.0,jogging,8.40,5.05,-3.35,26.46,27.59,20.76,19.42,-1.34,25.54,24.41,-1.13,False,False,1.0,pass_reception,1.0,pass,NaN,False,False,True,False,False,False,False,62.47,3.0,sideway_left,26.98,2.0,medium,1.0,successful,7_80,False,50951.0,J. Brimmer,19.0,CF,15.72,29.53,1.0,wide_left,2.0,middle_third,False,15.0,29.98,1.0,wide_left,2.0,middle_third,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.9567,False,0.0015,False,4.0,0.0,3.0,2.0,1.0,0.0,2.0,0.0,0.0,4.0,0.0,4.0,3.0,2.0,2.0,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,424.0,3.0,True,NaN,NaN,False,NaN,NaN,False,NaN,NaN,1.0,first,2.0,around,8.14,1.0,short,NaN,NaN,NaN,NaN,NaN,-22.00,1.0,forward,NaN,NaN,NaN,7.92,1.0,short,-24.69,1.0,forward,True,7.0,6.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,8.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,True,True,False
160,7_79,160,1899585,1672,1684,NaN,02:46.2,02:47.4,2,46,1.2,1,2,right_to_left,7,passing_option,NaN,NaN,23418,F. Gallegos,12,LM,133498.0,F. De Vries,2.0,LB,4177,Auckland FC,8.17,19.50,2,half_space_left,2,middle_third,False,10.09,22.13,1,wide_left,2,middle_third,False,8_34,1672.0,NaN,NaN,NaN,NaN,NaN,NaN,3,drawing,0,0,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,finish,8,low_block,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,3.27,53.87,3.0,sideway_left,True,False,9.76,1.0,jogging,4.91,6.08,1.17,26.46,27.59,18.29,17.50,-0.79,25.54,24.41,-1.13,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,424.0,3.0,True,1.0,through,False,NaN,NaN,False,NaN,NaN,1.0,first,1.0,through,10.62,1.0,short,NaN,NaN,NaN,NaN,NaN,-79.59,4.0,sideway_right,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,7.0,7.0,0.0,2.0,same_line,2.0,same_line,13.29,10.62,5.70,32.56,1.0,wide_left,2.0,middle_third,False,8.17,32.58,1.0,wide_left,2.0,middle_third,False,False,False,NaN,False,False,0.0028,0.9221,0.8711,True,1684.0,True,NaN,NaN,NaN,NaN,NaN,NaN,3.0,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,False
161,7_80,161,1899585,1672,1684,NaN,02:46.2,02:47.4,2,46,1.2,1,2,right_to_left,7,passing_option,NaN,NaN,50951,J. Brimmer,19,CF,133498.0,F. De Vries,2.0,LB,4177,Auckland FC,17.58,27.83,1,wide_left,3,attacking_third,False,15.72,29.53,1,wide_left,2,middle_third,False,8_34,1672.0,NaN,NaN,NaN,NaN,NaN,NaN,3,drawing,0,0,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,finish,8,low_block,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,2.53,137.57,2.0,backward,False,False,NaN,NaN,NaN,4.49,1.46,-3.03,26.46,27.59,8.88,11.87,2.99,25.54,24.41,-1.13,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,424.0,3.0,True,2.0,around,False,NaN,NaN,False,NaN,NaN,1.0,first,2.0,around,8.14,1.0,short,NaN,NaN,NaN,NaN,NaN,-22.00,1.0,forward,NaN,NaN,NaN,7.92,1.0,short,-24.69,1.0,forward,True,7.0,6.0,1.0,3.0,ahead,3.0,ahead,12.79,8.14,5.70,32.56,1.0,wide_left,2.0,middle_third,False,8.17,32.58,1.0,wide_left,2.0,middle_third,False,True,True,False,False,False,0.0015,0.9567,0.9751,True,1684.0,True,NaN,NaN,NaN,NaN,NaN,NaN,3.0,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,True,False

In [10]:
silver_event_data[silver_event_data['event_type'] == 'off_ball_run'].head()

,event_id,index,frame_start,frame_end,attacking_side,event_type_id,event_type,player_id,player_name,team_id,x_start,y_start,x_end,y_end
8,1_0,8,57,66,left_to_right,1,off_ball_run,51015,A. Rufer,867,-9.98,0.48,-10.80,4.37
18,1_1,18,88,105,left_to_right,1,off_ball_run,26969,H. Ishige,867,13.18,19.94,20.60,23.58
21,1_2,21,117,125,left_to_right,1,off_ball_run,26969,H. Ishige,867,21.70,27.53,19.77,30.39
24,1_3,24,126,163,left_to_right,1,off_ball_run,27003,K. Nagasawa,867,6.12,15.14,23.88,28.47
38,1_4,38,195,227,left_to_right,1,off_ball_run,42510,S. Wootton,867,-17.83,7.35,-35.41,0.91

In [ ]:
event_idx = 0
n_events = len(silver_event_data)
events = 
while event_idx < n_events and silver_event_data.iloc[event_idx]['frame_start'] <= frame_number:
    event = silver_event_data.iloc[event_idx]
    if event['frame_start'] <= frame_number <= event['frame_end']:
        frames[frame_number]['events'].append(event.to_dict())
                if event['frame_end'] < frame_number:
                    event_idx += 1
                else:
                    break

adding event player_possession for frame 12
adding event player_possession for frame 31
adding event passing_option for frame 31
adding event passing_option for frame 31
adding event on_ball_engagement for frame 37

In [21]:
event_set = set()
for event in events:
    event_set.add(event['event_type'])
print(event_set)

{'on_ball_engagement', 'passing_option', 'player_possession'}

In [7]:
silver_data = silver_tracking_data.merge(
            silver_meta_data, left_on=["player_id"], right_on=["id"]
        )

In [8]:
pd.set_option('display.max_columns', None)  # Show all columns

In [9]:
def build_frame_dict(tracking_data, event_data):
    frames = {}
    event_idx = 0
    n_events = len(event_data)
    for frame_number, group in tracking_data.groupby("frame"):
        # Add tracking data
        frames[frame_number] = {
                #'is_detected': group['is_detected'].iloc[0],
                #'timestamp': group['timestamp'].iloc[0],
                'period': group['period'].iloc[0],
                'players': {
                    'x': group['x'].tolist(),
                    'y': group['y'].tolist(),
                    'player_id': group['player_id'].tolist(),
                    'id': group['id'].tolist(),
                    'short_name': group['short_name'].tolist(),
                    'number': group['number'].tolist(),
                    'team_id': group['team_id'].tolist(),
                    'total_time': group['total_time'].tolist(),
                    'player_role.name': group['player_role.name'].tolist(),
                    'player_role.acronym': group['player_role.acronym'].tolist(),
                    'is_gk': group['is_gk'].tolist(),
                    'direction_player_1st_half': group['direction_player_1st_half'].tolist(),
                    'direction_player_2nd_half': group['direction_player_2nd_half'].tolist(),
                },
                'ball': {
                    'ball_x': group['ball_x'].iloc[0],
                    'ball_y': group['ball_y'].iloc[0],
                    'ball_z': group['ball_z'].iloc[0],
                    #'is_detected_ball': group['is_detected_ball'].iloc[0],
                },
                'events': []
            }
        # Add event data
        while event_idx < n_events and event_data.iloc[event_idx]['frame_start'] <= frame_number:
            event = event_data.iloc[event_idx]
            if event['frame_start'] <= frame_number <= event['frame_end']:
                frames[frame_number]['events'].append(event.to_dict())
            if event['frame_end'] < frame_number:
                event_idx += 1
            else:
                break
    
    return frames

In [10]:
gold_frames = build_frame_dict(silver_data, silver_event_data)

KeyboardInterrupt:

In [ ]:
gold_frames[58]['events']

[{'event_id': '8_1',
  'index': 1,
  'frame_start': 48,
  'frame_end': 58,
  'attacking_side': 'left_to_right',
  'event_type_id': 8,
  'event_type': 'player_possession',
  'event_subtype_id': nan,
  'event_subtype': nan,
  'player_id': 51649,
  'player_name': 'A. Šušnjar',
  'team_id': 1805,
  'x_start': -22.31,
  'y_start': 1.22,
  'x_end': -22.21,
  'y_end': 2.7}]

In [ ]:
silver_event_data.head()

,event_id,index,frame_start,frame_end,attacking_side,event_type_id,event_type,event_subtype_id,event_subtype,player_id,player_name,team_id,x_start,y_start,x_end,y_end
0,8_0,0,28,28,left_to_right,8,player_possession,NaN,NaN,966120,B. Gibson,1805,0.73,0.49,0.73,0.49
1,8_1,1,48,58,left_to_right,8,player_possession,NaN,NaN,51649,A. Šušnjar,1805,-22.31,1.22,-22.21,2.70
2,7_0,2,48,53,left_to_right,7,passing_option,NaN,NaN,735574,K. Grozos,1805,-10.47,-2.78,-11.36,-1.38
3,7_1,3,48,58,left_to_right,7,passing_option,NaN,NaN,735578,M. Natta,1805,-20.69,16.66,-20.36,17.69
4,9_0,4,56,58,right_to_left,9,on_ball_engagement,11.0,pressing,50951,J. Brimmer,4177,13.03,0.06,13.98,-0.68