In [59]:
import pandas as pd
import requests
import numpy as np
import json

pd.set_option('display.max_columns', None)  # Show all columns

from data_ingestor_github import SkillCornerDataIngestor
di = SkillCornerDataIngestor()

In [69]:
bronze_event_data = di._get_bronze_event_data(match_id=1886347)
silver_event_data = di._get_silver_event_data(bronze_event_data)

In [ ]:
# bronze_event_data[bronze_event_data['xthreat'] > 0.2].head()
bronze_event_data[bronze_event_data['force_backward'] == True][['phase_index', 'event_type', 'team_shortname', 'end_type', xloss_player_possession_start]]

      phase_index          event_type team_shortname end_type
60             10  on_ball_engagement      Newcastle      NaN
136            16  on_ball_engagement    Auckland FC      NaN
227            25  on_ball_engagement    Auckland FC      NaN
238            26  on_ball_engagement    Auckland FC      NaN
437            38  on_ball_engagement      Newcastle      NaN
...           ...                 ...            ...      ...
4461          403  on_ball_engagement      Newcastle      NaN
4560          412  on_ball_engagement      Newcastle      NaN
4598          416  on_ball_engagement      Newcastle      NaN
4679          423  on_ball_engagement    Auckland FC      NaN
4972          448  on_ball_engagement    Auckland FC      NaN

[66 rows x 4 columns]

In [81]:
# Get all rows of data where a shot was taken
bronze_event_data[bronze_event_data['lead_to_goal'] == True].head()

,event_id,index,match_id,frame_start,frame_end,frame_physical_start,time_start,time_end,minute_start,second_start,duration,period,attacking_side_id,attacking_side,event_type_id,event_type,event_subtype_id,event_subtype,player_id,player_name,player_position_id,player_position,player_in_possession_id,player_in_possession_name,player_in_possession_position_id,player_in_possession_position,team_id,team_shortname,x_start,y_start,channel_id_start,channel_start,third_id_start,third_start,penalty_area_start,x_end,y_end,channel_id_end,channel_end,third_id_end,third_end,penalty_area_end,associated_player_possession_event_id,associated_player_possession_frame_start,associated_player_possession_frame_end,associated_player_possession_end_type_id,associated_player_possession_end_type,associated_off_ball_run_event_id,associated_off_ball_run_subtype_id,associated_off_ball_run_subtype,game_state_id,game_state,team_score,opponent_team_score,phase_index,player_possession_phase_index,first_player_possession_in_team_possession,last_player_possession_in_team_possession,lead_to_different_phase,issued_from_different_phase,n_player_possessions_in_phase,team_possession_loss_in_phase,team_in_possession_phase_type_id,team_in_possession_phase_type,team_out_of_possession_phase_type_id,team_out_of_possession_phase_type,current_team_in_possession_next_phase_type_id,current_team_in_possession_next_phase_type,current_team_out_of_possession_next_phase_type_id,current_team_out_of_possession_next_phase_type,current_team_in_possession_previous_phase_type_id,current_team_in_possession_previous_phase_type,current_team_out_of_possession_previous_phase_type_id,current_team_out_of_possession_previous_phase_type,game_interruption_before_id,game_interruption_before,game_interruption_after_id,game_interruption_after,lead_to_shot,lead_to_goal,distance_covered,trajectory_angle,trajectory_direction_id,trajectory_direction,in_to_out,out_to_in,speed_avg,speed_avg_band_id,speed_avg_band,separation_start,separation_end,separation_gain,last_defensive_line_x_start,last_defensive_line_x_end,delta_to_last_defensive_line_start,delta_to_last_defensive_line_end,delta_to_last_defensive_line_gain,last_defensive_line_height_start,last_defensive_line_height_end,last_defensive_line_height_gain,inside_defensive_shape_start,inside_defensive_shape_end,start_type_id,start_type,end_type_id,end_type,consecutive_on_ball_engagements,one_touch,quick_pass,carry,forward_momentum,is_header,hand_pass,initiate_give_and_go,pass_angle_received,pass_direction_received_id,pass_direction_received,pass_distance_received,pass_range_received_id,pass_range_received,pass_outcome_id,pass_outcome,targeted_passing_option_event_id,high_pass,player_targeted_id,player_targeted_name,player_targeted_position_id,player_targeted_position,player_targeted_x_pass,player_targeted_y_pass,player_targeted_channel_pass_id,player_targeted_channel_pass,player_targeted_third_pass_id,player_targeted_third_pass,player_targeted_penalty_area_pass,player_targeted_x_reception,player_targeted_y_reception,player_targeted_channel_reception_id,player_targeted_channel_reception,player_targeted_third_reception_id,player_targeted_third_reception,player_targeted_penalty_area_reception,player_targeted_distance_to_goal_start,player_targeted_distance_to_goal_end,player_targeted_angle_to_goal_start,player_targeted_angle_to_goal_end,player_targeted_average_speed,player_targeted_speed_avg_band_id,player_targeted_speed_avg_band,speed_difference,player_targeted_xpass_completion,player_targeted_difficult_pass_target,player_targeted_xthreat,player_targeted_dangerous,n_passing_options,n_off_ball_runs,n_passing_options_line_break,n_passing_options_first_line_break,n_passing_options_second_last_line_break,n_passing_options_last_line_break,n_passing_options_ahead,n_passing_options_dangerous_difficult,n_passing_options_dangerous_not_difficult,n_passing_options_not_dangerous_not_difficult,n_passing_options_not_dangerous_difficult,n_passing_options_at_start,n_passing_options_at_end,n_passing_options_ahead_at_start,n_passing_options_ahead_at_end,n_teammates_ahead_end,n_teammates_ahead_start,n_player_targeted_opponents_ahead_start,n_player_targeted_opponents_ahead_end,n_player_targeted_teammates_ahead_start,n_player_targeted_teammates_ahead_end,n_player_targeted_teammates_within_5m_start,n_player_targeted_teammates_within_5m_end,n_player_targeted_opponents_within_5m_start,n_player_targeted_opponents_within_5m_end,organised_defense,defensive_structure,n_defensive_lines,first_line_break,first_line_break_type_id,first_line_break_type,second_last_line_break,second_last_line_break_type_id,second_last_line_break_type,last_line_break,last_line_break_type_id,last_line_break_type,furthest_line_break_id,furthest_line_break,furthest_line_break_type_id,furthest_line_break_type,interplayer_distance,interplayer_distance_range_id,interplayer_distance_range,interplayer_distance_start,interplayer_distance_end,interplayer_distance_min,interplayer_distance_start_physical,close_at_player_possession_start,interplayer_angle,interplayer_direction_id,interplayer_direction,angle_of_engagement,goal_side_start,goal_side_end,pass_distance,pass_range_id,pass_range,pass_angle,pass_direction_id,pass_direction,pass_ahead,n_opponents_ahead_player_in_possession_pass_moment,n_opponents_ahead_pass_reception,n_opponents_bypassed,location_to_player_in_possession_id_start,location_to_player_in_possession_start,location_to_player_in_possession_id_end,location_to_player_in_possession_end,distance_to_player_in_possession_start,distance_to_player_in_possession_end,player_in_possession_x_start,player_in_possession_y_start,player_in_possession_channel_id_start,player_in_possession_channel_start,player_in_possession_third_id_start,player_in_possession_third_start,player_in_possession_penalty_area_start,player_in_possession_x_end,player_in_possession_y_end,player_in_possession_channel_id_end,player_in_possession_channel_end,player_in_possession_third_id_end,player_in_possession_third_end,player_in_possession_penalty_area_end,targeted,received,received_in_space,dangerous,difficult_pass_target,xthreat,xpass_completion,passing_option_score,predicted_passing_option,peak_passing_option_frame,passing_option_at_player_possession_start,n_simultaneous_runs,give_and_go,intended_run_behind,push_defensive_line,break_defensive_line,passing_option_at_start,n_simultaneous_passing_options,passing_option_at_pass_moment,n_opponents_ahead_end,n_opponents_ahead_start,n_opponents_overtaken,pressing_chain,pressing_chain_length,pressing_chain_end_type_id,pressing_chain_end_type,pressing_chain_index,index_in_pressing_chain,simultaneous_defensive_engagement_same_target,simultaneous_defensive_engagement_same_target_rank,affected_line_breaking_passing_option_id,affected_line_break_id,affected_line_break,affected_line_breaking_passing_option_attempted,affected_line_breaking_passing_option_xthreat,affected_line_breaking_passing_option_dangerous,affected_line_breaking_passing_option_run_subtype_id,affected_line_breaking_passing_option_run_subtype,possession_danger,beaten_by_possession,beaten_by_movement,stop_possession_danger,reduce_possession_danger,force_backward,xloss_player_possession_start,xloss_player_possession_end,xloss_player_possession_max,xshot_player_possession_start,xshot_player_possession_end,xshot_player_possession_max,is_player_possession_start_matched,is_player_possession_end_matched,is_previous_pass_matched,is_pass_reception_matched,fully_extrapolated
4644,8_912,4644,1886347,50488,50512,NaN,82:48.8,82:51.2,82,48,2.4,2,1,left_to_right,8,player_possession,NaN,NaN,23418,F. Gallegos,15,AM,NaN,NaN,NaN,NaN,4177,Auckland FC,-0.77,6.49,3,center,2,middle_third,False,6.08,3.89,3,center,2,middle_third,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,drawing,0,0,422,1.0,False,False,False,True,6.0,False,2,finish,8,low_block,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,7.41,-20.78,1.0,forward,False,False,NaN,NaN,NaN,6.70,8.66,1.96,25.87,28.75,26.64,22.67,-3.97,26.13,23.25,-2.88,False,False,1.0,pass_reception,1.0,pass,NaN,False,False,True,False,False,False,False,123.5,3.0,sideway_left,37.28,3.0,long,1.0,successful,7_2327,False,965685.0,L. Gillion,16.0,LW,18.71,1.78,3.0,center,3.0,attacking_third,False,17.0,0.41,3.0,center,2.0,middle_third,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.8791,False,0.0095,False,6.0,2.0,3.0,0.0,2.0,1.0,6.0,1.0,0.0,4.0,1.0,2.0,5.0,2.0,6.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,442.0,3.0,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,12.81,1.0,short,NaN,NaN,NaN,NaN,NaN,-9.48,1.0,forward,NaN,NaN,NaN,11.27,1.0,short,-14.12,1.0,forward,True,8.0,6.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,9.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,True,True,True
4645,7_2325,4645,1886347,50488,50502,NaN,82:48.8,82:50.2,82,48,1.4,2,1,left_to_right,7,passing_option,NaN,NaN,51713,C. Elliott,8,RB,23418.0,F. Gallegos,15.0,AM,4177,Auckland FC,21.61,-30.86,5,wide_right,3,attacking_third,False,25.70,-29.33,5,wide_right,3,attacking_third,False,8_912,50488.0,NaN,NaN,NaN,1_549,8.0,run_ahead_of_the_ball,3,drawing,0,0,422,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,finish,8,low_block,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,4.46,20.51,1.0,forward,False,False,11.55,1.0,jogging,5.70,5.91,0.21,25.87,28.60,4.26,2.90,-1.36,26.13,23.40,-2.73,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,442.0,3.0,False,NaN,NaN,True,1.0,through,True,1.0,through,3.0,last,1.0,through,43.02,3.0,long,NaN,NaN,NaN,NaN,NaN,-57.24,4.0,sideway_right,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,8.0,3.0,5.0,3.0,ahead,3.0,ahead,43.54,40.50,-0.77,6.49,3.0,center,2.0,middle_third,False,3.34,4.44,3.0,center,2.0,middle_third,False,False,False,NaN,False,False,0.0053,0.6911,0.9607,True,50492.0,True,NaN,NaN,NaN,NaN,NaN,NaN,5.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,False
4646,7_2326,4646,1886347,50488,50512,NaN,82:48.8,82:51.2,82,48,2.4,2,1,left_to_right,7,passing_option,NaN,NaN,14736,L. Verstraete,10,DM,23418.0,F. Gallegos,15.0,AM,4177,Auckland FC,3.48,-18.12,4,half_space_right,2,middle_third,False,7.02,-15.96,4,half_space_right,2,middle_third,False,8_912,50488.0,NaN,NaN,NaN,NaN,NaN,NaN,3,drawing,0,0,422,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,finish,8,low_block,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,4.47,31.39,1.0,forward,False,False,6.73,1.0,jogging,8.86,7.15,-1.70,25.87,28.75,22.39,21.73,-0.66,26.13,23.25,-2.88,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,442.0,3.0,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,19.87,2.0,medium,NaN,NaN,NaN,NaN,NaN,-87.29,4.0,sideway_right,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,8.0,8.0,0.0,3.0,ahead,2.0,same_line,24.97,19.87,-0.77,6.49,3.0,center,2.0,middle_third,False,6.08,3.89,3.0,center,2.0,middle_third,False,False,False,NaN,False,False,0.0035,0.8987,0.9147,True,50512.0,True,NaN,NaN,NaN,NaN,NaN,NaN,5.0,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,False
4647,7_2327,4647,1886347,50495,50512,NaN,82:49.5,82:51.2,82,49,1.7,2,1,left_to_right,7,passing_option,NaN,NaN,965685,L. Gillion,16,LW,23418.0,F. Gallegos,15.0,AM,4177,Auckland FC,19.96,8.16,3,center,3,attacking_third,False,18.71,1.78,3,center,3,attacking_third,False,8_912,50488.0,NaN,NaN,NaN,NaN,NaN,NaN,3,drawing,0,0,422,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,finish,8,low_block,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,6.18,-101.09,4.0,sideway_right,False,False,13.68,1.0,jogging,5.92,2.16,-3.76,27.55,28.75,7.59,10.04,2.45,24.45,23.25,-1.20,False,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,442.0,3.0,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,12.81,1.0,short,NaN,NaN,NaN,NaN,NaN,-9.48,1.0,forward,NaN,NaN,NaN,11.27,1.0,short,-14.12,1.0,forward,True,8.0,6.0,2.0,3.0,ahead,3.0,ahead,18.91,12.81,1.26,5.33,3.0,center,2.0,middle_third,False,6.08,3.89,3.0,center,2.0,middle_third,False,True,True,False,False,False,0.0095,0.8791,0.9829,True,50512.0,False,NaN,NaN,NaN,NaN,NaN,NaN,5.0,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,True,False
4648,7_2328,4648,1886347,50496,50509,NaN,82:49.6,82:50.9,82,49,1.3,2,1,left_to_right,7,passing_option,NaN,NaN,43829,N. Moreno,17,RW,23418.0,F. Gallegos,15.0,AM,4177,Auckland FC,11.74,-22.71,5,wide_right,2,middle_third,False,13.13,-19.15,4,half_space_right,2,middle_third,False,8_912,50488.0,NaN,NaN,NaN,NaN,NaN,NaN,3,drawing,0,0,422,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,finish,8,low_block,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,3.62,68.67,3.0,sideway_left,False,True,10.42,1.0,jogging,5.75,3.22,-2.53,27.75,28.70,16.01,15.57,-0.44,24.25,23.30,-0.95,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,442.0,3.0,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,26.90,2.0,medium,NaN,NaN,NaN,NaN,NaN,-70.32,4.0,sideway_right,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,8.0,7.0,1.0,3.0,ahead,3.0,ahead,29.70,24.38,1.55,5.19,3.0,center,2.0,middle_third,False,5.32,3.94,3.0,center,2.0,middle_third,False,False,False,NaN,False,False,0.0052,0.8911,0.8556,True,50502.0,False,NaN,NaN,NaN,NaN,NaN,NaN,5.0,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN,False

In [88]:
test_data = bronze_event_data[bronze_event_data['event_type'] == 'player_possession']
bronze_event_data['stop_possession_danger'].value_counts()

stop_possession_danger
False    926
True      11
Name: count, dtype: int64

In [87]:
bronze_event_data[bronze_event_data['beaten_by_movement'] == True].head()

,event_id,index,match_id,frame_start,frame_end,frame_physical_start,time_start,time_end,minute_start,second_start,duration,period,attacking_side_id,attacking_side,event_type_id,event_type,event_subtype_id,event_subtype,player_id,player_name,player_position_id,player_position,player_in_possession_id,player_in_possession_name,player_in_possession_position_id,player_in_possession_position,team_id,team_shortname,x_start,y_start,channel_id_start,channel_start,third_id_start,third_start,penalty_area_start,x_end,y_end,channel_id_end,channel_end,third_id_end,third_end,penalty_area_end,associated_player_possession_event_id,associated_player_possession_frame_start,associated_player_possession_frame_end,associated_player_possession_end_type_id,associated_player_possession_end_type,associated_off_ball_run_event_id,associated_off_ball_run_subtype_id,associated_off_ball_run_subtype,game_state_id,game_state,team_score,opponent_team_score,phase_index,player_possession_phase_index,first_player_possession_in_team_possession,last_player_possession_in_team_possession,lead_to_different_phase,issued_from_different_phase,n_player_possessions_in_phase,team_possession_loss_in_phase,team_in_possession_phase_type_id,team_in_possession_phase_type,team_out_of_possession_phase_type_id,team_out_of_possession_phase_type,current_team_in_possession_next_phase_type_id,current_team_in_possession_next_phase_type,current_team_out_of_possession_next_phase_type_id,current_team_out_of_possession_next_phase_type,current_team_in_possession_previous_phase_type_id,current_team_in_possession_previous_phase_type,current_team_out_of_possession_previous_phase_type_id,current_team_out_of_possession_previous_phase_type,game_interruption_before_id,game_interruption_before,game_interruption_after_id,game_interruption_after,lead_to_shot,lead_to_goal,distance_covered,trajectory_angle,trajectory_direction_id,trajectory_direction,in_to_out,out_to_in,speed_avg,speed_avg_band_id,speed_avg_band,separation_start,separation_end,separation_gain,last_defensive_line_x_start,last_defensive_line_x_end,delta_to_last_defensive_line_start,delta_to_last_defensive_line_end,delta_to_last_defensive_line_gain,last_defensive_line_height_start,last_defensive_line_height_end,last_defensive_line_height_gain,inside_defensive_shape_start,inside_defensive_shape_end,start_type_id,start_type,end_type_id,end_type,consecutive_on_ball_engagements,one_touch,quick_pass,carry,forward_momentum,is_header,hand_pass,initiate_give_and_go,pass_angle_received,pass_direction_received_id,pass_direction_received,pass_distance_received,pass_range_received_id,pass_range_received,pass_outcome_id,pass_outcome,targeted_passing_option_event_id,high_pass,player_targeted_id,player_targeted_name,player_targeted_position_id,player_targeted_position,player_targeted_x_pass,player_targeted_y_pass,player_targeted_channel_pass_id,player_targeted_channel_pass,player_targeted_third_pass_id,player_targeted_third_pass,player_targeted_penalty_area_pass,player_targeted_x_reception,player_targeted_y_reception,player_targeted_channel_reception_id,player_targeted_channel_reception,player_targeted_third_reception_id,player_targeted_third_reception,player_targeted_penalty_area_reception,player_targeted_distance_to_goal_start,player_targeted_distance_to_goal_end,player_targeted_angle_to_goal_start,player_targeted_angle_to_goal_end,player_targeted_average_speed,player_targeted_speed_avg_band_id,player_targeted_speed_avg_band,speed_difference,player_targeted_xpass_completion,player_targeted_difficult_pass_target,player_targeted_xthreat,player_targeted_dangerous,n_passing_options,n_off_ball_runs,n_passing_options_line_break,n_passing_options_first_line_break,n_passing_options_second_last_line_break,n_passing_options_last_line_break,n_passing_options_ahead,n_passing_options_dangerous_difficult,n_passing_options_dangerous_not_difficult,n_passing_options_not_dangerous_not_difficult,n_passing_options_not_dangerous_difficult,n_passing_options_at_start,n_passing_options_at_end,n_passing_options_ahead_at_start,n_passing_options_ahead_at_end,n_teammates_ahead_end,n_teammates_ahead_start,n_player_targeted_opponents_ahead_start,n_player_targeted_opponents_ahead_end,n_player_targeted_teammates_ahead_start,n_player_targeted_teammates_ahead_end,n_player_targeted_teammates_within_5m_start,n_player_targeted_teammates_within_5m_end,n_player_targeted_opponents_within_5m_start,n_player_targeted_opponents_within_5m_end,organised_defense,defensive_structure,n_defensive_lines,first_line_break,first_line_break_type_id,first_line_break_type,second_last_line_break,second_last_line_break_type_id,second_last_line_break_type,last_line_break,last_line_break_type_id,last_line_break_type,furthest_line_break_id,furthest_line_break,furthest_line_break_type_id,furthest_line_break_type,interplayer_distance,interplayer_distance_range_id,interplayer_distance_range,interplayer_distance_start,interplayer_distance_end,interplayer_distance_min,interplayer_distance_start_physical,close_at_player_possession_start,interplayer_angle,interplayer_direction_id,interplayer_direction,angle_of_engagement,goal_side_start,goal_side_end,pass_distance,pass_range_id,pass_range,pass_angle,pass_direction_id,pass_direction,pass_ahead,n_opponents_ahead_player_in_possession_pass_moment,n_opponents_ahead_pass_reception,n_opponents_bypassed,location_to_player_in_possession_id_start,location_to_player_in_possession_start,location_to_player_in_possession_id_end,location_to_player_in_possession_end,distance_to_player_in_possession_start,distance_to_player_in_possession_end,player_in_possession_x_start,player_in_possession_y_start,player_in_possession_channel_id_start,player_in_possession_channel_start,player_in_possession_third_id_start,player_in_possession_third_start,player_in_possession_penalty_area_start,player_in_possession_x_end,player_in_possession_y_end,player_in_possession_channel_id_end,player_in_possession_channel_end,player_in_possession_third_id_end,player_in_possession_third_end,player_in_possession_penalty_area_end,targeted,received,received_in_space,dangerous,difficult_pass_target,xthreat,xpass_completion,passing_option_score,predicted_passing_option,peak_passing_option_frame,passing_option_at_player_possession_start,n_simultaneous_runs,give_and_go,intended_run_behind,push_defensive_line,break_defensive_line,passing_option_at_start,n_simultaneous_passing_options,passing_option_at_pass_moment,n_opponents_ahead_end,n_opponents_ahead_start,n_opponents_overtaken,pressing_chain,pressing_chain_length,pressing_chain_end_type_id,pressing_chain_end_type,pressing_chain_index,index_in_pressing_chain,simultaneous_defensive_engagement_same_target,simultaneous_defensive_engagement_same_target_rank,affected_line_breaking_passing_option_id,affected_line_break_id,affected_line_break,affected_line_breaking_passing_option_attempted,affected_line_breaking_passing_option_xthreat,affected_line_breaking_passing_option_dangerous,affected_line_breaking_passing_option_run_subtype_id,affected_line_breaking_passing_option_run_subtype,possession_danger,beaten_by_possession,beaten_by_movement,stop_possession_danger,reduce_possession_danger,force_backward,xloss_player_possession_start,xloss_player_possession_end,xloss_player_possession_max,xshot_player_possession_start,xshot_player_possession_end,xshot_player_possession_max,is_player_possession_start_matched,is_player_possession_end_matched,is_previous_pass_matched,is_pass_reception_matched,fully_extrapolated
37,9_5,37,1886347,345,350,341.0,00:33.1,00:34.0,0,33,0.9,1,1,left_to_right,9,on_ball_engagement,14.0,recovery_press,50983,D. Ingham,8,RB,23418.0,F. Gallegos,15.0,AM,1805,Newcastle,-40.68,-23.45,5,wide_right,1,defensive_third,False,-43.31,-23.07,5,wide_right,1,defensive_third,False,8_7,350.0,350.0,1.0,pass,NaN,NaN,NaN,3,drawing,0,0,5,NaN,NaN,NaN,NaN,NaN,NaN,True,2,finish,8,low_block,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,4.04,171.78,2.0,backward,NaN,NaN,18.12,2.0,running,NaN,NaN,NaN,-43.01,-43.95,2.33,0.64,-1.69,8.99,8.05,-0.94,NaN,NaN,NaN,NaN,9.0,direct_disruption,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23418.0,F. Gallegos,15.0,AM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.12,27.22,109.58,105.62,20.30,3.0,hsr,-2.18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,6.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.28,3.42,3.42,4.90,False,NaN,NaN,NaN,19.53,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,False,True,True,False,False,0.452,0.452,0.452,0.004,0.004,0.004,True,True,True,True,NaN
167,9_31,167,1886347,1437,1441,1425.0,02:21.5,02:23.1,2,21,1.6,1,2,right_to_left,9,on_ball_engagement,14.0,recovery_press,33697,N. Pijnaker,4,LCB,966120.0,B. Gibson,19.0,CF,4177,Auckland FC,-33.52,-0.57,3,center,1,defensive_third,False,-36.53,-0.68,3,center,1,defensive_third,True,8_32,1433.0,1444.0,2.0,shot,NaN,NaN,NaN,3,drawing,0,0,19,NaN,NaN,NaN,NaN,NaN,NaN,False,2,finish,8,low_block,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,False,11.01,-176.62,2.0,backward,NaN,NaN,24.82,3.0,hsr,NaN,NaN,NaN,-33.52,-36.53,0.00,0.00,0.00,18.48,15.47,-3.01,NaN,NaN,NaN,NaN,7.0,direct_regain,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,966120.0,B. Gibson,19.0,CF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.43,15.44,167.69,162.20,30.35,4.0,sprinting,-5.53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.39,4.11,3.39,2.41,False,NaN,NaN,NaN,-8.09,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,False,True,False,False,False,0.109,0.055,0.109,0.780,0.896,0.916,True,True,True,NaN,NaN
514,9_94,514,1886347,4225,4236,4225.0,07:01.5,07:02.6,7,1,1.1,1,1,left_to_right,9,on_ball_engagement,14.0,recovery_press,735574,K. Grozos,11,RDM,23418.0,F. Gallegos,15.0,AM,1805,Newcastle,-24.08,10.40,2,half_space_left,1,defensive_third,False,-28.96,3.57,3,center,1,defensive_third,False,8_103,4236.0,4236.0,2.0,shot,NaN,NaN,NaN,3,drawing,0,0,49,NaN,NaN,NaN,NaN,NaN,NaN,True,2,finish,8,low_block,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,goal_kick_for,True,False,7.72,-125.55,4.0,sideway_right,NaN,NaN,27.44,4.0,sprinting,NaN,NaN,NaN,-34.62,-36.37,10.54,7.41,-3.13,17.38,15.63,-1.75,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23418.0,F. Gallegos,15.0,AM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.97,24.70,-166.53,-177.01,23.64,3.0,hsr,3.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,5.0,6.0,6.0,4.0,4.0,0.0,0.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.63,2.80,2.80,3.63,False,NaN,NaN,NaN,-1.82,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,False,True,False,False,False,0.070,0.070,0.070,0.879,0.879,0.879,True,True,True,NaN,NaN
1220,9_220,1220,1886347,10725,10739,10725.0,17:51.5,17:52.9,17,51,1.4,1,2,right_to_left,9,on_ball_engagement,14.0,recovery_press,133501,L. Rogerson,17,RW,735573.0,T. Aquilina,16.0,LW,4177,Auckland FC,-36.84,-21.17,5,wide_right,1,defensive_third,False,-46.60,-17.53,4,half_space_right,1,defensive_third,True,8_238,10735.0,10739.0,5.0,possession_loss,NaN,NaN,NaN,3,drawing,0,0,117,NaN,NaN,NaN,NaN,NaN,NaN,True,2,finish,8,low_block,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,10.42,159.55,2.0,backward,NaN,NaN,26.58,4.0,sprinting,NaN,NaN,NaN,-42.74,-46.60,5.90,0.00,-5.90,9.26,5.40,-3.86,NaN,NaN,NaN,NaN,8.0,indirect_regain,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,735573.0,T. Aquilina,16.0,LW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.23,18.07,122.95,103.41,25.99,4.0,sprinting,0.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,5.0,4.0,0.0,2.0,0.0,0.0,0.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.44,1.21,1.21,1.44,False,NaN,NaN,NaN,-2.29,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,False,True,True,True,False,0.411,0.393,0.411,0.026,0.036,0.039,True,True,True,NaN,NaN
1639,9_288,1639,1886347,16150,16164,16148.0,26:53.8,26:55.4,26,53,1.6,1,1,left_to_right,9,on_ball_engagement,14.0,recovery_press,735574,K. Grozos,11,RDM,50951.0,J. Brimmer,19.0,CF,1805,Newcastle,-40.91,15.17,2,half_space_left,1,defensive_third,True,-47.76,17.67,2,half_space_left,1,defensive_third,True,8_322,16164.0,16164.0,1.0,pass,NaN,NaN,NaN,3,drawing,0,0,163,NaN,NaN,NaN,NaN,NaN,NaN,False,2,finish,8,low_block,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,False,8.24,159.95,2.0,backward,NaN,NaN,18.37,2.0,running,NaN,NaN,NaN,-40.91,-47.76,0.00,0.00,0.00,11.09,4.24,-6.85,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50951.0,J. Brimmer,19.0,CF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.27,20.57,-120.79,-101.07,20.33,3.0,hsr,-1.96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,9.0,2.0,0.0,0.0,0.0,1.0,0.0,3.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.89,2.54,2.54,4.92,False,NaN,NaN,NaN,-6.83,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,False,True,False,False,False,0.465,0.465,0.465,0.002,0.002,0.002,True,True,True,True,NaN

In [71]:
def find_all_goals_scored(df):
    df = df[(df['lead_to_goal'] == True) & (df['event_type'] == 'player_possession')]
    return (df['end_type'] == 'shot').cumsum().shift(1, fill_value=0) + 1

In [77]:
events_data_copy = bronze_event_data.copy()
events_data_copy["Sequence_ID"] = find_all_goals_scored(events_data_copy)
grouped_data = events_data_copy.groupby("Sequence_ID").agg({'frame_start': 'min', 'frame_end': 'max', 'lead_to_goal': 'first', 'player_name': 'last', 'time_end': 'last'}).reset_index()

In [78]:
events_data_copy[events_data_copy['Sequence_ID'] == 1]

,event_id,index,match_id,frame_start,frame_end,frame_physical_start,time_start,time_end,minute_start,second_start,duration,period,attacking_side_id,attacking_side,event_type_id,event_type,event_subtype_id,event_subtype,player_id,player_name,player_position_id,player_position,player_in_possession_id,player_in_possession_name,player_in_possession_position_id,player_in_possession_position,team_id,team_shortname,x_start,y_start,channel_id_start,channel_start,third_id_start,third_start,penalty_area_start,x_end,y_end,channel_id_end,channel_end,third_id_end,third_end,penalty_area_end,associated_player_possession_event_id,associated_player_possession_frame_start,associated_player_possession_frame_end,associated_player_possession_end_type_id,associated_player_possession_end_type,associated_off_ball_run_event_id,associated_off_ball_run_subtype_id,associated_off_ball_run_subtype,game_state_id,game_state,team_score,opponent_team_score,phase_index,player_possession_phase_index,first_player_possession_in_team_possession,last_player_possession_in_team_possession,lead_to_different_phase,issued_from_different_phase,n_player_possessions_in_phase,team_possession_loss_in_phase,team_in_possession_phase_type_id,team_in_possession_phase_type,team_out_of_possession_phase_type_id,team_out_of_possession_phase_type,current_team_in_possession_next_phase_type_id,current_team_in_possession_next_phase_type,current_team_out_of_possession_next_phase_type_id,current_team_out_of_possession_next_phase_type,current_team_in_possession_previous_phase_type_id,current_team_in_possession_previous_phase_type,current_team_out_of_possession_previous_phase_type_id,current_team_out_of_possession_previous_phase_type,game_interruption_before_id,game_interruption_before,game_interruption_after_id,game_interruption_after,lead_to_shot,lead_to_goal,distance_covered,trajectory_angle,trajectory_direction_id,trajectory_direction,in_to_out,out_to_in,speed_avg,speed_avg_band_id,speed_avg_band,separation_start,separation_end,separation_gain,last_defensive_line_x_start,last_defensive_line_x_end,delta_to_last_defensive_line_start,delta_to_last_defensive_line_end,delta_to_last_defensive_line_gain,last_defensive_line_height_start,last_defensive_line_height_end,last_defensive_line_height_gain,inside_defensive_shape_start,inside_defensive_shape_end,start_type_id,start_type,end_type_id,end_type,consecutive_on_ball_engagements,one_touch,quick_pass,carry,forward_momentum,is_header,hand_pass,initiate_give_and_go,pass_angle_received,pass_direction_received_id,pass_direction_received,pass_distance_received,pass_range_received_id,pass_range_received,pass_outcome_id,pass_outcome,targeted_passing_option_event_id,high_pass,player_targeted_id,player_targeted_name,player_targeted_position_id,player_targeted_position,player_targeted_x_pass,player_targeted_y_pass,player_targeted_channel_pass_id,player_targeted_channel_pass,player_targeted_third_pass_id,player_targeted_third_pass,player_targeted_penalty_area_pass,player_targeted_x_reception,player_targeted_y_reception,player_targeted_channel_reception_id,player_targeted_channel_reception,player_targeted_third_reception_id,player_targeted_third_reception,player_targeted_penalty_area_reception,player_targeted_distance_to_goal_start,player_targeted_distance_to_goal_end,player_targeted_angle_to_goal_start,player_targeted_angle_to_goal_end,player_targeted_average_speed,player_targeted_speed_avg_band_id,player_targeted_speed_avg_band,speed_difference,player_targeted_xpass_completion,player_targeted_difficult_pass_target,player_targeted_xthreat,player_targeted_dangerous,n_passing_options,n_off_ball_runs,n_passing_options_line_break,n_passing_options_first_line_break,n_passing_options_second_last_line_break,n_passing_options_last_line_break,n_passing_options_ahead,n_passing_options_dangerous_difficult,n_passing_options_dangerous_not_difficult,n_passing_options_not_dangerous_not_difficult,n_passing_options_not_dangerous_difficult,n_passing_options_at_start,n_passing_options_at_end,n_passing_options_ahead_at_start,n_passing_options_ahead_at_end,n_teammates_ahead_end,n_teammates_ahead_start,n_player_targeted_opponents_ahead_start,n_player_targeted_opponents_ahead_end,n_player_targeted_teammates_ahead_start,n_player_targeted_teammates_ahead_end,n_player_targeted_teammates_within_5m_start,n_player_targeted_teammates_within_5m_end,n_player_targeted_opponents_within_5m_start,n_player_targeted_opponents_within_5m_end,organised_defense,defensive_structure,n_defensive_lines,first_line_break,first_line_break_type_id,first_line_break_type,second_last_line_break,second_last_line_break_type_id,second_last_line_break_type,last_line_break,last_line_break_type_id,last_line_break_type,furthest_line_break_id,furthest_line_break,furthest_line_break_type_id,furthest_line_break_type,interplayer_distance,interplayer_distance_range_id,interplayer_distance_range,interplayer_distance_start,interplayer_distance_end,interplayer_distance_min,interplayer_distance_start_physical,close_at_player_possession_start,interplayer_angle,interplayer_direction_id,interplayer_direction,angle_of_engagement,goal_side_start,goal_side_end,pass_distance,pass_range_id,pass_range,pass_angle,pass_direction_id,pass_direction,pass_ahead,n_opponents_ahead_player_in_possession_pass_moment,n_opponents_ahead_pass_reception,n_opponents_bypassed,location_to_player_in_possession_id_start,location_to_player_in_possession_start,location_to_player_in_possession_id_end,location_to_player_in_possession_end,distance_to_player_in_possession_start,distance_to_player_in_possession_end,player_in_possession_x_start,player_in_possession_y_start,player_in_possession_channel_id_start,player_in_possession_channel_start,player_in_possession_third_id_start,player_in_possession_third_start,player_in_possession_penalty_area_start,player_in_possession_x_end,player_in_possession_y_end,player_in_possession_channel_id_end,player_in_possession_channel_end,player_in_possession_third_id_end,player_in_possession_third_end,player_in_possession_penalty_area_end,targeted,received,received_in_space,dangerous,difficult_pass_target,xthreat,xpass_completion,passing_option_score,predicted_passing_option,peak_passing_option_frame,passing_option_at_player_possession_start,n_simultaneous_runs,give_and_go,intended_run_behind,push_defensive_line,break_defensive_line,passing_option_at_start,n_simultaneous_passing_options,passing_option_at_pass_moment,n_opponents_ahead_end,n_opponents_ahead_start,n_opponents_overtaken,pressing_chain,pressing_chain_length,pressing_chain_end_type_id,pressing_chain_end_type,pressing_chain_index,index_in_pressing_chain,simultaneous_defensive_engagement_same_target,simultaneous_defensive_engagement_same_target_rank,affected_line_breaking_passing_option_id,affected_line_break_id,affected_line_break,affected_line_breaking_passing_option_attempted,affected_line_breaking_passing_option_xthreat,affected_line_breaking_passing_option_dangerous,affected_line_breaking_passing_option_run_subtype_id,affected_line_breaking_passing_option_run_subtype,possession_danger,beaten_by_possession,beaten_by_movement,stop_possession_danger,reduce_possession_danger,force_backward,xloss_player_possession_start,xloss_player_possession_end,xloss_player_possession_max,xshot_player_possession_start,xshot_player_possession_end,xshot_player_possession_max,is_player_possession_start_matched,is_player_possession_end_matched,is_previous_pass_matched,is_pass_reception_matched,fully_extrapolated,Sequence_ID
4644,8_912,4644,1886347,50488,50512,NaN,82:48.8,82:51.2,82,48,2.4,2,1,left_to_right,8,player_possession,NaN,NaN,23418,F. Gallegos,15,AM,NaN,NaN,NaN,NaN,4177,Auckland FC,-0.77,6.49,3,center,2,middle_third,False,6.08,3.89,3,center,2,middle_third,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,drawing,0,0,422,1.0,False,False,False,True,6.0,False,2,finish,8,low_block,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,7.41,-20.78,1.0,forward,False,False,NaN,NaN,NaN,6.70,8.66,1.96,25.87,28.75,26.64,22.67,-3.97,26.13,23.25,-2.88,False,False,1.0,pass_reception,1.0,pass,NaN,False,False,True,False,False,False,False,123.50,3.0,sideway_left,37.28,3.0,long,1.0,successful,7_2327,False,965685.0,L. Gillion,16.0,LW,18.71,1.78,3.0,center,3.0,attacking_third,False,17.00,0.41,3.0,center,2.0,middle_third,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.8791,False,0.0095,False,6.0,2.0,3.0,0.0,2.0,1.0,6.0,1.0,0.0,4.0,1.0,2.0,5.0,2.0,6.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,442.0,3.0,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,12.81,1.0,short,NaN,NaN,NaN,NaN,NaN,-9.48,1.0,forward,NaN,NaN,NaN,11.27,1.0,short,-14.12,1.0,forward,True,8.0,6.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,9.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,True,True,True,1.0
4653,8_913,4653,1886347,50522,50522,NaN,82:52.2,82:52.2,82,52,0.0,2,1,left_to_right,8,player_possession,NaN,NaN,965685,L. Gillion,16,LW,NaN,NaN,NaN,NaN,4177,Auckland FC,16.85,0.42,3,center,2,middle_third,False,16.85,0.42,3,center,2,middle_third,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,drawing,0,0,422,2.0,False,False,False,False,6.0,False,2,finish,8,low_block,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,0.00,-164.69,2.0,backward,NaN,NaN,7.15,1.0,jogging,2.04,2.04,0.00,29.39,29.39,12.54,12.54,0.00,22.61,22.61,0.00,True,True,1.0,pass_reception,1.0,pass,NaN,True,False,False,False,False,False,False,-14.12,1.0,forward,11.27,1.0,short,1.0,successful,7_2331,False,23418.0,F. Gallegos,15.0,AM,7.92,4.68,3.0,center,2.0,middle_third,False,8.94,7.34,3.0,center,2.0,middle_third,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.9840,False,0.0059,False,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,NaN,NaN,NaN,NaN,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,442.0,3.0,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,9.89,1.0,short,NaN,NaN,NaN,NaN,NaN,154.50,2.0,backward,NaN,NaN,NaN,10.16,1.0,short,165.40,2.0,backward,False,7.0,8.0,-1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,7.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,False,True,False,1.0
4657,8_914,4657,1886347,50536,50545,NaN,82:53.6,82:54.5,82,53,0.9,2,1,left_to_right,8,player_possession,NaN,NaN,23418,F. Gallegos,15,AM,NaN,NaN,NaN,NaN,4177,Auckland FC,8.94,7.34,3,center,2,middle_third,False,9.26,9.34,2,half_space_left,2,middle_third,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,drawing,0,0,422,3.0,False,False,False,False,6.0,False,2,finish,8,low_block,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,1.79,80.91,3.0,sideway_left,NaN,NaN,8.10,1.0,jogging,5.62,6.01,0.39,29.91,31.32,20.97,22.06,1.09,22.09,20.68,-1.41,False,False,1.0,pass_reception,1.0,pass,NaN,False,True,False,False,False,False,False,165.40,2.0,backward,10.16,1.0,short,1.0,successful,7_2333,False,133498.0,F. De Vries,2.0,LB,19.39,20.71,1.0,wide_left,3.0,attacking_third,False,23.25,22.47,1.0,wide_left,3.0,attacking_third,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.9613,False,0.0119,False,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,433.0,3.0,True,NaN,NaN,False,NaN,NaN,False,NaN,NaN,1.0,first,2.0,around,15.23,2.0,medium,NaN,NaN,NaN,NaN,NaN,48.30,3.0,sideway_left,NaN,NaN,NaN,13.44,1.0,short,37.93,1.0,forward,True,9.0,7.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,8.0,-1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,True,True,False,1.0
4662,8_915,4662,1886347,50558,50575,NaN,82:55.8,82:57.5,82,55,1.7,2,1,left_to_right,8,player_possession,NaN,NaN,133498,F. De Vries,2,LB,NaN,NaN,NaN,NaN,4177,Auckland FC,23.25,22.47,1,wide_left,3,attacking_third,False,31.81,23.82,1,wide_left,3,attacking_third,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,drawing,0,0,422,4.0,False,False,False,False,6.0,False,2,finish,8,low_block,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,8.13,8.96,1.0,forward,False,False,18.26,2.0,running,7.56,3.05,-4.51,34.62,40.93,11.37,9.12,-2.25,17.38,11.07,-6.31,False,False,1.0,pass_reception,1.0,pass,NaN,False,False,True,False,False,False,False,37.93,1.0,forward,13.44,1.0,short,1.0,successful,7_2337,True,43829.0,N. Moreno,17.0,RW,28.03,-6.73,3.0,center,3.0,attacking_third,False,35.54,-1.15,3.0,center,3.0,attacking_third,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.1698,True,0.0312,True,4.0,3.0,0.0,0.0,0.0,0.0,2.0,4.0,0.0,0.0,0.0,2.0,4.0,1.0,2.0,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.78,3.0,long,NaN,NaN,NaN,NaN,NaN,-97.05,4.0,sideway_right,NaN,NaN,NaN,34.37,3.0,long,-102.47,4.0,sideway_right,False,7.0,8.0,-1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,7.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,True,True,False,1.0
4669,8_916,4669,1886347,50600,50600,NaN,83:00.0,83:00.0,83,0,0.0,2,1,left_to_right,8,player_possession,NaN,NaN,43829,N. Moreno,17,RW,NaN,NaN,NaN,NaN,4177,Auckland FC,35.54,-1.15,3,center,3,attacking_third,True,35.54,-1.15,3,center,3,attacking_third,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,winning,1,0,422,5.0,False,True,True,False,6.0,False,2,finish,8,low_block,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,goal_for,True,True,0.00,49.00,3.0,sideway_left,NaN,NaN,16.74,2.0,running,4.57,4.57,0.00,46.23,46.23,10.69,10.69,0.00,5.77,5.77,0.00,True,True,1.0,pass_reception,2.0,shot,NaN,True,False,False,False,False,False,False,-102.47,4.0,sideway_right,34.37,3.0,long,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,8.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,True,NaN,False,1.0

In [79]:
events_data_copy[events_data_copy['Sequence_ID'] == 2]

,event_id,index,match_id,frame_start,frame_end,frame_physical_start,time_start,time_end,minute_start,second_start,duration,period,attacking_side_id,attacking_side,event_type_id,event_type,event_subtype_id,event_subtype,player_id,player_name,player_position_id,player_position,player_in_possession_id,player_in_possession_name,player_in_possession_position_id,player_in_possession_position,team_id,team_shortname,x_start,y_start,channel_id_start,channel_start,third_id_start,third_start,penalty_area_start,x_end,y_end,channel_id_end,channel_end,third_id_end,third_end,penalty_area_end,associated_player_possession_event_id,associated_player_possession_frame_start,associated_player_possession_frame_end,associated_player_possession_end_type_id,associated_player_possession_end_type,associated_off_ball_run_event_id,associated_off_ball_run_subtype_id,associated_off_ball_run_subtype,game_state_id,game_state,team_score,opponent_team_score,phase_index,player_possession_phase_index,first_player_possession_in_team_possession,last_player_possession_in_team_possession,lead_to_different_phase,issued_from_different_phase,n_player_possessions_in_phase,team_possession_loss_in_phase,team_in_possession_phase_type_id,team_in_possession_phase_type,team_out_of_possession_phase_type_id,team_out_of_possession_phase_type,current_team_in_possession_next_phase_type_id,current_team_in_possession_next_phase_type,current_team_out_of_possession_next_phase_type_id,current_team_out_of_possession_next_phase_type,current_team_in_possession_previous_phase_type_id,current_team_in_possession_previous_phase_type,current_team_out_of_possession_previous_phase_type_id,current_team_out_of_possession_previous_phase_type,game_interruption_before_id,game_interruption_before,game_interruption_after_id,game_interruption_after,lead_to_shot,lead_to_goal,distance_covered,trajectory_angle,trajectory_direction_id,trajectory_direction,in_to_out,out_to_in,speed_avg,speed_avg_band_id,speed_avg_band,separation_start,separation_end,separation_gain,last_defensive_line_x_start,last_defensive_line_x_end,delta_to_last_defensive_line_start,delta_to_last_defensive_line_end,delta_to_last_defensive_line_gain,last_defensive_line_height_start,last_defensive_line_height_end,last_defensive_line_height_gain,inside_defensive_shape_start,inside_defensive_shape_end,start_type_id,start_type,end_type_id,end_type,consecutive_on_ball_engagements,one_touch,quick_pass,carry,forward_momentum,is_header,hand_pass,initiate_give_and_go,pass_angle_received,pass_direction_received_id,pass_direction_received,pass_distance_received,pass_range_received_id,pass_range_received,pass_outcome_id,pass_outcome,targeted_passing_option_event_id,high_pass,player_targeted_id,player_targeted_name,player_targeted_position_id,player_targeted_position,player_targeted_x_pass,player_targeted_y_pass,player_targeted_channel_pass_id,player_targeted_channel_pass,player_targeted_third_pass_id,player_targeted_third_pass,player_targeted_penalty_area_pass,player_targeted_x_reception,player_targeted_y_reception,player_targeted_channel_reception_id,player_targeted_channel_reception,player_targeted_third_reception_id,player_targeted_third_reception,player_targeted_penalty_area_reception,player_targeted_distance_to_goal_start,player_targeted_distance_to_goal_end,player_targeted_angle_to_goal_start,player_targeted_angle_to_goal_end,player_targeted_average_speed,player_targeted_speed_avg_band_id,player_targeted_speed_avg_band,speed_difference,player_targeted_xpass_completion,player_targeted_difficult_pass_target,player_targeted_xthreat,player_targeted_dangerous,n_passing_options,n_off_ball_runs,n_passing_options_line_break,n_passing_options_first_line_break,n_passing_options_second_last_line_break,n_passing_options_last_line_break,n_passing_options_ahead,n_passing_options_dangerous_difficult,n_passing_options_dangerous_not_difficult,n_passing_options_not_dangerous_not_difficult,n_passing_options_not_dangerous_difficult,n_passing_options_at_start,n_passing_options_at_end,n_passing_options_ahead_at_start,n_passing_options_ahead_at_end,n_teammates_ahead_end,n_teammates_ahead_start,n_player_targeted_opponents_ahead_start,n_player_targeted_opponents_ahead_end,n_player_targeted_teammates_ahead_start,n_player_targeted_teammates_ahead_end,n_player_targeted_teammates_within_5m_start,n_player_targeted_teammates_within_5m_end,n_player_targeted_opponents_within_5m_start,n_player_targeted_opponents_within_5m_end,organised_defense,defensive_structure,n_defensive_lines,first_line_break,first_line_break_type_id,first_line_break_type,second_last_line_break,second_last_line_break_type_id,second_last_line_break_type,last_line_break,last_line_break_type_id,last_line_break_type,furthest_line_break_id,furthest_line_break,furthest_line_break_type_id,furthest_line_break_type,interplayer_distance,interplayer_distance_range_id,interplayer_distance_range,interplayer_distance_start,interplayer_distance_end,interplayer_distance_min,interplayer_distance_start_physical,close_at_player_possession_start,interplayer_angle,interplayer_direction_id,interplayer_direction,angle_of_engagement,goal_side_start,goal_side_end,pass_distance,pass_range_id,pass_range,pass_angle,pass_direction_id,pass_direction,pass_ahead,n_opponents_ahead_player_in_possession_pass_moment,n_opponents_ahead_pass_reception,n_opponents_bypassed,location_to_player_in_possession_id_start,location_to_player_in_possession_start,location_to_player_in_possession_id_end,location_to_player_in_possession_end,distance_to_player_in_possession_start,distance_to_player_in_possession_end,player_in_possession_x_start,player_in_possession_y_start,player_in_possession_channel_id_start,player_in_possession_channel_start,player_in_possession_third_id_start,player_in_possession_third_start,player_in_possession_penalty_area_start,player_in_possession_x_end,player_in_possession_y_end,player_in_possession_channel_id_end,player_in_possession_channel_end,player_in_possession_third_id_end,player_in_possession_third_end,player_in_possession_penalty_area_end,targeted,received,received_in_space,dangerous,difficult_pass_target,xthreat,xpass_completion,passing_option_score,predicted_passing_option,peak_passing_option_frame,passing_option_at_player_possession_start,n_simultaneous_runs,give_and_go,intended_run_behind,push_defensive_line,break_defensive_line,passing_option_at_start,n_simultaneous_passing_options,passing_option_at_pass_moment,n_opponents_ahead_end,n_opponents_ahead_start,n_opponents_overtaken,pressing_chain,pressing_chain_length,pressing_chain_end_type_id,pressing_chain_end_type,pressing_chain_index,index_in_pressing_chain,simultaneous_defensive_engagement_same_target,simultaneous_defensive_engagement_same_target_rank,affected_line_breaking_passing_option_id,affected_line_break_id,affected_line_break,affected_line_breaking_passing_option_attempted,affected_line_breaking_passing_option_xthreat,affected_line_breaking_passing_option_dangerous,affected_line_breaking_passing_option_run_subtype_id,affected_line_breaking_passing_option_run_subtype,possession_danger,beaten_by_possession,beaten_by_movement,stop_possession_danger,reduce_possession_danger,force_backward,xloss_player_possession_start,xloss_player_possession_end,xloss_player_possession_max,xshot_player_possession_start,xshot_player_possession_end,xshot_player_possession_max,is_player_possession_start_matched,is_player_possession_end_matched,is_previous_pass_matched,is_pass_reception_matched,fully_extrapolated,Sequence_ID
4769,8_937,4769,1886347,53812,53812,NaN,88:21.2,88:21.2,88,21,0.0,2,1,left_to_right,8,player_possession,NaN,NaN,133498,F. De Vries,2,LB,NaN,NaN,NaN,NaN,4177,Auckland FC,34.03,1.49,3,center,3,attacking_third,False,34.03,1.49,3,center,3,attacking_third,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,winning,2,0,427,1.0,True,True,True,True,3.0,False,7,set_play,13,defending_set_play,NaN,NaN,NaN,NaN,6.0,direct,15.0,defending_direct,3.0,free_kick_for,5.0,goal_for,True,True,0.0,42.17,1.0,forward,NaN,NaN,5.06,1.0,jogging,2.82,2.82,0.0,47.07,47.07,13.04,13.04,0.0,4.93,4.93,0.0,False,False,5.0,free_kick_reception,2.0,shot,NaN,True,False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,9.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,False,2.0

In [80]:
grouped_data

   Sequence_ID  frame_start  frame_end  lead_to_goal  player_name time_end
0          1.0        50488      50600          True    N. Moreno  83:00.0
1          2.0        53812      53812          True  F. De Vries  88:21.2