In [2]:
# imports
import pandas as pd
import requests
import numpy as np
import json

from data_ingestor_github import SkillCornerDataIngestor
di = SkillCornerDataIngestor()

In [3]:
# To load all the data
# data = di.load_data(match_id=1886347)

In [4]:
# To view the loaded data
with open (f"../../data/gold_tracking_data.json", "r") as f:
    gold_tracking_data = json.load(f)

frames = gold_tracking_data['frames']

In [9]:
start = 10
end = 20
filtered_frames = {frame_num: frames[str(frame_num)] for frame_num in range(start, end + 1) if str(frame_num) in frames}
filtered_frames

{10: {'period': 1.0,
  'players': {'x': [-39.61,
    -18.99,
    -17.05,
    -20.05,
    -1.41,
    -1.67,
    -8.8,
    -1.15,
    0.5,
    0.52,
    -6.68,
    41.59,
    21.09,
    19.3,
    20.27,
    18.81,
    9.73,
    10.29,
    6.9,
    8.65,
    1.15,
    0.44],
   'y': [0.71,
    10.85,
    -11.54,
    1.28,
    -30.06,
    29.57,
    -3.73,
    -8.46,
    -0.25,
    10.9,
    6.52,
    0.32,
    6.28,
    -5.44,
    16.89,
    -15.49,
    -7.24,
    3.47,
    14.33,
    -18.59,
    9.59,
    -8.31],
   'player_id': [34718,
    698137,
    799092,
    42510,
    51017,
    51028,
    51015,
    51046,
    23909,
    26969,
    27003,
    285188,
    51667,
    33697,
    4322,
    133498,
    23418,
    14736,
    133501,
    965685,
    38673,
    50951],
   'id': [34718,
    698137,
    799092,
    42510,
    51017,
    51028,
    51015,
    51046,
    23909,
    26969,
    27003,
    285188,
    51667,
    33697,
    4322,
    133498,
    23418,
    14736,
    133501,
    965685,
    38673,
    50951],
   'short_name': ['J. Oluwayemi',
    'I. Hughes',
    'M. Sheridan',
    'S. Wootton',
    'T. Payne',
    'S. Sutton',
    'A. Rufer',
    'P. Retre',
    'K. Barbarouses',
    'H. Ishige',
    'K. Nagasawa',
    'A. Paulsen',
    'D. Hall',
    'N. Pijnaker',
    'H. Sakai',
    'F. De Vries',
    'F. Gallegos',
    'L. Verstraete',
    'L. Rogerson',
    'L. Gillion',
    'G. May',
    'J. Brimmer'],
   'number': [1,
    15,
    27,
    4,
    6,
    19,
    14,
    8,
    7,
    9,
    25,
    12,
    23,
    4,
    2,
    15,
    28,
    6,
    27,
    14,
    10,
    22],
   'team_id': [867,
    867,
    867,
    867,
    867,
    867,
    867,
    867,
    867,
    867,
    867,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177],
   'total_time': [5400,
    5400,
    5400,
    5400,
    3610,
    5677,
    5400,
    3610,
    5400,
    5400,
    4785,
    5400,
    5400,
    5400,
    5400,
    5400,
    5400,
    1301,
    3484,
    3484,
    5400,
    4111],
   'player_role.name': ['Goalkeeper',
    'Center Back',
    'Right Center Back',
    'Left Center Back',
    'Right Wing Back',
    'Left Wing Back',
    'Left Midfield',
    'Right Midfield',
    'Right Forward',
    'Left Forward',
    'Center Forward',
    'Goalkeeper',
    'Right Center Back',
    'Left Center Back',
    'Right Back',
    'Left Back',
    'Left Midfield',
    'Right Midfield',
    'Right Winger',
    'Left Winger',
    'Center Forward',
    'Center Forward'],
   'player_role.acronym': ['GK',
    'CB',
    'RCB',
    'LCB',
    'RWB',
    'LWB',
    'LM',
    'RM',
    'RF',
    'LF',
    'CF',
    'GK',
    'RCB',
    'LCB',
    'RB',
    'LB',
    'LM',
    'RM',
    'RW',
    'LW',
    'CF',
    'CF'],
   'is_gk': [True,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    True,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False],
   'direction_player_1st_half': ['left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left'],
   'direction_player_2nd_half': ['right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right']},
  'ball': {'ball_x': 0.73, 'ball_y': -0.93, 'ball_z': 0.26},
  'events': []},
 11: {'period': 1.0,
  'players': {'x': [-39.83,
    -18.97,
    -17.08,
    -20.26,
    -1.25,
    -1.41,
    -8.86,
    -1.06,
    0.51,
    0.49,
    -6.83,
    41.74,
    21.19,
    19.39,
    20.46,
    18.89,
    9.65,
    10.09,
    6.92,
    8.6,
    1.03,
    0.37],
   'y': [0.67,
    10.9,
    -11.58,
    1.22,
    -29.88,
    29.6,
    -3.72,
    -8.48,
    -0.26,
    10.86,
    6.45,
    0.31,
    6.24,
    -5.63,
    16.93,
    -15.55,
    -7.31,
    3.44,
    14.37,
    -18.71,
    9.42,
    -8.32],
   'player_id': [34718,
    698137,
    799092,
    42510,
    51017,
    51028,
    51015,
    51046,
    23909,
    26969,
    27003,
    285188,
    51667,
    33697,
    4322,
    133498,
    23418,
    14736,
    133501,
    965685,
    38673,
    50951],
   'id': [34718,
    698137,
    799092,
    42510,
    51017,
    51028,
    51015,
    51046,
    23909,
    26969,
    27003,
    285188,
    51667,
    33697,
    4322,
    133498,
    23418,
    14736,
    133501,
    965685,
    38673,
    50951],
   'short_name': ['J. Oluwayemi',
    'I. Hughes',
    'M. Sheridan',
    'S. Wootton',
    'T. Payne',
    'S. Sutton',
    'A. Rufer',
    'P. Retre',
    'K. Barbarouses',
    'H. Ishige',
    'K. Nagasawa',
    'A. Paulsen',
    'D. Hall',
    'N. Pijnaker',
    'H. Sakai',
    'F. De Vries',
    'F. Gallegos',
    'L. Verstraete',
    'L. Rogerson',
    'L. Gillion',
    'G. May',
    'J. Brimmer'],
   'number': [1,
    15,
    27,
    4,
    6,
    19,
    14,
    8,
    7,
    9,
    25,
    12,
    23,
    4,
    2,
    15,
    28,
    6,
    27,
    14,
    10,
    22],
   'team_id': [867,
    867,
    867,
    867,
    867,
    867,
    867,
    867,
    867,
    867,
    867,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177],
   'total_time': [5400,
    5400,
    5400,
    5400,
    3610,
    5677,
    5400,
    3610,
    5400,
    5400,
    4785,
    5400,
    5400,
    5400,
    5400,
    5400,
    5400,
    1301,
    3484,
    3484,
    5400,
    4111],
   'player_role.name': ['Goalkeeper',
    'Center Back',
    'Right Center Back',
    'Left Center Back',
    'Right Wing Back',
    'Left Wing Back',
    'Left Midfield',
    'Right Midfield',
    'Right Forward',
    'Left Forward',
    'Center Forward',
    'Goalkeeper',
    'Right Center Back',
    'Left Center Back',
    'Right Back',
    'Left Back',
    'Left Midfield',
    'Right Midfield',
    'Right Winger',
    'Left Winger',
    'Center Forward',
    'Center Forward'],
   'player_role.acronym': ['GK',
    'CB',
    'RCB',
    'LCB',
    'RWB',
    'LWB',
    'LM',
    'RM',
    'RF',
    'LF',
    'CF',
    'GK',
    'RCB',
    'LCB',
    'RB',
    'LB',
    'LM',
    'RM',
    'RW',
    'LW',
    'CF',
    'CF'],
   'is_gk': [True,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    True,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False],
   'direction_player_1st_half': ['left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left'],
   'direction_player_2nd_half': ['right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right']},
  'ball': {'ball_x': 0.28, 'ball_y': -0.81, 'ball_z': 0.34},
  'events': []},
 12: {'period': 1.0,
  'players': {'x': [-40.03,
    -18.95,
    -17.12,
    -20.43,
    -1.06,
    -1.14,
    -8.91,
    -0.95,
    0.53,
    0.48,
    -6.94,
    41.87,
    21.27,
    19.48,
    20.63,
    18.96,
    9.56,
    9.89,
    6.94,
    8.54,
    0.88,
    0.29],
   'y': [0.64,
    10.93,
    -11.62,
    1.16,
    -29.74,
    29.62,
    -3.71,
    -8.51,
    -0.28,
    10.82,
    6.39,
    0.29,
    6.19,
    -5.81,
    16.96,
    -15.62,
    -7.38,
    3.4,
    14.41,
    -18.84,
    9.25,
    -8.3],
   'player_id': [34718,
    698137,
    799092,
    42510,
    51017,
    51028,
    51015,
    51046,
    23909,
    26969,
    27003,
    285188,
    51667,
    33697,
    4322,
    133498,
    23418,
    14736,
    133501,
    965685,
    38673,
    50951],
   'id': [34718,
    698137,
    799092,
    42510,
    51017,
    51028,
    51015,
    51046,
    23909,
    26969,
    27003,
    285188,
    51667,
    33697,
    4322,
    133498,
    23418,
    14736,
    133501,
    965685,
    38673,
    50951],
   'short_name': ['J. Oluwayemi',
    'I. Hughes',
    'M. Sheridan',
    'S. Wootton',
    'T. Payne',
    'S. Sutton',
    'A. Rufer',
    'P. Retre',
    'K. Barbarouses',
    'H. Ishige',
    'K. Nagasawa',
    'A. Paulsen',
    'D. Hall',
    'N. Pijnaker',
    'H. Sakai',
    'F. De Vries',
    'F. Gallegos',
    'L. Verstraete',
    'L. Rogerson',
    'L. Gillion',
    'G. May',
    'J. Brimmer'],
   'number': [1,
    15,
    27,
    4,
    6,
    19,
    14,
    8,
    7,
    9,
    25,
    12,
    23,
    4,
    2,
    15,
    28,
    6,
    27,
    14,
    10,
    22],
   'team_id': [867,
    867,
    867,
    867,
    867,
    867,
    867,
    867,
    867,
    867,
    867,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177],
   'total_time': [5400,
    5400,
    5400,
    5400,
    3610,
    5677,
    5400,
    3610,
    5400,
    5400,
    4785,
    5400,
    5400,
    5400,
    5400,
    5400,
    5400,
    1301,
    3484,
    3484,
    5400,
    4111],
   'player_role.name': ['Goalkeeper',
    'Center Back',
    'Right Center Back',
    'Left Center Back',
    'Right Wing Back',
    'Left Wing Back',
    'Left Midfield',
    'Right Midfield',
    'Right Forward',
    'Left Forward',
    'Center Forward',
    'Goalkeeper',
    'Right Center Back',
    'Left Center Back',
    'Right Back',
    'Left Back',
    'Left Midfield',
    'Right Midfield',
    'Right Winger',
    'Left Winger',
    'Center Forward',
    'Center Forward'],
   'player_role.acronym': ['GK',
    'CB',
    'RCB',
    'LCB',
    'RWB',
    'LWB',
    'LM',
    'RM',
    'RF',
    'LF',
    'CF',
    'GK',
    'RCB',
    'LCB',
    'RB',
    'LB',
    'LM',
    'RM',
    'RW',
    'LW',
    'CF',
    'CF'],
   'is_gk': [True,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    True,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False],
   'direction_player_1st_half': ['left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left'],
   'direction_player_2nd_half': ['right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right']},
  'ball': {'ball_x': -0.59, 'ball_y': -0.79, 'ball_z': 0.25},
  'events': [{'event_id': '8_0',
    'index': 0,
    'frame_start': 12,
    'frame_end': 12,
    'attacking_side': 'left_to_right',
    'event_type_id': 8,
    'event_type': 'player_possession',
    'event_subtype_id': nan,
    'event_subtype': nan,
    'player_id': 23909,
    'player_name': 'K. Barbarouses',
    'team_id': 867,
    'x_start': 0.53,
    'y_start': -0.28,
    'x_end': 0.53,
    'y_end': -0.28}]},
 13: {'period': 1.0,
  'players': {'x': [-40.21,
    -18.94,
    -17.16,
    -20.59,
    -0.86,
    -0.88,
    -8.96,
    -0.82,
    0.56,
    0.51,
    -7.02,
    41.99,
    21.32,
    19.57,
    20.77,
    19.03,
    9.48,
    9.7,
    6.97,
    8.48,
    0.68,
    0.18],
   'y': [0.61,
    10.96,
    -11.68,
    1.1,
    -29.63,
    29.63,
    -3.69,
    -8.55,
    -0.31,
    10.79,
    6.34,
    0.28,
    6.14,
    -5.99,
    16.98,
    -15.69,
    -7.44,
    3.36,
    14.45,
    -18.97,
    9.08,
    -8.26],
   'player_id': [34718,
    698137,
    799092,
    42510,
    51017,
    51028,
    51015,
    51046,
    23909,
    26969,
    27003,
    285188,
    51667,
    33697,
    4322,
    133498,
    23418,
    14736,
    133501,
    965685,
    38673,
    50951],
   'id': [34718,
    698137,
    799092,
    42510,
    51017,
    51028,
    51015,
    51046,
    23909,
    26969,
    27003,
    285188,
    51667,
    33697,
    4322,
    133498,
    23418,
    14736,
    133501,
    965685,
    38673,
    50951],
   'short_name': ['J. Oluwayemi',
    'I. Hughes',
    'M. Sheridan',
    'S. Wootton',
    'T. Payne',
    'S. Sutton',
    'A. Rufer',
    'P. Retre',
    'K. Barbarouses',
    'H. Ishige',
    'K. Nagasawa',
    'A. Paulsen',
    'D. Hall',
    'N. Pijnaker',
    'H. Sakai',
    'F. De Vries',
    'F. Gallegos',
    'L. Verstraete',
    'L. Rogerson',
    'L. Gillion',
    'G. May',
    'J. Brimmer'],
   'number': [1,
    15,
    27,
    4,
    6,
    19,
    14,
    8,
    7,
    9,
    25,
    12,
    23,
    4,
    2,
    15,
    28,
    6,
    27,
    14,
    10,
    22],
   'team_id': [867,
    867,
    867,
    867,
    867,
    867,
    867,
    867,
    867,
    867,
    867,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177],
   'total_time': [5400,
    5400,
    5400,
    5400,
    3610,
    5677,
    5400,
    3610,
    5400,
    5400,
    4785,
    5400,
    5400,
    5400,
    5400,
    5400,
    5400,
    1301,
    3484,
    3484,
    5400,
    4111],
   'player_role.name': ['Goalkeeper',
    'Center Back',
    'Right Center Back',
    'Left Center Back',
    'Right Wing Back',
    'Left Wing Back',
    'Left Midfield',
    'Right Midfield',
    'Right Forward',
    'Left Forward',
    'Center Forward',
    'Goalkeeper',
    'Right Center Back',
    'Left Center Back',
    'Right Back',
    'Left Back',
    'Left Midfield',
    'Right Midfield',
    'Right Winger',
    'Left Winger',
    'Center Forward',
    'Center Forward'],
   'player_role.acronym': ['GK',
    'CB',
    'RCB',
    'LCB',
    'RWB',
    'LWB',
    'LM',
    'RM',
    'RF',
    'LF',
    'CF',
    'GK',
    'RCB',
    'LCB',
    'RB',
    'LB',
    'LM',
    'RM',
    'RW',
    'LW',
    'CF',
    'CF'],
   'is_gk': [True,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    True,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False],
   'direction_player_1st_half': ['left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left'],
   'direction_player_2nd_half': ['right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'right_to_left',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right',
    'left_to_right']},
  'ball': {'ball_x': -2.1, 'ball_y': -0.54, 'ball_z': 0.24},
  'events': []},
 14: {'period': 1.0,
  'players': {'x': [-40.37,
    -18.94,
    -17.21,
    -20.71,
    -0.65,
    -0.61,
    -9.01,
    -0.67,
    0.6,
    0.57,
    -7.06,
    42.1,
    21.36,
    19.64,
    20.89,
    19.1,
    9.39,
    9.51,
    6.99,
    8.4,
    0.45,
    0.06],
   'y': [0.58,
    10.98,
    -11.74,
    1.05,
    -29.55,
    29.65,
    -3.67,
    -8.59,
    -0.35,
    10.77,
    6.29,
    0.27,
    6.08,
    -6.17,
    17.0,
    -15.78,
    -7.5,
    3.31,
    14.49,
    -19.09,
    8.91,
    -8.21],
   'player_id': [34718,
    698137,
    799092,
    42510,
    51017,
    51028,
    51015,
    51046,
    23909,
    26969,
    27003,
    285188,
    51667,
    33697,
    4322,
    133498,
    23418,
    14736,
    133501,
    965685,
    38673,
    50951],
   'id': [34718,
    698137,
    799092,
    42510,
    51017,
    51028,
    51015,
    51046,
    23909,
    26969,
    27003,
    285188,
    51667,
    33697,
    4322,
    133498,
    23418,
    14736,
    133501,
    965685,
    38673,
    50951],
   'short_name': ['J. Oluwayemi',
    'I. Hughes',
    'M. Sheridan',
    'S. Wootton',
    'T. Payne',
    'S. Sutton',
    'A. Rufer',
    'P. Retre',
    'K. Barbarouses',
    'H. Ishige',
    'K. Nagasawa',
    'A. Paulsen',
    'D. Hall',
    'N. Pijnaker',
    'H. Sakai',
    'F. De Vries',
    'F. Gallegos',
    'L. Verstraete',
    'L. Rogerson',
    'L. Gillion',
    'G. May',
    'J. Brimmer'],
   'number': [1,
    15,
    27,
    4,
    6,
    19,
    14,
    8,
    7,
    9,
    25,
    12,
    23,
    4,
    2,
    15,
    28,
    6,
    27,
    14,
    10,
    22],
   'team_id': [867,
    867,
    867,
    867,
    867,
    867,
    867,
    867,
    867,
    867,
    867,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177,
    4177],
   'total_time': [5400,
    5400,
    5400,
    5400,
    3610,
    5677,
    5400,
    3610,
    5400,
    5400,
    4785,
    5400,
    5400,
    5400,
    5400,
    5400,
    5400,
    1301,
    3484,
    3484,
    5400,
    4111],
   'player_role.name': ['Goalkeeper',
    'Center Back',
    'Right Center Back',
    'Left Center Back',
    'Right Wing Back',
    'Left Wing Back',
    'Left Midfield',
    'Right Midfield',
    'Right Forward',
    'Left Forward',
    'Center Forward',
    'Goalkeeper',
    'Right Center Back',
    'Left Center Back',
    'Right Back',
    'Left Back',
    'Left Midfield',
    'Right Midfield',
    'Right Winger',
    'Left Winger',
    'Center Forward',
    'Center Forward'],
   'player_role.acronym': ['GK',
    'CB',
    'RCB',
    'LCB',
    'RWB',
    'LWB',
    'LM',
    'RM',
    'RF',
    'LF',
    'CF',
    'GK',
    'RCB',
    'LCB',
    'RB',
    'LB',
    'LM',
    'RM',
    'RW',
    'LW',
    'CF',
    'CF'],
   'is_gk': [True,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    True,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False],

In [4]:
for frame_number, frame_data in frames.items():
    if len(frames[frame_number]['events']) > 0:
        print(f"Frame {frame_number} has events: {frame_data['events']}")

Frame 28 has events: [{'event_id': '8_0', 'index': 0, 'frame_start': 28, 'frame_end': 28, 'attacking_side': 'left_to_right', 'event_type_id': 8, 'event_type': 'player_possession', 'event_subtype_id': nan, 'event_subtype': nan, 'player_id': 966120, 'player_name': 'B. Gibson', 'team_id': 1805, 'x_start': 0.73, 'y_start': 0.49, 'x_end': 0.73, 'y_end': 0.49}]
Frame 48 has events: [{'event_id': '8_1', 'index': 1, 'frame_start': 48, 'frame_end': 58, 'attacking_side': 'left_to_right', 'event_type_id': 8, 'event_type': 'player_possession', 'event_subtype_id': nan, 'event_subtype': nan, 'player_id': 51649, 'player_name': 'A. Šušnjar', 'team_id': 1805, 'x_start': -22.31, 'y_start': 1.22, 'x_end': -22.21, 'y_end': 2.7}]
Frame 49 has events: [{'event_id': '8_1', 'index': 1, 'frame_start': 48, 'frame_end': 58, 'attacking_side': 'left_to_right', 'event_type_id': 8, 'event_type': 'player_possession', 'event_subtype_id': nan, 'event_subtype': nan, 'player_id': 51649, 'player_name': 'A. Šušnjar', 'team_id': 1805, 'x_start': -22.31, 'y_start': 1.22, 'x_end': -22.21, 'y_end': 2.7}]
Frame 50 has events: [{'event_id': '8_1', 'index': 1, 'frame_start': 48, 'frame_end': 58, 'attacking_side': 'left_to_right', 'event_type_id': 8, 'event_type': 'player_possession', 'event_subtype_id': nan, 'event_subtype': nan, 'player_id': 51649, 'player_name': 'A. Šušnjar', 'team_id': 1805, 'x_start': -22.31, 'y_start': 1.22, 'x_end': -22.21, 'y_end': 2.7}]
Frame 51 has events: [{'event_id': '8_1', 'index': 1, 'frame_start': 48, 'frame_end': 58, 'attacking_side': 'left_to_right', 'event_type_id': 8, 'event_type': 'player_possession', 'event_subtype_id': nan, 'event_subtype': nan, 'player_id': 51649, 'player_name': 'A. Šušnjar', 'team_id': 1805, 'x_start': -22.31, 'y_start': 1.22, 'x_end': -22.21, 'y_end': 2.7}]
Frame 52 has events: [{'event_id': '8_1', 'index': 1, 'frame_start': 48, 'frame_end': 58, 'attacking_side': 'left_to_right', 'event_type_id': 8, 'event_type': 'player_possession', 'event_subtype_id': nan, 'event_subtype': nan, 'player_id': 51649, 'player_name': 'A. Šušnjar', 'team_id': 1805, 'x_start': -22.31, 'y_start': 1.22, 'x_end': -22.21, 'y_end': 2.7}]
Frame 53 has events: [{'event_id': '8_1', 'index': 1, 'frame_start': 48, 'frame_end': 58, 'attacking_side': 'left_to_right', 'event_type_id': 8, 'event_type': 'player_possession', 'event_subtype_id': nan, 'event_subtype': nan, 'player_id': 51649, 'player_name': 'A. Šušnjar', 'team_id': 1805, 'x_start': -22.31, 'y_start': 1.22, 'x_end': -22.21, 'y_end': 2.7}]
Frame 54 has events: [{'event_id': '8_1', 'index': 1, 'frame_start': 48, 'frame_end': 58, 'attacking_side': 'left_to_right', 'event_type_id': 8, 'event_type': 'player_possession', 'event_subtype_id': nan, 'event_subtype': nan, 'player_id': 51649, 'player_name': 'A. Šušnjar', 'team_id': 1805, 'x_start': -22.31, 'y_start': 1.22, 'x_end': -22.21, 'y_end': 2.7}]
Frame 55 has events: [{'event_id': '8_1', 'index': 1, 'frame_start': 48, 'frame_end': 58, 'attacking_side': 'left_to_right', 'event_type_id': 8, 'event_type': 'player_possession', 'event_subtype_id': nan, 'event_subtype': nan, 'player_id': 51649, 'player_name': 'A. Šušnjar', 'team_id': 1805, 'x_start': -22.31, 'y_start': 1.22, 'x_end': -22.21, 'y_end': 2.7}]
Frame 56 has events: [{'event_id': '8_1', 'index': 1, 'frame_start': 48, 'frame_end': 58, 'attacking_side': 'left_to_right', 'event_type_id': 8, 'event_type': 'player_possession', 'event_subtype_id': nan, 'event_subtype': nan, 'player_id': 51649, 'player_name': 'A. Šušnjar', 'team_id': 1805, 'x_start': -22.31, 'y_start': 1.22, 'x_end': -22.21, 'y_end': 2.7}]
Frame 57 has events: [{'event_id': '8_1', 'index': 1, 'frame_start': 48, 'frame_end': 58, 'attacking_side': 'left_to_right', 'event_type_id': 8, 'event_type': 'player_possession', 'event_subtype_id': nan, 'event_subtype': nan, 'player_id': 51649, 'player_name': 'A. Šušnjar', 'team_id': 1805, 'x_start': -22.31, 'y_start': 1.22, 'x_end': -22.21, 'y_end': 2.7}]
Frame 58 has events: [{'event_id': '8_1', 'index': 1, 'frame_start': 48, 'frame_end': 58, 'attacking_side': 'left_to_right', 'event_type_id': 8, 'event_type': 'player_possession', 'event_subtype_id': nan, 'event_subtype': nan, 'player_id': 51649, 'player_name': 'A. Šušnjar', 'team_id': 1805, 'x_start': -22.31, 'y_start': 1.22, 'x_end': -22.21, 'y_end': 2.7}]
Frame 72 has events: [{'event_id': '8_2', 'index': 5, 'frame_start': 72, 'frame_end': 89, 'attacking_side': 'left_to_right', 'event_type_id': 8, 'event_type': 'player_possession', 'event_subtype_id': nan, 'event_subtype': nan, 'player_id': 735578, 'player_name': 'M. Natta', 'team_id': 1805, 'x_start': -17.6, 'y_start': 20.17, 'x_end': -10.75, 'y_end': 24.18}]
Frame 73 has events: [{'event_id': '8_2', 'index': 5, 'frame_start': 72, 'frame_end': 89, 'attacking_side': 'left_to_right', 'event_type_id': 8, 'event_type': 'player_possession', 'event_subtype_id': nan, 'event_subtype': nan, 'player_id': 735578, 'player_name': 'M. Natta', 'team_id': 1805, 'x_start': -17.6, 'y_start': 20.17, 'x_end': -10.75, 'y_end': 24.18}]
Frame 74 has events: [{'event_id': '8_2', 'index': 5, 'frame_start': 72, 'frame_end': 89, 'attacking_side': 'left_to_right', 'event_type_id': 8, 'event_type': 'player_possession', 'event_subtype_id': nan, 'event_subtype': nan, 'player_id': 735578, 'player_name': 'M. Natta', 'team_id': 1805, 'x_start': -17.6, 'y_start': 20.17, 'x_end': -10.75, 'y_end': 24.18}]
Frame 75 has events: [{'event_id': '8_2', 'index': 5, 'frame_start': 72, 'frame_end': 89, 'attacking_side': 'left_to_right', 'event_type_id': 8, 'event_type': 'player_possession', 'event_subtype_id': nan, 'event_subtype': nan, 'player_id': 735578, 'player_name': 'M. Natta', 'team_id': 1805, 'x_start': -17.6, 'y_start': 20.17, 'x_end': -10.75, 'y_end': 24.18}]
Frame 76 has events: [{'event_id': '8_2', 'index': 5, 'frame_start': 72, 'frame_end': 89, 'attacking_side': 'left_to_right', 'event_type_id': 8, 'event_type': 'player_possession', 'event_subtype_id': nan, 'event_subtype': nan, 'player_id': 735578, 'player_name': 'M. Natta', 'team_id': 1805, 'x_start': -17.6, 'y_start': 20.17, 'x_end': -10.75, 'y_end': 24.18}]
Frame 77 has events: [{'event_id': '8_2', 'index': 5, 'frame_start': 72, 'frame_end': 89, 'attacking_side': 'left_to_right', 'event_type_id': 8, 'event_type': 'player_possession', 'event_subtype_id': nan, 'event_subtype': nan, 'player_id': 735578, 'player_name': 'M. Natta', 'team_id': 1805, 'x_start': -17.6, 'y_start': 20.17, 'x_end': -10.75, 'y_end': 24.18}]
Frame 78 has events: [{'event_id': '8_2', 'index': 5, 'frame_start': 72, 'frame_end': 89, 'attacking_side': 'left_to_right', 'event_type_id': 8, 'event_type': 'player_possession', 'event_subtype_id': nan, 'event_subtype': nan, 'player_id': 735578, 'player_name': 'M. Natta', 'team_id': 1805, 'x_start': -17.6, 'y_start': 20.17, 'x_end': -10.75, 'y_end': 24.18}]
Frame 79 has events: [{'event_id': '8_2', 'index': 5, 'frame_start': 72, 'frame_end': 89, 'attacking_side': 'left_to_right', 'event_type_id': 8, 'event_type': 'player_possession', 'event_subtype_id': nan, 'event_subtype': nan, 'player_id': 735578, 'player_name': 'M. Natta', 'team_id': 1805, 'x_start': -17.6, 'y_start': 20.17, 'x_end': -10.75, 'y_end': 24.18}]
Frame 80 has events: [{'event_id': '8_2', 'index': 5, 'frame_start': 72, 'frame_end': 89, 'attacking_side': 'left_to_right', 'event_type_id': 8, 'event_type': 'player_possession', 'event_subtype_id': nan, 'event_subtype': nan, 'player_id': 735578, 'player_name': 'M. Natta', 'team_id': 1805, 'x_start': -17.6, 'y_start': 20.17, 'x_end': -10.75, 'y_end': 24.18}]
Frame 81 has events: [{'event_id': '8_2', 'index': 5, 'frame_start': 72, 'frame_end': 89, 'attacking_side': 'left_to_right', 'event_type_id': 8, 'event_type': 'player_possession', 'event_subtype_id': nan, 'event_subtype': nan, 'player_id': 735578, 'player_name': 'M. Natta', 'team_id': 1805, 'x_start': -17.6, 'y_start': 20.17, 'x_end': -10.75, 'y_end': 24.18}]
Frame 82 has events: [{'event_id': '8_2', 'index': 5, 'frame_start': 72, 'frame_end': 89, 'attacking_side': 'left_to_right', 'event_type_id': 8, 'event_type': 'player_possession', 'event_subtype_id': nan, 'event_subtype': nan, 'player_id': 735578, 'player_name': 'M. Natta', 'team_id': 1805, 'x_start': -17.6, 'y_start': 20.17, 'x_end': -10.75, 'y_end': 24.18}]
Frame 83 has events: [{'event_id': '8_2', 'index': 5, 'frame_start': 72, 'frame_end': 89, 'attacking_side': 'left_to_right', 'event_type_id': 8, 'event_type': 'player_possession', 'event_subtype_id': nan, 'event_subtype': nan, 'player_id': 735578, 'player_name': 'M. Natta', 'team_id': 1805, 'x_start': -17.6, 'y_start': 20.17, 'x_end': -10.75, 'y_end': 24.18}]
Frame 84 has events: [{'event_id': '8_2', 'index': 5, 'frame_start': 72, 'frame_end': 89, 'attacking_side': 'left_to_right', 'event_type_id': 8, 'event_type': 'player_possession', 'event_subtype_id': nan, 'event_subtype': nan, 'player_id': 735578, 'player_name': 'M. Natta', 'team_id': 1805, 'x_start': -17.6, 'y_start': 20.17, 'x_end': -10.75, 'y_end': 24.18}]
Frame 85 has events: [{'event_id': '8_2', 'index': 5, 'frame_start': 72, 'frame_end': 89, 'attacking_side': 'left_to_right', 'event_type_id': 8, 'event_type': 'player_possession', 'event_subtype_id': nan, 'event_subtype': nan, 'player_id': 735578, 'player_name': 'M. Natta', 'team_id': 1805, 'x_start': -17.6, 'y_start': 20.17, 'x_end': -10.75, 'y_end': 24.18}]
Frame 86 has events: [{'event_id': '8_2', 'index': 5, 'frame_start': 72, 'frame_end': 89, 'attacking_side': 'left_to_right', 'event_type_id': 8, 'event_type': 'player_possession', 'event_subtype_id': nan, 'event_subtype': nan, 'player_id': 735578, 'player_name': 'M. Natta', 'team_id': 1805, 'x_start': -17.6, 'y_start': 20.17, 'x_end': -10.75, 'y_end': 24.18}]
Frame 87 has events: [{'event_id': '8_2', 'index': 5, 'frame_start': 72, 'frame_end': 89, 'attacking_side': 'left_to_right', 'event_type_id': 8, 'event_type': 'player_possession', 'event_subtype_id': nan, 'event_subtype': nan, 'player_id': 735578, 'player_name': 'M. Natta', 'team_id': 1805, 'x_start': -17.6, 'y_start': 20.17, 'x_end': -10.75, 'y_end': 24.18}]
Frame 88 has events: [{'event_id': '8_2', 'index': 5, 'frame_start': 72, 'frame_end': 89, 'attacking_side': 'left_to_right', 'event_type_id': 8, 'event_type': 'player_possession', 'event_subtype_id': nan, 'event_subtype': nan, 'player_id': 735578, 'player_name': 'M. Natta', 'team_id': 1805, 'x_start': -17.6, 'y_start': 20.17, 'x_end': -10.75, 'y_end': 24.18}]
Frame 89 has events: [{'event_id': '8_2', 'index': 5, 'frame_start': 72, 'frame_end': 89, 'attacking_side': 'left_to_right', 'event_type_id': 8, 'event_type': 'player_possession', 'event_subtype_id': nan, 'event_subtype': nan, 'player_id': 735578, 'player_name': 'M. Natta', 'team_id': 1805, 'x_start': -17.6, 'y_start': 20.17, 'x_end': -10.75, 'y_end': 24.18}]
Frame 90 has events: [{'event_id': '1_0', 'index': 10, 'frame_start': 74, 'frame_end': 90, 'attacking_side': 'left_to_right', 'event_type_id': 1, 'event_type': 'off_ball_run', 'event_subtype_id': 7.0, 'event_subtype': 'pulling_wide', 'player_id': 735573, 'player_name': 'T. Aquilina', 'team_id': 1805, 'x_start': 7.31, 'y_start': 20.4, 'x_end': 6.94, 'y_end': 28.05}]
Frame 91 has events: [{'event_id': '1_1', 'index': 12, 'frame_start': 81, 'frame_end': 96, 'attacking_side': 'left_to_right', 'event_type_id': 1, 'event_type': 'off_ball_run', 'event_subtype_id': 2.0, 'event_subtype': 'coming_short', 'player_id': 795507, 'player_name': 'L. Bayliss', 'team_id': 1805, 'x_start': 14.25, 'y_start': 12.68, 'x_end': 10.46, 'y_end': 19.53}]
Frame 92 has events: [{'event_id': '1_1', 'index': 12, 'frame_start': 81, 'frame_end': 96, 'attacking_side': 'left_to_right', 'event_type_id': 1, 'event_type': 'off_ball_run', 'event_subtype_id': 2.0, 'event_subtype': 'coming_short', 'player_id': 795507, 'player_name': 'L. Bayliss', 'team_id': 1805, 'x_start': 14.25, 'y_start': 12.68, 'x_end': 10.46, 'y_end': 19.53}]
Frame 93 has events: [{'event_id': '1_1', 'index': 12, 'frame_start': 81, 'frame_end': 96, 'attacking_side': 'left_to_right', 'event_type_id': 1, 'event_type': 'off_ball_run', 'event_subtype_id': 2.0, 'event_subtype': 'coming_short', 'player_id': 795507, 'player_name': 'L. Bayliss', 'team_id': 1805, 'x_start': 14.25, 'y_start': 12.68, 'x_end': 10.46, 'y_end': 19.53}]
Frame 94 has events: [{'event_id': '1_1', 'index': 12, 'frame_start': 81, 'frame_end': 96, 'attacking_side': 'left_to_right', 'event_type_id': 1, 'event_type': 'off_ball_run', 'event_subtype_id': 2.0, 'event_subtype': 'coming_short', 'player_id': 795507, 'player_name': 'L. Bayliss', 'team_id': 1805, 'x_start': 14.25, 'y_start': 12.68, 'x_end': 10.46, 'y_end': 19.53}]
Frame 95 has events: [{'event_id': '1_1', 'index': 12, 'frame_start': 81, 'frame_end': 96, 'attacking_side': 'left_to_right', 'event_type_id': 1, 'event_type': 'off_ball_run', 'event_subtype_id': 2.0, 'event_subtype': 'coming_short', 'player_id': 795507, 'player_name': 'L. Bayliss', 'team_id': 1805, 'x_start': 14.25, 'y_start': 12.68, 'x_end': 10.46, 'y_end': 19.53}]
Frame 96 has events: [{'event_id': '1_1', 'index': 12, 'frame_start': 81, 'frame_end': 96, 'attacking_side': 'left_to_right', 'event_type_id': 1, 'event_type': 'off_ball_run', 'event_subtype_id': 2.0, 'event_subtype': 'coming_short', 'player_id': 795507, 'player_name': 'L. Bayliss', 'team_id': 1805, 'x_start': 14.25, 'y_start': 12.68, 'x_end': 10.46, 'y_end': 19.53}]
Frame 97 has events: [{'event_id': '1_2', 'index': 13, 'frame_start': 82, 'frame_end': 99, 'attacking_side': 'left_to_right', 'event_type_id': 1, 'event_type': 'off_ball_run', 'event_subtype_id': 1.0, 'event_subtype': 'behind', 'player_id': 966120, 'player_name': 'B. Gibson', 'team_id': 1805, 'x_start': 15.51, 'y_start': 6.38, 'x_end': 19.96, 'y_end': 13.36}]
Frame 98 has events: [{'event_id': '1_2', 'index': 13, 'frame_start': 82, 'frame_end': 99, 'attacking_side': 'left_to_right', 'event_type_id': 1, 'event_type': 'off_ball_run', 'event_subtype_id': 1.0, 'event_subtype': 'behind', 'player_id': 966120, 'player_name': 'B. Gibson', 'team_id': 1805, 'x_start': 15.51, 'y_start': 6.38, 'x_end': 19.96, 'y_end': 13.36}]
Frame 99 has events: [{'event_id': '1_2', 'index': 13, 'frame_start': 82, 'frame_end': 99, 'attacking_side': 'left_to_right', 'event_type_id': 1, 'event_type': 'off_ball_run', 'event_subtype_id': 1.0, 'event_subtype': 'behind', 'player_id': 966120, 'player_name': 'B. Gibson', 'team_id': 1805, 'x_start': 15.51, 'y_start': 6.38, 'x_end': 19.96, 'y_end': 13.36}]
Frame 202 has events: [{'event_id': '8_3', 'index': 14, 'frame_start': 202, 'frame_end': 229, 'attacking_side': 'right_to_left', 'event_type_id': 8, 'event_type': 'player_possession', 'event_subtype_id': nan, 'event_subtype': nan, 'player_id': 33697, 'player_name': 'N. Pijnaker', 'team_id': 4177, 'x_start': -27.84, 'y_start': 6.4, 'x_end': -23.05, 'y_end': 13.87}]
Frame 203 has events: [{'event_id': '8_3', 'index': 14, 'frame_start': 202, 'frame_end': 229, 'attacking_side': 'right_to_left', 'event_type_id': 8, 'event_type': 'player_possession', 'event_subtype_id': nan, 'event_subtype': nan, 'player_id': 33697, 'player_name': 'N. Pijnaker', 'team_id': 4177, 'x_start': -27.84, 'y_start': 6.4, 'x_end': -23.05, 'y_end': 13.87}]
Frame 204 has events: [{'event_id': '8_3', 'index': 14, 'frame_start': 202, 'frame_end': 229, 'attacking_side': 'right_to_left', 'event_type_id': 8, 'event_type': 'player_possession', 'event_subtype_id': nan, 'event_subtype': nan, 'player_id': 33697, 'player_name': 'N. Pijnaker', 'team_id': 4177, 'x_start': -27.84, 'y_start': 6.4, 'x_end': -23.05, 'y_end': 13.87}]
Frame 205 has events: [{'event_id': '8_3', 'index': 14, 'frame_start': 202, 'frame_end': 229, 'attacking_side': 'right_to_left', 'event_type_id': 8, 'event_type': 'player_possession', 'event_subtype_id': nan, 'event_subtype': nan, 'player_id': 33697, 'player_name': 'N. Pijnaker', 'team_id': 4177, 'x_start': -27.84, 'y_start': 6.4, 'x_end': -23.05, 'y_end': 13.87}]
Frame 206 has events: [{'event_id': '8_3', 'index': 14, 'frame_start': 202, 'frame_end': 229, 'attacking_side': 'right_to_left', 'event_type_id': 8, 'event_type': 'player_possession', 'event_subtype_id': nan, 'event_subtype': nan, 'player_id': 33697, 'player_name': 'N. Pijnaker', 'team_id': 4177, 'x_start': -27.84, 'y_start': 6.4, 'x_end': -23.05, 'y_end': 13.87}]
Frame 207 has events: [{'event_id': '8_3', 'index': 14, 'frame_start': 202, 'frame_end': 229, 'attacking_side': 'right_to_left', 'event_type_id': 8, 'event_type': 'player_possession', 'event_subtype_id': nan, 'event_subtype': nan, 'player_id': 33697, 'player_name': 'N. Pijnaker', 'team_id': 4177, 'x_start': -27.84, 'y_start': 6.4, 'x_end': -23.05, 'y_end': 13.87}]
Frame 208 has events: [{'event_id': '8_3', 'index': 14, 'frame_start': 202, 'frame_end': 229, 'attacking_side': 'right_to_left', 'event_type_id': 8, 'event_type': 'player_possession', 'event_subtype_id': nan, 'event_subtype': nan, 'player_id': 33697, 'player_name': 'N. Pijnaker', 'team_id': 4177, 'x_start': -27.84, 'y_start': 6.4, 'x_end': -23.05, 'y_end': 13.87}]
Frame 209 has events: [{'event_id': '8_3', 'index': 14, 'frame_start': 202, 'frame_end': 229, 'attacking_side': 'right_to_left', 'event_type_id': 8, 'event_type': 'player_possession', 'event_subtype_id': nan, 'event_subtype': nan, 'player_id': 33697, 'player_name': 'N. Pijnaker', 'team_id': 4177, 'x_start': -27.84, 'y_start': 6.4, 'x_end': -23.05, 'y_end': 13.87}]
Frame 210 has events: [{'event_id': '8_3', 'index': 14, 'frame_start': 202, 'frame_end': 229, 'attacking_side': 'right_to_left', 'event_type_id': 8, 'event_type': 'player_possession', 'event_subtype_id': nan, 'event_subtype': nan, 'player_id': 33697, 'player_name': 'N. Pijnaker', 'team_id': 4177, 'x_start': -27.84, 'y_start': 6.4, 'x_end': -23.05, 'y_end': 13.87}]
Frame 211 has events: [{'event_id': '8_3', 'index': 14, 'frame_start': 202, 'frame_end': 229, 'attacking_side': 'right_to_left', 'event_type_id': 8, 'event_type': 'player_possession', 'event_subtype_id': nan, 'event_subtype': nan, 'player_id': 33697, 'player_name': 'N. Pijnaker', 'team_id': 4177, 'x_start': -27.84, 'y_start': 6.4, 'x_end': -23.05, 'y_end': 13.87}]
Frame 212 has events: [{'event_id': '8_3', 'index': 14, 'frame_start': 202, 'frame_end': 229, 'attacking_side': 'right_to_left', 'event_type_id': 8, 'event_type': 'player_possession', 'event_subtype_id': nan, 'event_subtype': nan, 'player_id': 33697, 'player_name': 'N. Pijnaker', 'team_id': 4177, 'x_start': -27.84, 'y_start': 6.4, 'x_end': -23.05, 'y_end': 13.87}]
Frame 213 has events: [{'event_id': '8_3', 'index': 14, 'frame_start': 202, 'frame_end': 229, 'attacking_side': 'right_to_left', 'event_type_id': 8, 'event_type': 'player_possession', 'event_subtype_id': nan, 'event_subtype': nan, 'player_id': 33697, 'player_name': 'N. Pijnaker', 'team_id': 4177, 'x_start': -27.84, 'y_start': 6.4, 'x_end': -23.05, 'y_end': 13.87}]
Frame 214 has events: [{'event_id': '8_3', 'index': 14, 'frame_start': 202, 'frame_end': 229, 'attacking_side': 'right_to_left', 'event_type_id': 8, 'event_type': 'player_possession', 'event_subtype_id': nan, 'event_subtype': nan, 'player_id': 33697, 'player_name': 'N. Pijnaker', 'team_id': 4177, 'x_start': -27.84, 'y_start': 6.4, 'x_end': -23.05, 'y_end': 13.87}]
Frame 215 has events: [{'event_id': '8_3', 'index': 14, 'frame_start': 202, 'frame_end': 229, 'attacking_side': 'right_to_left', 'event_type_id': 8, 'event_type': 'player_possession', 'event_subtype_id': nan, 'event_subtype': nan, 'player_id': 33697, 'player_name': 'N. Pijnaker', 'team_id': 4177, 'x_start': -27.84, 'y_start': 6.4, 'x_end': -23.05, 'y_end': 13.87}]

In [6]:
frames['50']

{'period': 1.0,
 'players': {'x': [-40.39,
   -21.62,
   -22.29,
   4.98,
   -20.68,
   -4.54,
   -10.79,
   6.36,
   5.41,
   1.47,
   4.98,
   41.35,
   16.73,
   18.31,
   14.68,
   16.94,
   7.05,
   6.81,
   1.13,
   7.63,
   -9.85,
   -6.1],
  'y': [0.21,
   -10.09,
   1.44,
   -32.17,
   16.83,
   7.32,
   -2.25,
   9.54,
   -19.52,
   16.49,
   0.34,
   -0.01,
   3.6,
   -5.28,
   13.85,
   -16.34,
   7.2,
   -2.33,
   15.32,
   -19.86,
   -2.33,
   9.59],
  'player_id': [51009,
   176224,
   51649,
   50983,
   735578,
   50978,
   735574,
   795507,
   795505,
   735573,
   966120,
   285188,
   51667,
   33697,
   51713,
   133498,
   14736,
   23418,
   133501,
   965685,
   50951,
   38673],
  'id': [51009,
   176224,
   51649,
   50983,
   735578,
   50978,
   735574,
   795507,
   795505,
   735573,
   966120,
   285188,
   51667,
   33697,
   51713,
   133498,
   14736,
   23418,
   133501,
   965685,
   50951,
   38673],
  'short_name': ['R. Scott',
   'P. Cancar',
   'A. Šušnjar',
   'D. Ingham',
   'M. Natta',
   'C. Timmins',
   'K. Grozos',
   'L. Bayliss',
   'E. Adams',
   'T. Aquilina',
   'B. Gibson',
   'A. Paulsen',
   'D. Hall',
   'N. Pijnaker',
   'C. Elliott',
   'F. De Vries',
   'L. Verstraete',
   'F. Gallegos',
   'L. Rogerson',
   'L. Gillion',
   'J. Brimmer',
   'G. May'],
  'number': [1,
   4,
   15,
   14,
   33,
   19,
   17,
   37,
   7,
   39,
   22,
   12,
   23,
   4,
   17,
   15,
   6,
   28,
   27,
   14,
   22,
   10],
  'team_id': [1805,
   1805,
   1805,
   1805,
   1805,
   1805,
   1805,
   1805,
   1805,
   1805,
   1805,
   4177,
   4177,
   4177,
   4177,
   4177,
   4177,
   4177,
   4177,
   4177,
   4177,
   4177],
  'total_time': [5400,
   5400,
   5400,
   5400,
   5400,
   5098,
   5400,
   3615,
   5098,
   5400,
   4063,
   5400,
   5400,
   5400,
   5400,
   5400,
   5400,
   5400,
   4193,
   5400,
   4597,
   5121],
  'player_role.name': ['Goalkeeper',
   'Right Center Back',
   'Left Center Back',
   'Right Back',
   'Left Back',
   'Left Defensive Midfield',
   'Right Defensive Midfield',
   'Attacking Midfield',
   'Right Winger',
   'Left Winger',
   'Center Forward',
   'Goalkeeper',
   'Right Center Back',
   'Left Center Back',
   'Right Back',
   'Left Back',
   'Defensive Midfield',
   'Attacking Midfield',
   'Right Winger',
   'Left Winger',
   'Center Forward',
   'Center Forward'],
  'player_role.acronym': ['GK',
   'RCB',
   'LCB',
   'RB',
   'LB',
   'LDM',
   'RDM',
   'AM',
   'RW',
   'LW',
   'CF',
   'GK',
   'RCB',
   'LCB',
   'RB',
   'LB',
   'DM',
   'AM',
   'RW',
   'LW',
   'CF',
   'CF'],
  'is_gk': [True,
   False,
   False,
   False,
   False,
   False,
   False,
   False,
   False,
   False,
   False,
   True,
   False,
   False,
   False,
   False,
   False,
   False,
   False,
   False,
   False,
   False],
  'direction_player_1st_half': ['left_to_right',
   'left_to_right',
   'left_to_right',
   'left_to_right',
   'left_to_right',
   'left_to_right',
   'left_to_right',
   'left_to_right',
   'left_to_right',
   'left_to_right',
   'left_to_right',
   'right_to_left',
   'right_to_left',
   'right_to_left',
   'right_to_left',
   'right_to_left',
   'right_to_left',
   'right_to_left',
   'right_to_left',
   'right_to_left',
   'right_to_left',
   'right_to_left'],
  'direction_player_2nd_half': ['right_to_left',
   'right_to_left',
   'right_to_left',
   'right_to_left',
   'right_to_left',
   'right_to_left',
   'right_to_left',
   'right_to_left',
   'right_to_left',
   'right_to_left',
   'right_to_left',
   'left_to_right',
   'left_to_right',
   'left_to_right',
   'left_to_right',
   'left_to_right',
   'left_to_right',
   'left_to_right',
   'left_to_right',
   'left_to_right',
   'left_to_right',
   'left_to_right']},
 'ball': {'ball_x': -21.44, 'ball_y': 1.08, 'ball_z': 0.26},
 'events': [{'event_id': '8_1',
   'index': 1,
   'frame_start': 48,
   'frame_end': 58,
   'attacking_side': 'left_to_right',
   'event_type_id': 8,
   'event_type': 'player_possession',
   'event_subtype_id': nan,
   'event_subtype': nan,
   'player_id': 51649,
   'player_name': 'A. Šušnjar',
   'team_id': 1805,
   'x_start': -22.31,
   'y_start': 1.22,
   'x_end': -22.21,
   'y_end': 2.7}]}

In [5]:
# start=1000
# end=1050
# filtered_frames = {frame_num: frames[str(frame_num)] for frame_num in range(start, end + 1) if str(frame_num) in frames}
# filtered_frames

In [7]:
# To view tracking data at different stages of the pipeline
bronze_tracking_data = di._get_bronze_tracking_data(match_id=1899585)
silver_tracking_data = di._get_silver_tracking_data(bronze_tracking_data)
bronze_meta_data = di._get_bronze_meta_data(match_id=1899585)
silver_meta_data = di._get_silver_meta_data(bronze_meta_data)
bronze_event_data = di._get_bronze_event_data(match_id=1899585)
silver_event_data = di._get_silver_event_data(bronze_event_data)
gold_data = di._get_gold_tracking_data(silver_tracking_data, silver_meta_data, silver_event_data)

/Users/mihirthalanki/Documents/MT/Hackathon/PlayTactix/backend/services/data_ingestor_github.py:217: DtypeWarning: Columns (276) have mixed types. Specify dtype option on import or set low_memory=False.
  raw_data = pd.read_csv(event_data_github_url)

In [8]:
silver_event_data.head()

,event_id,index,frame_start,frame_end,attacking_side,event_type_id,event_type,event_subtype_id,event_subtype,player_id,player_name,team_id,x_start,y_start,x_end,y_end
0,8_0,0,12,12,left_to_right,8,player_possession,NaN,NaN,23909,K. Barbarouses,867,0.53,-0.28,0.53,-0.28
1,8_1,1,31,44,left_to_right,8,player_possession,NaN,NaN,42510,S. Wootton,867,-20.68,0.53,-20.75,-0.04
2,7_0,2,31,32,left_to_right,7,passing_option,NaN,NaN,51015,A. Rufer,867,-9.38,-3.50,-9.36,-3.52
3,7_1,3,31,44,left_to_right,7,passing_option,NaN,NaN,799092,M. Sheridan,867,-17.97,-13.76,-18.41,-14.35
4,9_0,4,37,44,right_to_left,9,on_ball_engagement,11.0,pressing,38673,G. May,4177,11.77,-3.34,15.46,-1.41

In [12]:
gold_data[50]

{'period': 1.0,
 'players': {'x': [-40.39,
   -21.62,
   -22.29,
   4.98,
   -20.68,
   -4.54,
   -10.79,
   6.36,
   5.41,
   1.47,
   4.98,
   41.35,
   16.73,
   18.31,
   14.68,
   16.94,
   7.05,
   6.81,
   1.13,
   7.63,
   -9.85,
   -6.1],
  'y': [0.21,
   -10.09,
   1.44,
   -32.17,
   16.83,
   7.32,
   -2.25,
   9.54,
   -19.52,
   16.49,
   0.34,
   -0.01,
   3.6,
   -5.28,
   13.85,
   -16.34,
   7.2,
   -2.33,
   15.32,
   -19.86,
   -2.33,
   9.59],
  'player_id': [51009,
   176224,
   51649,
   50983,
   735578,
   50978,
   735574,
   795507,
   795505,
   735573,
   966120,
   285188,
   51667,
   33697,
   51713,
   133498,
   14736,
   23418,
   133501,
   965685,
   50951,
   38673],
  'id': [51009,
   176224,
   51649,
   50983,
   735578,
   50978,
   735574,
   795507,
   795505,
   735573,
   966120,
   285188,
   51667,
   33697,
   51713,
   133498,
   14736,
   23418,
   133501,
   965685,
   50951,
   38673],
  'short_name': ['R. Scott',
   'P. Cancar',
   'A. Šušnjar',
   'D. Ingham',
   'M. Natta',
   'C. Timmins',
   'K. Grozos',
   'L. Bayliss',
   'E. Adams',
   'T. Aquilina',
   'B. Gibson',
   'A. Paulsen',
   'D. Hall',
   'N. Pijnaker',
   'C. Elliott',
   'F. De Vries',
   'L. Verstraete',
   'F. Gallegos',
   'L. Rogerson',
   'L. Gillion',
   'J. Brimmer',
   'G. May'],
  'number': [1,
   4,
   15,
   14,
   33,
   19,
   17,
   37,
   7,
   39,
   22,
   12,
   23,
   4,
   17,
   15,
   6,
   28,
   27,
   14,
   22,
   10],
  'team_id': [1805,
   1805,
   1805,
   1805,
   1805,
   1805,
   1805,
   1805,
   1805,
   1805,
   1805,
   4177,
   4177,
   4177,
   4177,
   4177,
   4177,
   4177,
   4177,
   4177,
   4177,
   4177],
  'total_time': [5400,
   5400,
   5400,
   5400,
   5400,
   5098,
   5400,
   3615,
   5098,
   5400,
   4063,
   5400,
   5400,
   5400,
   5400,
   5400,
   5400,
   5400,
   4193,
   5400,
   4597,
   5121],
  'player_role.name': ['Goalkeeper',
   'Right Center Back',
   'Left Center Back',
   'Right Back',
   'Left Back',
   'Left Defensive Midfield',
   'Right Defensive Midfield',
   'Attacking Midfield',
   'Right Winger',
   'Left Winger',
   'Center Forward',
   'Goalkeeper',
   'Right Center Back',
   'Left Center Back',
   'Right Back',
   'Left Back',
   'Defensive Midfield',
   'Attacking Midfield',
   'Right Winger',
   'Left Winger',
   'Center Forward',
   'Center Forward'],
  'player_role.acronym': ['GK',
   'RCB',
   'LCB',
   'RB',
   'LB',
   'LDM',
   'RDM',
   'AM',
   'RW',
   'LW',
   'CF',
   'GK',
   'RCB',
   'LCB',
   'RB',
   'LB',
   'DM',
   'AM',
   'RW',
   'LW',
   'CF',
   'CF'],
  'is_gk': [True,
   False,
   False,
   False,
   False,
   False,
   False,
   False,
   False,
   False,
   False,
   True,
   False,
   False,
   False,
   False,
   False,
   False,
   False,
   False,
   False,
   False],
  'direction_player_1st_half': ['left_to_right',
   'left_to_right',
   'left_to_right',
   'left_to_right',
   'left_to_right',
   'left_to_right',
   'left_to_right',
   'left_to_right',
   'left_to_right',
   'left_to_right',
   'left_to_right',
   'right_to_left',
   'right_to_left',
   'right_to_left',
   'right_to_left',
   'right_to_left',
   'right_to_left',
   'right_to_left',
   'right_to_left',
   'right_to_left',
   'right_to_left',
   'right_to_left'],
  'direction_player_2nd_half': ['right_to_left',
   'right_to_left',
   'right_to_left',
   'right_to_left',
   'right_to_left',
   'right_to_left',
   'right_to_left',
   'right_to_left',
   'right_to_left',
   'right_to_left',
   'right_to_left',
   'left_to_right',
   'left_to_right',
   'left_to_right',
   'left_to_right',
   'left_to_right',
   'left_to_right',
   'left_to_right',
   'left_to_right',
   'left_to_right',
   'left_to_right',
   'left_to_right']},
 'ball': {'ball_x': np.float64(-21.44),
  'ball_y': np.float64(1.08),
  'ball_z': np.float64(0.26)},
 'events': [{'event_id': '8_1',
   'index': 1,
   'frame_start': 48,
   'frame_end': 58,
   'attacking_side': 'left_to_right',
   'event_type_id': 8,
   'event_type': 'player_possession',
   'event_subtype_id': nan,
   'event_subtype': nan,
   'player_id': 51649,
   'player_name': 'A. Šušnjar',
   'team_id': 1805,
   'x_start': -22.31,
   'y_start': 1.22,
   'x_end': -22.21,
   'y_end': 2.7}]}

In [7]:
silver_data = silver_tracking_data.merge(
            silver_meta_data, left_on=["player_id"], right_on=["id"]
        )

In [8]:
pd.set_option('display.max_columns', None)  # Show all columns

In [9]:
def build_frame_dict(tracking_data, event_data):
    frames = {}
    event_idx = 0
    n_events = len(event_data)
    for frame_number, group in tracking_data.groupby("frame"):
        # Add tracking data
        frames[frame_number] = {
                #'is_detected': group['is_detected'].iloc[0],
                #'timestamp': group['timestamp'].iloc[0],
                'period': group['period'].iloc[0],
                'players': {
                    'x': group['x'].tolist(),
                    'y': group['y'].tolist(),
                    'player_id': group['player_id'].tolist(),
                    'id': group['id'].tolist(),
                    'short_name': group['short_name'].tolist(),
                    'number': group['number'].tolist(),
                    'team_id': group['team_id'].tolist(),
                    'total_time': group['total_time'].tolist(),
                    'player_role.name': group['player_role.name'].tolist(),
                    'player_role.acronym': group['player_role.acronym'].tolist(),
                    'is_gk': group['is_gk'].tolist(),
                    'direction_player_1st_half': group['direction_player_1st_half'].tolist(),
                    'direction_player_2nd_half': group['direction_player_2nd_half'].tolist(),
                },
                'ball': {
                    'ball_x': group['ball_x'].iloc[0],
                    'ball_y': group['ball_y'].iloc[0],
                    'ball_z': group['ball_z'].iloc[0],
                    #'is_detected_ball': group['is_detected_ball'].iloc[0],
                },
                'events': []
            }
        # Add event data
        while event_idx < n_events and event_data.iloc[event_idx]['frame_start'] <= frame_number:
            event = event_data.iloc[event_idx]
            if event['frame_start'] <= frame_number <= event['frame_end']:
                frames[frame_number]['events'].append(event.to_dict())
            if event['frame_end'] < frame_number:
                event_idx += 1
            else:
                break
    
    return frames

In [10]:
gold_frames = build_frame_dict(silver_data, silver_event_data)

KeyboardInterrupt:

In [ ]:
gold_frames[58]['events']

[{'event_id': '8_1',
  'index': 1,
  'frame_start': 48,
  'frame_end': 58,
  'attacking_side': 'left_to_right',
  'event_type_id': 8,
  'event_type': 'player_possession',
  'event_subtype_id': nan,
  'event_subtype': nan,
  'player_id': 51649,
  'player_name': 'A. Šušnjar',
  'team_id': 1805,
  'x_start': -22.31,
  'y_start': 1.22,
  'x_end': -22.21,
  'y_end': 2.7}]

In [ ]:
silver_event_data.head()

,event_id,index,frame_start,frame_end,attacking_side,event_type_id,event_type,event_subtype_id,event_subtype,player_id,player_name,team_id,x_start,y_start,x_end,y_end
0,8_0,0,28,28,left_to_right,8,player_possession,NaN,NaN,966120,B. Gibson,1805,0.73,0.49,0.73,0.49
1,8_1,1,48,58,left_to_right,8,player_possession,NaN,NaN,51649,A. Šušnjar,1805,-22.31,1.22,-22.21,2.70
2,7_0,2,48,53,left_to_right,7,passing_option,NaN,NaN,735574,K. Grozos,1805,-10.47,-2.78,-11.36,-1.38
3,7_1,3,48,58,left_to_right,7,passing_option,NaN,NaN,735578,M. Natta,1805,-20.69,16.66,-20.36,17.69
4,9_0,4,56,58,right_to_left,9,on_ball_engagement,11.0,pressing,50951,J. Brimmer,4177,13.03,0.06,13.98,-0.68