In [16]:
import pandas as pd
import requests
import numpy as np
import json

pd.set_option('display.max_columns', None)  # Show all columns

from data_ingestor_github import SkillCornerDataIngestor
di = SkillCornerDataIngestor()

In [17]:
bronze_event_data = di._get_bronze_event_data(match_id=1899585)

/Users/mihirthalanki/Documents/MT/Hackathon/PlayTactix/backend/services/data_ingestor_github.py:221: DtypeWarning: Columns (276) have mixed types. Specify dtype option on import or set low_memory=False.
  raw_data = pd.read_csv(event_data_github_url)

In [18]:
# Get all rows of data where a shot was taken
bronze_event_data[bronze_event_data['lead_to_shot'] == True].head()

,event_id,index,match_id,frame_start,frame_end,frame_physical_start,time_start,time_end,minute_start,second_start,duration,period,attacking_side_id,attacking_side,event_type_id,event_type,event_subtype_id,event_subtype,player_id,player_name,player_position_id,player_position,player_in_possession_id,player_in_possession_name,player_in_possession_position_id,player_in_possession_position,team_id,team_shortname,x_start,y_start,channel_id_start,channel_start,third_id_start,third_start,penalty_area_start,x_end,y_end,channel_id_end,channel_end,third_id_end,third_end,penalty_area_end,associated_player_possession_event_id,associated_player_possession_frame_start,associated_player_possession_frame_end,associated_player_possession_end_type_id,associated_player_possession_end_type,associated_off_ball_run_event_id,associated_off_ball_run_subtype_id,associated_off_ball_run_subtype,game_state_id,game_state,team_score,opponent_team_score,phase_index,player_possession_phase_index,first_player_possession_in_team_possession,last_player_possession_in_team_possession,lead_to_different_phase,issued_from_different_phase,n_player_possessions_in_phase,team_possession_loss_in_phase,team_in_possession_phase_type_id,team_in_possession_phase_type,team_out_of_possession_phase_type_id,team_out_of_possession_phase_type,current_team_in_possession_next_phase_type_id,current_team_in_possession_next_phase_type,current_team_out_of_possession_next_phase_type_id,current_team_out_of_possession_next_phase_type,current_team_in_possession_previous_phase_type_id,current_team_in_possession_previous_phase_type,current_team_out_of_possession_previous_phase_type_id,current_team_out_of_possession_previous_phase_type,game_interruption_before_id,game_interruption_before,game_interruption_after_id,game_interruption_after,lead_to_shot,lead_to_goal,distance_covered,trajectory_angle,trajectory_direction_id,trajectory_direction,in_to_out,out_to_in,speed_avg,speed_avg_band_id,speed_avg_band,separation_start,separation_end,separation_gain,last_defensive_line_x_start,last_defensive_line_x_end,delta_to_last_defensive_line_start,delta_to_last_defensive_line_end,delta_to_last_defensive_line_gain,last_defensive_line_height_start,last_defensive_line_height_end,last_defensive_line_height_gain,inside_defensive_shape_start,inside_defensive_shape_end,start_type_id,start_type,end_type_id,end_type,consecutive_on_ball_engagements,one_touch,quick_pass,carry,forward_momentum,is_header,hand_pass,initiate_give_and_go,pass_angle_received,pass_direction_received_id,pass_direction_received,pass_distance_received,pass_range_received_id,pass_range_received,pass_outcome_id,pass_outcome,targeted_passing_option_event_id,high_pass,player_targeted_id,player_targeted_name,player_targeted_position_id,player_targeted_position,player_targeted_x_pass,player_targeted_y_pass,player_targeted_channel_pass_id,player_targeted_channel_pass,player_targeted_third_pass_id,player_targeted_third_pass,player_targeted_penalty_area_pass,player_targeted_x_reception,player_targeted_y_reception,player_targeted_channel_reception_id,player_targeted_channel_reception,player_targeted_third_reception_id,player_targeted_third_reception,player_targeted_penalty_area_reception,player_targeted_distance_to_goal_start,player_targeted_distance_to_goal_end,player_targeted_angle_to_goal_start,player_targeted_angle_to_goal_end,player_targeted_average_speed,player_targeted_speed_avg_band_id,player_targeted_speed_avg_band,speed_difference,player_targeted_xpass_completion,player_targeted_difficult_pass_target,player_targeted_xthreat,player_targeted_dangerous,n_passing_options,n_off_ball_runs,n_passing_options_line_break,n_passing_options_first_line_break,n_passing_options_second_last_line_break,n_passing_options_last_line_break,n_passing_options_ahead,n_passing_options_dangerous_difficult,n_passing_options_dangerous_not_difficult,n_passing_options_not_dangerous_not_difficult,n_passing_options_not_dangerous_difficult,n_passing_options_at_start,n_passing_options_at_end,n_passing_options_ahead_at_start,n_passing_options_ahead_at_end,n_teammates_ahead_end,n_teammates_ahead_start,n_player_targeted_opponents_ahead_start,n_player_targeted_opponents_ahead_end,n_player_targeted_teammates_ahead_start,n_player_targeted_teammates_ahead_end,n_player_targeted_teammates_within_5m_start,n_player_targeted_teammates_within_5m_end,n_player_targeted_opponents_within_5m_start,n_player_targeted_opponents_within_5m_end,organised_defense,defensive_structure,n_defensive_lines,first_line_break,first_line_break_type_id,first_line_break_type,second_last_line_break,second_last_line_break_type_id,second_last_line_break_type,last_line_break,last_line_break_type_id,last_line_break_type,furthest_line_break_id,furthest_line_break,furthest_line_break_type_id,furthest_line_break_type,interplayer_distance,interplayer_distance_range_id,interplayer_distance_range,interplayer_distance_start,interplayer_distance_end,interplayer_distance_min,interplayer_distance_start_physical,close_at_player_possession_start,interplayer_angle,interplayer_direction_id,interplayer_direction,angle_of_engagement,goal_side_start,goal_side_end,pass_distance,pass_range_id,pass_range,pass_angle,pass_direction_id,pass_direction,pass_ahead,n_opponents_ahead_player_in_possession_pass_moment,n_opponents_ahead_pass_reception,n_opponents_bypassed,location_to_player_in_possession_id_start,location_to_player_in_possession_start,location_to_player_in_possession_id_end,location_to_player_in_possession_end,distance_to_player_in_possession_start,distance_to_player_in_possession_end,player_in_possession_x_start,player_in_possession_y_start,player_in_possession_channel_id_start,player_in_possession_channel_start,player_in_possession_third_id_start,player_in_possession_third_start,player_in_possession_penalty_area_start,player_in_possession_x_end,player_in_possession_y_end,player_in_possession_channel_id_end,player_in_possession_channel_end,player_in_possession_third_id_end,player_in_possession_third_end,player_in_possession_penalty_area_end,targeted,received,received_in_space,dangerous,difficult_pass_target,xthreat,xpass_completion,passing_option_score,predicted_passing_option,peak_passing_option_frame,passing_option_at_player_possession_start,n_simultaneous_runs,give_and_go,intended_run_behind,push_defensive_line,break_defensive_line,passing_option_at_start,n_simultaneous_passing_options,passing_option_at_pass_moment,n_opponents_ahead_end,n_opponents_ahead_start,n_opponents_overtaken,pressing_chain,pressing_chain_length,pressing_chain_end_type_id,pressing_chain_end_type,pressing_chain_index,index_in_pressing_chain,simultaneous_defensive_engagement_same_target,simultaneous_defensive_engagement_same_target_rank,affected_line_breaking_passing_option_id,affected_line_break_id,affected_line_break,affected_line_breaking_passing_option_attempted,affected_line_breaking_passing_option_xthreat,affected_line_breaking_passing_option_dangerous,affected_line_breaking_passing_option_run_subtype_id,affected_line_breaking_passing_option_run_subtype,possession_danger,beaten_by_possession,beaten_by_movement,stop_possession_danger,reduce_possession_danger,force_backward,xloss_player_possession_start,xloss_player_possession_end,xloss_player_possession_max,xshot_player_possession_start,xshot_player_possession_end,xshot_player_possession_max,is_player_possession_start_matched,is_player_possession_end_matched,is_previous_pass_matched,is_pass_reception_matched,fully_extrapolated
173,8_37,173,1899585,2194,2212,NaN,03:38.4,03:40.2,3,38,1.8,1,2,right_to_left,8,player_possession,NaN,NaN,33697,N. Pijnaker,4,LCB,NaN,NaN,NaN,NaN,4177,Auckland FC,47.18,5.67,3,center,3,attacking_third,True,46.24,10.27,2,half_space_left,3,attacking_third,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,drawing,0,0,20,1.0,False,True,True,True,10.0,False,7,set_play,13,defending_set_play,2.0,finish,8.0,low_block,5.0,chaotic,5.0,chaotic,1.0,corner_for,NaN,NaN,True,False,4.89,101.55,3.0,sideway_left,True,False,9.77,1.0,jogging,1.48,2.60,1.12,49.95,49.04,2.77,2.80,0.03,2.05,2.96,0.91,True,True,11.0,corner_reception,2.0,shot,NaN,False,False,True,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,False
931,1_79,931,1899585,9367,9383,NaN,15:35.7,15:37.3,15,35,1.6,1,2,right_to_left,1,off_ball_run,3.0,cross_receiver,23418,F. Gallegos,12,LM,50951.0,J. Brimmer,19.0,CF,4177,Auckland FC,29.97,-0.42,3,center,3,attacking_third,False,37.72,-4.97,3,center,3,attacking_third,True,8_196,9365.0,NaN,NaN,NaN,NaN,NaN,NaN,3,drawing,0,0,88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,finish,8,low_block,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,False,8.99,-30.42,1.0,forward,False,False,20.12,3.0,hsr,6.48,4.97,-1.51,42.77,44.14,12.80,6.42,-6.38,9.23,7.86,-1.37,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,behind,2.0,same_line,20.36,8.25,33.46,-20.48,5.0,wide_right,3.0,attacking_third,False,36.18,-13.08,4.0,half_space_right,3.0,attacking_third,True,True,False,NaN,True,False,0.0426,0.8131,0.8841,True,NaN,True,0.0,False,NaN,NaN,NaN,True,NaN,NaN,5.0,6.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,NaN,NaN
936,9_187,936,1899585,9431,9466,9431.0,15:42.1,15:45.6,15,42,3.5,1,1,left_to_right,9,on_ball_engagement,15.0,other,51015,A. Rufer,12,LM,133501.0,L. Rogerson,17.0,RW,867,Wellington P FC,-46.73,19.66,2,half_space_left,1,defensive_third,True,-50.04,23.44,1,wide_left,1,defensive_third,False,8_198,9433.0,9466.0,1.0,pass,NaN,NaN,NaN,3,drawing,0,0,90,NaN,NaN,NaN,NaN,NaN,NaN,True,2,finish,8,low_block,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,False,6.23,131.21,3.0,sideway_left,NaN,NaN,6.35,1.0,jogging,NaN,NaN,NaN,-46.73,-50.04,0.00,0.00,0.00,5.27,1.96,-3.31,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,133501.0,L. Rogerson,17.0,RW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.39,19.5,-104.48,-93.41,10.97,1.0,jogging,-4.62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,9.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.05,4.05,0.62,1.05,True,NaN,NaN,NaN,-5.66,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,True,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,False,False,False,False,0.373,0.34,0.444,0.021,0.002,0.021,True,True,NaN,True,NaN
937,8_198,937,1899585,9433,9466,NaN,15:42.3,15:45.6,15,42,3.3,1,2,right_to_left,8,player_possession,NaN,NaN,133501,L. Rogerson,17,RW,NaN,NaN,NaN,NaN,4177,Auckland FC,47.05,-21.68,5,wide_right,3,attacking_third,False,50.84,-19.47,4,half_space_right,3,attacking_third,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,drawing,0,0,90,1.0,True,False,False,True,2.0,True,2,finish,8,low_block,5.0,chaotic,5.0,chaotic,5.0,chaotic,5.0,chaotic,NaN,NaN,NaN,NaN,True,False,9.28,30.25,1.0,forward,False,True,10.48,1.0,jogging,1.02,4.05,3.03,47.02,50.04,-0.03,-0.80,-0.77,4.98,1.96,-3.02,False,False,4.0,recovery,1.0,pass,NaN,False,False,True,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,1.0,successful,7_471,False,23418.0,F. Gallegos,12.0,LM,43.28,-20.79,5.0,wide_right,3.0,attacking_third,False,40.83,-17.47,4.0,half_space_right,3.0,attacking_third,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.2658,True,0.0196,False,3.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,1.0,2.0,3.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.67,1.0,short,NaN,NaN,NaN,NaN,NaN,-170.1,2.0,backward,NaN,NaN,NaN,8.38,1.0,short,-147.86,2.0,backward,False,0.0,6.0,-6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,True,False
938,7_471,938,1899585,9433,9466,NaN,15:42.3,15:45.6,15,42,3.3,1,2,right_to_left,7,passing_option,NaN,NaN,23418,F. Gallegos,12,LM,133501.0,L. Rogerson,17.0,RW,4177,Auckland FC,39.67,-17.84,4,half_space_right,3,attacking_third,True,43.28,-20.79,5,wide_right,3,attacking_third,False,8_198,9433.0,NaN,NaN,NaN,NaN,NaN,NaN,3,drawing,0,0,90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,finish,8,low_block,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,False,7.91,-39.25,1.0,forward,True,False,8.96,1.0,jogging,5.19,0.97,-4.22,47.02,50.04,7.35,6.76,-0.59,4.98,1.96,-3.02,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.67,1.0,short,NaN,NaN,NaN,NaN,NaN,-170.1,2.0,backward,NaN,NaN,NaN,8.38,1.0,short,-147.86,2.0,backward,False,0.0,6.0,-6.0,1.0,behind,1.0,behind,8.32,7.67,47.05,-21.68,5.0,wide_right,3.0,attacking_third,False,50.84,-19.47,4.0,half_space_right,3.0,attacking_third,True,True,True,False,False,True,0.0196,0.2658,0.8572,True,9466.0,True,NaN,NaN,NaN,NaN,NaN,NaN,2.0,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,NaN,True,False

In [36]:
def find_all_goals_scored(df):
    df = df[(df['lead_to_goal'] == True) & (df['event_type'] == 'player_possession')]
    return (df['end_type'] == 'shot').cumsum().shift(1, fill_value=0) + 1

In [37]:
events_data_copy = bronze_event_data.copy()
events_data_copy["Sequence_ID"] = find_all_goals_scored(events_data_copy)
grouped_data = events_data_copy.groupby("Sequence_ID").agg({'frame_start': 'min', 'frame_end': 'max', 'match_id': 'first', 'lead_to_shot': 'first'}).reset_index()

In [38]:
display(grouped_data)

   Sequence_ID  frame_start  frame_end  match_id  lead_to_shot
0          1.0        44380      44380   1899585          True
1          2.0        51849      51899   1899585          True